### ISSUE TITLE
node-webkit for Linux crash on this app

### ISSUE THREAD

**Issue by libm** [nwjs/nw.js#1864]
package.json
```
{
  "name": "nw-tests",
  "main": "index.html",
  "window": {
    "show": false
  }
}
```
index.html
```
<html>
<head>
</head>
<body>
<script type="text/javascript" charset="utf-8">
	var gui = require('nw.gui');
	gui.Window.get().show();
	gui.App.quit();
</script>
</body>
</html>
```

bt for this segfault

```
Program received signal SIGSEGV, Segmentation fault.
__GI___pthread_mutex_lock (mutex=0x7fffffffc8d0) at ../nptl/pthread_mutex_lock.c:66
66      ../nptl/pthread_mutex_lock.c: No such file or directory.
(gdb) bt
#0  __GI___pthread_mutex_lock (mutex=0x7fffffffc8d0) at ../nptl/pthread_mutex_lock.c:66
#1  0x00000000007deadc in base::internal::LockImpl::Lock (this=0x3636363636363646) at ../../base/synchronization/lock_impl_posix.cc:45
#2  0x0000000000745e72 in base::Lock::Acquire (this=0x363636363636363e) at ../../base/synchronization/lock.h:41
#3  0x0000000000745ed4 in base::AutoLock::AutoLock (this=0x7fffffffc450, lock=...) at ../../base/synchronization/lock.h:102
#4  0x00000000007c212c in base::SequenceCheckerImpl::CalledOnValidSequencedThread (this=0x363636363636363e) at ../../base/sequence_checker_impl.cc:18
#5  0x0000000000799f08 in base::internal::WeakReference::Flag::IsValid (this=0x3636363636363636) at ../../base/memory/weak_ptr.cc:26
#6  0x000000000079a07b in base::internal::WeakReference::is_valid (this=0x29effa6dd628) at ../../base/memory/weak_ptr.cc:43
#7  0x000000000070e070 in base::WeakPtr<content::Shell>::get (this=0x29effa6dd628) at ../../base/memory/weak_ptr.h:203
#8  0x000000000074083c in nw::NativeWindow::shell (this=0x29effa6dd620) at ../../content/nw/src/browser/native_window.h:121
#9  0x000000000073ffa6 in nw::NativeWindowGtk::OnWindowConfigureEvent (this=0x29effa6dd620, window=0x29effa87c150, event=0x29effaae19e0)
    at ../../content/nw/src/browser/native_window_gtk.cc:612
#10 0x0000000000740b47 in nw::NativeWindowGtk::OnWindowConfigureEventThunk (sender=0x29effa87c150, one=0x29effaae19e0, userdata=0x29effa6dd620)
    at ../../content/nw/src/browser/native_window_gtk.h:121
#11 0x00007ffff620e4f5 in _gtk_marshal_BOOLEAN__BOXED (closure=0x29effa93c440, return_value=0x7fffffffc880, n_param_values=<optimized out>,
    param_values=0x7fffffffc930, invocation_hint=<optimized out>, marshal_data=0x0) at /tmp/buildd/gtk+2.0-2.24.23/gtk/gtkmarshalers.c:86
#12 0x00007ffff6e3c3b8 in g_closure_invoke (closure=0x29effa93c440, return_value=0x7fffffffc880, n_param_values=2, param_values=0x7fffffffc930,
    invocation_hint=0x7fffffffc8d0) at /tmp/buildd/glib2.0-2.40.0/./gobject/gclosure.c:768
#13 0x00007ffff6e4dd3d in signal_emit_unlocked_R (node=node@entry=0x29effa7bab60, detail=detail@entry=0, instance=instance@entry=0x29effa87c150,
    emission_return=emission_return@entry=0x7fffffffca00, instance_and_params=instance_and_params@entry=0x7fffffffc930)
    at /tmp/buildd/glib2.0-2.40.0/./gobject/gsignal.c:3551
#14 0x00007ffff6e556f9 in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>,
    var_args=var_args@entry=0x7fffffffcac8) at /tmp/buildd/glib2.0-2.40.0/./gobject/gsignal.c:3317
#15 0x00007ffff6e55ce2 in g_signal_emit (instance=instance@entry=0x29effa87c150, signal_id=<optimized out>, detail=detail@entry=0)
    at /tmp/buildd/glib2.0-2.40.0/./gobject/gsignal.c:3363
#16 0x00007ffff631e114 in gtk_widget_event_internal (widget=widget@entry=0x29effa87c150, event=event@entry=0x29effaae19e0)
    at /tmp/buildd/gtk+2.0-2.24.23/gtk/gtkwidget.c:5010
#17 0x00007ffff631e3e9 in IA__gtk_widget_event (widget=widget@entry=0x29effa87c150, event=event@entry=0x29effaae19e0)
    at /tmp/buildd/gtk+2.0-2.24.23/gtk/gtkwidget.c:4807
#18 0x00007ffff620d25b in IA__gtk_main_do_event (event=0x29effaae19e0) at /tmp/buildd/gtk+2.0-2.24.23/gtk/gtkmain.c:1639
#19 0x000000000080c233 in base::MessagePumpGtk::DispatchEvents (this=0x7ffff7e625d0, event=0x29effaae19e0) at ../../base/message_loop/message_pump_gtk.cc:78
#20 0x000000000080c45f in base::MessagePumpGtk::EventDispatcher (event=0x29effaae19e0, data=0x7ffff7e625d0)
    at ../../base/message_loop/message_pump_gtk.cc:117
#21 0x00007ffff5e881fc in gdk_event_dispatch (source=<optimized out>, callback=<optimized out>, user_data=<optimized out>)
    at /tmp/buildd/gtk+2.0-2.24.23/gdk/x11/gdkevents-x11.c:2403
#22 0x00007ffff696ae04 in g_main_dispatch (context=0x7ffff7e637a0) at /tmp/buildd/glib2.0-2.40.0/./glib/gmain.c:3064
#23 g_main_context_dispatch (context=context@entry=0x7ffff7e637a0) at /tmp/buildd/glib2.0-2.40.0/./glib/gmain.c:3663
#24 0x00007ffff696b048 in g_main_context_iterate (context=context@entry=0x7ffff7e637a0, block=block@entry=0, dispatch=dispatch@entry=1, self=<optimized out>)
    at /tmp/buildd/glib2.0-2.40.0/./glib/gmain.c:3734
#25 0x00007ffff696b0ec in g_main_context_iteration (context=0x7ffff7e637a0, may_block=0) at /tmp/buildd/glib2.0-2.40.0/./glib/gmain.c:3795
#26 0x000000000084bc8f in base::MessagePumpGlib::RunWithDispatcher (this=0x7ffff7e625d0, delegate=0x7ffff7f2aaa0, dispatcher=0x0)
    at ../../base/message_loop/message_pump_glib.cc:205
#27 0x000000000084c174 in base::MessagePumpGlib::Run (this=0x7ffff7e625d0, delegate=0x7ffff7f2aaa0) at ../../base/message_loop/message_pump_glib.cc:294
#28 0x000000000079bf98 in base::MessageLoop::RunInternal (this=0x7ffff7f2aaa0) at ../../base/message_loop/message_loop.cc:449
#29 0x000000000079beb6 in base::MessageLoop::RunHandler (this=0x7ffff7f2aaa0) at ../../base/message_loop/message_loop.cc:421
#30 0x00000000007c165a in base::RunLoop::Run (this=0x7fffffffd220) at ../../base/run_loop.cc:47
#31 0x0000000003de184d in content::BrowserMainLoop::MainMessageLoopRun (this=0x7ffff7e56520) at ../../content/browser/browser_main_loop.cc:1066
#32 0x0000000003ddf57a in content::BrowserMainLoop::RunMainMessageLoopParts (this=0x7ffff7e56520) at ../../content/browser/browser_main_loop.cc:719
#33 0x0000000003bb081a in content::BrowserMainRunnerImpl::Run (this=0x7ffff7efd200) at ../../content/browser/browser_main_runner.cc:121
#34 0x00000000006c8d1d in ShellBrowserMain (parameters=...) at ../../content/nw/src/shell_browser_main.cc:45
#35 0x00000000006b0884 in content::ShellMainDelegate::RunProcess (this=0x7fffffffdd70, process_type=..., main_function_params=...)
    at ../../content/nw/src/shell_main_delegate.cc:182
#36 0x00000000041137ba in content::RunNamedProcessTypeMain (process_type=..., main_function_params=..., delegate=0x7fffffffdd70)
    at ../../content/app/content_main_runner.cc:446
---Type <return> to continue, or q <return> to quit---
#37 0x000000000411497f in content::ContentMainRunnerImpl::Run (this=0x7ffff7e5d3a0) at ../../content/app/content_main_runner.cc:777
#38 0x0000000004112b8c in content::ContentMain (argc=2, argv=0x7fffffffdea8, delegate=0x7fffffffdd70) at ../../content/app/content_main.cc:35
#39 0x00000000006b034e in main (argc=2, argv=0x7fffffffdea8) at ../../content/nw/src/shell_main.cc:52
(gdb)
```

**Comment by felicienfrancois** [comment]
I also sometimes get segfault crash when quitting with nw0.12.0 (ubuntu 64bit), but it is not systematic.
