### ISSUE TITLE
drawable is not a native X11 window

### ISSUE THREAD

**Issue by demian85** [nwjs/nw.js#2589]
Linux Mint 17 KDE... broken in new v0.11

When hovering menu items, this error appears over and over again until app crashes.

```
[8268:1111/092942:ERROR:browser_main_loop.cc(206)] /build/buildd/gtk+2.0-2.24.23/gdk/x11/gdkdrawable-x11.c:942 drawable is not a native X11 window (http://bugs.chromium.org/329991)
[8268:1111/092942:ERROR:browser_main_loop.cc(206)] /build/buildd/gtk+2.0-2.24.23/gdk/x11/gdkdrawable-x11.c:942 drawable is not a native X11 window (http://bugs.chromium.org/329991)
[8268:1111/092942:ERROR:browser_main_loop.cc(206)] /build/buildd/gtk+2.0-2.24.23/gdk/x11/gdkdrawable-x11.c:942 drawable is not a native X11 window (http://bugs.chromium.org/329991)
[8268:1111/092944:ERROR:browser_main_loop.cc(206)] /build/buildd/gtk+2.0-2.24.23/gdk/x11/gdkdrawable-x11.c:942 drawable is not a native X11 window (http://bugs.chromium.org/329991)
[8268:1111/092945:ERROR:browser_main_loop.cc(206)] /build/buildd/gtk+2.0-2.24.23/gdk/x11/gdkdrawable-x11.c:942 drawable is not a native X11 window (http://bugs.chromium.org/329991)
[8268:1111/092946:ERROR:browser_main_loop.cc(206)] /build/buildd/gtk+2.0-2.24.23/gdk/x11/gdkdrawable-x11.c:942 drawable is not a native X11 window (http://bugs.chromium.org/329991)
[8268:1111/092947:ERROR:browser_main_loop.cc(206)] /build/buildd/gtk+2.0-2.24.23/gdk/x11/gdkdrawable-x11.c:942 drawable is not a native X11 window (http://bugs.chromium.org/329991)
[8268:1111/092950:ERROR:browser_main_loop.cc(206)] /build/buildd/gtk+2.0-2.24.23/gdk/x11/gdkdrawable-x11.c:942 drawable is not a native X11 window (http://bugs.chromium.org/329991)
[8268:1111/092951:ERROR:browser_main_loop.cc(206)] /build/buildd/gtk+2.0-2.24.23/gdk/x11/gdkdrawable-x11.c:942 drawable is not a native X11 window (http://bugs.chromium.org/329991)
[8268:1111/092951:ERROR:browser_main_loop.cc(206)] /build/buildd/gtk+2.0-2.24.23/gdk/x11/gdkdrawable-x11.c:942 drawable is not a native X11 window (http://bugs.chromium.org/329991)
[8291:1111/092952:WARNING:x11_util.cc(1408)] X error received: serial 1703, error_code 3 (BadWindow (invalid Window parameter)), request_code 4, minor_code 0 (X_DestroyWindow)
[8268:1111/092952:ERROR:browser_main_loop.cc(206)] /build/buildd/gtk+2.0-2.24.23/gdk/x11/gdkdrawable-x11.c:942 drawable is not a native X11 window (http://bugs.chromium.org/329991)
[8268:1111/092954:ERROR:browser_main_loop.cc(206)] /build/buildd/gtk+2.0-2.24.23/gdk/x11/gdkdrawable-x11.c:942 drawable is not a native X11 window (http://bugs.chromium.org/329991)
Segmentation fault
```
##

**Comment by demian85** [comment]
Still ugly menus

![bug](http://i.imgur.com/CuNkZ8Z.png)

**Comment by razykov** [comment]
It looks like this error is repeated in the KDE because of oxygen-gtk library. 
In version 0.10.5 this error was not

A call stack before error message:
```
(gdb) bt
#0  0x00007ffff2764b70 in gdk_x11_drawable_get_xid () from /usr/lib/libgdk-x11-2.0.so.0
#1  0x00007fffe9512838 in Oxygen::BackgroundHintEngine::registerWidget(_GtkWidget*, Oxygen::Flags<Oxygen::BackgroundHint>) () from /usr/lib/gtk-2.0/2.10.0/engines/liboxygen-gtk.so
#2  0x00007fffe95bc453 in ?? () from /usr/lib/gtk-2.0/2.10.0/engines/liboxygen-gtk.so
#3  0x00007ffff2c1820b in ?? () from /usr/lib/libgtk-x11-2.0.so.0
#4  0x00007ffff2c1825c in ?? () from /usr/lib/libgtk-x11-2.0.so.0
#5  0x00007ffff2af489f in ?? () from /usr/lib/libgtk-x11-2.0.so.0
#6  0x00007ffff7489255 in g_closure_invoke () from /usr/lib/libgobject-2.0.so.0
#7  0x00007ffff749ae42 in ?? () from /usr/lib/libgobject-2.0.so.0
#8  0x00007ffff74a3265 in g_signal_emit_valist () from /usr/lib/libgobject-2.0.so.0
#9  0x00007ffff74a39bf in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#10 0x00007ffff2c0b99c in ?? () from /usr/lib/libgtk-x11-2.0.so.0
#11 0x00007ffff2af3622 in gtk_main_do_event () from /usr/lib/libgtk-x11-2.0.so.0
#12 0x00007ffff2c0c679 in ?? () from /usr/lib/libgtk-x11-2.0.so.0
#13 0x00007ffff2c124d3 in gtk_widget_get_snapshot () from /usr/lib/libgtk-x11-2.0.so.0
#14 0x0000000002b70fc4 in libgtk2ui::Gtk2UI::DrawGtkButtonBorder (this=<optimized out>, gtk_state=<optimized out>, focused=<optimized out>, call_to_action=<optimized out>, width=<optimized out>, 
    height=<optimized out>) at ../../chrome/browser/ui/libgtk2ui/gtk2_ui.cc:1314
#15 0x0000000002b7e42e in libgtk2ui::(anonymous namespace)::ButtonImageSkiaSource::GetImageForScale (this=<optimized out>, scale=1) at ../../chrome/browser/ui/libgtk2ui/gtk2_border.cc:54
#16 0x000000000126cccf in gfx::internal::ImageSkiaStorage::FindRepresentation (this=0x3d48fe728340, scale=1, fetch_new_image=<optimized out>) at ../../ui/gfx/image/image_skia.cc:215
#17 0x000000000126d0c9 in gfx::ImageSkia::GetRepresentation (this=0x3d48fe53c1d0, scale=0) at ../../ui/gfx/image/image_skia.cc:394
#18 0x0000000001263b05 in gfx::Canvas::DrawImageInt (this=0x3d48fe558360, image=..., x=0, y=0, paint=...) at ../../ui/gfx/canvas.cc:339
#19 0x0000000001262c98 in gfx::Canvas::DrawImageInt (this=0x3d48fe0807e0, image=..., x=3, y=4) at ../../ui/gfx/canvas.cc:326
#20 0x0000000002b7e23c in libgtk2ui::Gtk2Border::PaintState (this=<optimized out>, state=<optimized out>, extra=..., rect=..., canvas=0x3d48fe558360) at ../../chrome/browser/ui/libgtk2ui/gtk2_border.cc:157
#21 0x0000000002b7e0a4 in libgtk2ui::Gtk2Border::Paint (this=0x3d48fe53c1b0, view=..., canvas=0x3d48fe558360) at ../../chrome/browser/ui/libgtk2ui/gtk2_border.cc:104
#22 0x0000000002b28489 in views::View::OnPaintBorder (this=0x3d48fe72b500, canvas=0x3d48fe558360) at ../../ui/views/view.cc:1381
#23 0x0000000002b280ed in views::View::OnPaint (this=0x3d48fe72b500, canvas=0x3d48fe558360) at ../../ui/views/view.cc:1364
#24 0x0000000002b02a5f in views::LabelButton::OnPaint (this=0x3d48fe72b500, canvas=0x3d48fe558360) at ../../ui/views/controls/button/label_button.cc:352
#25 0x0000000002b040ef in views::MenuButton::OnPaint (this=0x3d48fe72b500, canvas=0x3d48fe558360) at ../../ui/views/controls/button/menu_button.cc:138
#26 0x0000000002b2651a in views::View::PaintCommon (this=0x3d48fe72b500, canvas=0x3d48fe558360, cull_set=...) at ../../ui/views/view.cc:1766
#27 0x0000000002b25d75 in views::View::Paint (this=0x3d48fe72b500, canvas=0x3d48fe558360, cull_set=...) at ../../ui/views/view.cc:826
#28 0x0000000002b27f31 in views::View::PaintChildren (this=0x3d48fe517f00, canvas=0x3d48fe558360, cull_set=...) at ../../ui/views/view.cc:1358
#29 0x0000000002b26539 in views::View::PaintCommon (this=0x3d48fe517f00, canvas=0x3d48fe558360, cull_set=...) at ../../ui/views/view.cc:1769
#30 0x0000000002b25d75 in views::View::Paint (this=0x3d48fe517f00, canvas=0x3d48fe558360, cull_set=...) at ../../ui/views/view.cc:826
#31 0x0000000002b27f31 in views::View::PaintChildren (this=0x3d48fe03a310, canvas=0x3d48fe558360, cull_set=...) at ../../ui/views/view.cc:1358
#32 0x0000000002b26539 in views::View::PaintCommon (this=0x3d48fe03a310, canvas=0x3d48fe558360, cull_set=...) at ../../ui/views/view.cc:1769
#33 0x0000000002b25d75 in views::View::Paint (this=0x3d48fe03a310, canvas=0x3d48fe558360, cull_set=...) at ../../ui/views/view.cc:826
#34 0x0000000002b27f31 in views::View::PaintChildren (this=0x3d48fe37a800, canvas=0x3d48fe558360, cull_set=...) at ../../ui/views/view.cc:1358
#35 0x0000000002b26539 in views::View::PaintCommon (this=0x3d48fe37a800, canvas=0x3d48fe558360, cull_set=...) at ../../ui/views/view.cc:1769
#36 0x0000000002b25d75 in views::View::Paint (this=0x3d48fe37a800, canvas=0x3d48fe558360, cull_set=...) at ../../ui/views/view.cc:826
#37 0x0000000002b27f31 in views::View::PaintChildren (this=0x3d48fe37a000, canvas=0x3d48fe558360, cull_set=...) at ../../ui/views/view.cc:1358
#38 0x0000000002b26539 in views::View::PaintCommon (this=0x3d48fe37a000, canvas=0x3d48fe558360, cull_set=...) at ../../ui/views/view.cc:1769
#39 0x0000000002b25d75 in views::View::Paint (this=0x3d48fe37a000, canvas=0x3d48fe558360, cull_set=...) at ../../ui/views/view.cc:826
#40 0x0000000002b27f31 in views::View::PaintChildren (this=0x3d48fe199000, canvas=0x3d48fe558360, cull_set=...) at ../../ui/views/view.cc:1358
#41 0x0000000002b26539 in views::View::PaintCommon (this=0x3d48fe199000, canvas=0x3d48fe558360, cull_set=...) at ../../ui/views/view.cc:1769
#42 0x0000000002b2605f in views::View::Paint (this=0x3d48fe199000, canvas=0x3d48fe558360, cull_set=...) at ../../ui/views/view.cc:823
#43 0x0000000002b3020d in views::Widget::OnNativeWidgetPaint (this=<optimized out>, canvas=0x3d48fe558360) at ../../ui/views/widget/widget.cc:1167
#44 0x000000000130daf2 in Paint (this=0x3d48fe2da380, canvas=<optimized out>) at ../../ui/aura/window.cc:950
#45 aura::Window::OnPaintLayer (this=0x3d48fe2da380, canvas=0x3d48fe558360) at ../../ui/aura/window.cc:1356
#46 0x000000000131cc43 in ui::Layer::PaintContents (this=<optimized out>, sk_canvas=<optimized out>, clip=..., opaque=0x4, gc_status=(unknown: 4262027816)) at ../../ui/compositor/layer.cc:705
#47 0x000000000135567e in cc::ContentLayerUpdater::PaintContents (this=0x3d48fe6cbab0, canvas=0x3d48fe9e98c0, content_rect=..., contents_width_scale=1, contents_height_scale=1, 
    resulting_opaque_rect=0x7fffffffd8a0) at ../../cc/resources/content_layer_updater.cc:75
#48 0x0000000001354baf in cc::BitmapContentLayerUpdater::PrepareToUpdate (this=0x3d48fe6cbab0, content_rect=..., tile_size=..., contents_width_scale=<optimized out>, contents_height_scale=<optimized out>, 
    resulting_opaque_rect=0x7fffffffd8a0) at ../../cc/resources/bitmap_content_layer_updater.cc:78
---Type <return> to continue, or q <return> to quit---
#49 0x000000000134a7b3 in cc::TiledLayer::UpdateTileTextures (this=0x3d48fe217500, update_rect=..., paint_rect=..., left=<optimized out>, top=0, right=4, bottom=<optimized out>, queue=<optimized out>, 
    occlusion=<optimized out>) at ../../cc/layers/tiled_layer.cc:480
#50 0x000000000134a3ce in cc::TiledLayer::UpdateTiles (this=0x3d48fe217500, left=0, top=0, right=4, bottom=2, queue=0x3d48fe826f20, occlusion=<optimized out>, updated=<optimized out>)
    at ../../cc/layers/tiled_layer.cc:345
#51 0x000000000134b834 in cc::TiledLayer::Update (this=0x3d48fe217500, queue=0x3d48fe826f20, occlusion=0x7fffffffdb28) at ../../cc/layers/tiled_layer.cc:760
#52 0x000000000138ae3a in cc::LayerTreeHost::PaintLayerContents (this=0x3d48fe219000, render_surface_layer_list=..., queue=0x3d48fe826f20, did_paint_content=0x7fffffffdc57, need_more_updates=0x7fffffffdc56)
    at ../../cc/trees/layer_tree_host.cc:1018
#53 0x000000000138a5e7 in cc::LayerTreeHost::UpdateLayers (this=0x3d48fe219000, root_layer=<optimized out>, queue=0x3d48fe826f20) at ../../cc/trees/layer_tree_host.cc:853
#54 0x000000000138a170 in cc::LayerTreeHost::UpdateLayers (this=0x3d48fe219000, queue=0x3d48fe0807e0) at ../../cc/trees/layer_tree_host.cc:720
#55 0x00000000013afbd7 in cc::SingleThreadProxy::CompositeImmediately (this=0x3d48fe2c5aa0, frame_begin_time=...) at ../../cc/trees/single_thread_proxy.cc:350
#56 0x00000000013163a0 in ui::Compositor::Draw (this=0x3d48fe234240) at ../../ui/compositor/compositor.cc:230
#57 0x0000000000724593 in Run (this=<optimized out>) at ../../base/callback.h:401
#58 base::debug::TaskAnnotator::RunTask (this=<optimized out>, queue_function=<optimized out>, run_function=<optimized out>, pending_task=...) at ../../base/debug/task_annotator.cc:62
#59 0x00000000006e65e2 in base::MessageLoop::RunTask (this=0x3d48fdffd300, pending_task=...) at ../../base/message_loop/message_loop.cc:456
#60 0x00000000006e6c8c in DeferOrRunPendingTask (this=<optimized out>, pending_task=...) at ../../base/message_loop/message_loop.cc:466
#61 base::MessageLoop::DoWork (this=0x3d48fdffd300) at ../../base/message_loop/message_loop.cc:575
#62 0x00000000007197d9 in base::MessagePumpGlib::Run (this=0x3d48fe1ff880, delegate=<optimized out>) at ../../base/message_loop/message_pump_glib.cc:313
#63 0x00000000006f41e1 in base::RunLoop::Run (this=0x7fffffffe3b8) at ../../base/run_loop.cc:49
#64 0x00000000028263af in content::BrowserMainLoop::MainMessageLoopRun (this=<optimized out>) at ../../content/browser/browser_main_loop.cc:1153
#65 0x0000000002826320 in content::BrowserMainLoop::RunMainMessageLoopParts (this=0x3d48fdffdd80) at ../../content/browser/browser_main_loop.cc:754
#66 0x000000000269843d in content::BrowserMainRunnerImpl::Run (this=0x3d48fdfc7b60) at ../../content/browser/browser_main_runner.cc:205
#67 0x00000000006690e0 in ShellBrowserMain (parameters=...) at ../../content/nw/src/shell_browser_main.cc:45
Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
#68 0x0000000002ab3cd8 in content::RunNamedProcessTypeMain (process_type=, main_function_params=..., delegate=0x7fffffffe530) at ../../content/app/content_main_runner.cc:402
#69 0x0000000002ab4595 in content::ContentMainRunnerImpl::Run (this=0x3d48fdfc32d0) at ../../content/app/content_main_runner.cc:764
#70 0x0000000002ab3290 in content::ContentMain (params=...) at ../../content/app/content_main.cc:19
#71 0x0000000000663ee8 in main (argc=2, argv=0x7fffffffe668) at ../../content/nw/src/shell_main.cc:69
```
