### ISSUE TITLE
Current Working Directory

### ISSUE THREAD

**Issue by LengVang** [nwjs/nw.js#2836]
I believe the CWD should be set to whatever set in the package.son "main" path.  Many sites running under node-webkit should be running transparent with nodejs.  As it is, the CWD is set at where NW is running from which is false assumption and breaks nodejs's assumption of virtual path.
##

**Comment by ghostoy** [comment]
The current working directory is set to the root directory of your app (a.k.a. directory of `package.json`). The default behavior was implemented for a long time. Changing the default CWD may break existing apps. We need more investigation on this issue.

**Comment by ggarek** [comment]
I stumbled upon this issue too, and want to make some clarifications. @LengVang described exactly it, but very succinctly. I would like to add an illustrative example. (I also want to thanks @ghostoy for explanation in #5582)

Assuming this project structure
```
% tree                                                                                                                                                          
.
├── a
│   └── index.js
├── b
│   ├── c
│   │   └── index.js
│   └── index.js
├── index.js
└── package.json

3 directories, 5 files
```

And files content
```
% cat index.js                                                                                                                                                  
require('./a');%                                                                                                                                                                   
% cat a/index.js                                                                                                                                                
require('../b');%                                                                                                                                                                  
% cat b/index.js                                                                                                                                                
require('./c');%
% cat package.json                                                                                                                                              
{
  "name": "seems there is a bug",
  "version": "1.0.0",
  "main": "a/index.js"
}%
```

It the `a/index.js` is set as main script, then NW.js will fail, because the `CWD` is set to the project's root folder and `require(‘../b’)` could not be resolved, whereas seemingly wrong `require(‘./b’)` will work.

```
% ~/lib/nwjs/nwjs-v0.20.0-beta1-osx-x64/nwjs.app/Contents/MacOS/nwjs ./                                                                                         
module.js:496
    throw err;
    ^

Error: Cannot find module '../b'
    at Function.Module._resolveFilename (module.js:494:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:522:17)
    at require (internal/module.js:20:19)
    at self.require (<anonymous>:11:26)
    at chrome-extension://fpjcfnpnjglkdjffmcicogkmigoolpmc/a/index.js:1:1
```

The right way to fix it would be to set `CWD` in NW.js to wherever main script resides.

But there is a workaround to mitigate this issue for now. One way would be to change `require` statements in your main script during build process, but it is not a good solution. **Better workaround would be to add a simple “main script proxy” file which will `require` the real main script and which resides in project`s root folder.** *(Another way to address this issue would be to bundle your main script with tools like webpack)*

To demonstrate the workaround works let's change main script to be `index.js`, which just `require`s the real main script:

```
% cat package.json                                                                                                                                              
{
  "name": "seems there is a bug",
  "version": "1.0.0",
  "main": "index.js"
}
```


-----
The issue is not critical, but it would be awesome to have it resolved because it introduces unexpected behaviour. And because workarounds are not solutions )
And it seems not complicated issue to address.
