### ISSUE TITLE
Error: Cannot find module 'address_bar'

### ISSUE THREAD

**Issue by liudonghua123** [nwjs/nw.js#2964]
When I run "nw-sample-apps\file-explorer" on node-webkit-v0.11.1-win-x64, it give me the following error message!

Uncaught node.js Error 

Error: Cannot find module 'address_bar'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:273:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at window.require (<anonymous>:4:17)
    at file:///E:/code/nodejs/nw-sample-apps/file-explorer/main.js:3:12

Any ideas would be appreciate!

**Comment by liudonghua123** [comment]
This problem only occured on my old "node-webkit-v0.11.1-win-x64", I tried  the latest "node-webkit-v0.11.5-win-x64" and it works without problem.

Please close this issue!
