### ISSUE TITLE
0.11.6 release notes say it uses node v0.11.13 but actually it is v0.11.13pre

### ISSUE THREAD

**Issue by xdenser** [nwjs/nw.js#2994]
It is not the same. There is difference.
For instance 

``` javascript
 var s = dgram.createSocket{ type: 'udp4', reuseAddr: true });
```

works in Node v0.11.13, but not in NW 0.11.6 (based on v0.11.13pre actually)
I just realized that versions 0.9.2 - 0.11.x are not usable with my project by this reason.

That works in 0.12.0 though. It has other issues, so not usable yet too.
##

**Comment by ghostoy** [comment]
Could you provide a full test case to show the issue?

**Comment by layjump** [comment]
I am using nw.js 0.11.6 and console.log(process.versions) show messages:
[30359:0309/100448:INFO:CONSOLE(12)] "{"http_parser":"2.2","node":"0.11.13-pre","v8":"3.28.71.2","uv":"0.11.22","zlib":"1.2.5","modules":"14","openssl":"1.0.1f","node-webkit":"0.11.6","nw-commit-id":"ec3b4f4-d8ecacd-e5d35ef-f2f89e2-d9a9d39-cdd879e","chromium":"38.0.2125.104"}", source: file:///home/ubuntu/project/greenlord/html/index.html (12)

**Comment by layjump** [comment]
It can't be built with nw-gyp (--target=0.11.6) for those module using nan(version=1.7.0). Take pcap as an example:
```
$> nw-gyp rebuild --target=0.11.6
gyp info it worked if it ends with ok
gyp info using nw-gyp@0.12.4
gyp info using node@0.10.31 | linux | x64
gyp info spawn python
gyp info spawn args [ '/usr/local/lib/node_modules/nw-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ubuntu/project/backend/node_modules/pcap/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/nw-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ubuntu/.nw-gyp/0.11.6/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/ubuntu/.nw-gyp/0.11.6',
gyp info spawn args   '-Dmodule_root_dir=/home/ubuntu/project/backend/node_modules/pcap',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/home/ubuntu/project/backend/node_modules/pcap/build'
  CXX(target) Release/obj.target/pcap_binding/pcap_binding.o
In file included from ../pcap_session.h:4:0,
                 from ../pcap_binding.cc:12:
../node_modules/nan/nan.h: In function ‘void NanSetCounterFunction(v8::CounterLookupCallback)’:
../node_modules/nan/nan.h:207:5: error: ‘SetCounterFunction’ is not a member of ‘v8::V8’
     v8::V8::SetCounterFunction(cb);
     ^
../node_modules/nan/nan.h: In function ‘void NanSetCreateHistogramFunction(v8::CreateHistogramCallback)’:
../node_modules/nan/nan.h:212:5: error: ‘SetCreateHistogramFunction’ is not a member of ‘v8::V8’
     v8::V8::SetCreateHistogramFunction(cb);
     ^
../node_modules/nan/nan.h: In function ‘void NanSetAddHistogramSampleFunction(v8::AddHistogramSampleCallback)’:
../node_modules/nan/nan.h:217:5: error: ‘SetAddHistogramSampleFunction’ is not a member of ‘v8::V8’
     v8::V8::SetAddHistogramSampleFunction(cb);
     ^
../node_modules/nan/nan.h: In function ‘bool NanIdleNotification(int)’:
../node_modules/nan/nan.h:221:12: error: ‘IdleNotification’ is not a member of ‘v8::V8’
     return v8::V8::IdleNotification(idle_time_in_ms);
            ^
../node_modules/nan/nan.h: In function ‘void NanLowMemoryNotification()’:
../node_modules/nan/nan.h:225:5: error: ‘LowMemoryNotification’ is not a member of ‘v8::V8’
     v8::V8::LowMemoryNotification();
     ^
../node_modules/nan/nan.h: In function ‘void NanContextDisposedNotification()’:
../node_modules/nan/nan.h:229:5: error: ‘ContextDisposedNotification’ is not a member of ‘v8::V8’
     v8::V8::ContextDisposedNotification();
     ^
make: *** [Release/obj.target/pcap_binding/pcap_binding.o] Error 1
make: Leaving directory `/home/ubuntu/project/backend/node_modules/pcap/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/nw-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 3.16.0-031600-generic
gyp ERR! command "node" "/usr/local/bin/nw-gyp" "rebuild" "--target=0.11.6"
gyp ERR! cwd /home/ubuntu/project/backend/node_modules/pcap
gyp ERR! node -v v0.10.31
gyp ERR! nw-gyp -v v0.12.4
gyp ERR! not ok 
```
And at the same time it can be built with node-gyp (--target=0.11.13).
```
$> node-gyp rebuild --target=0.11.13
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.2
gyp info using node@0.10.31 | linux | x64
gyp info spawn python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ubuntu/project/backend/node_modules/pcap/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ubuntu/.node-gyp/0.11.13/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/ubuntu/.node-gyp/0.11.13',
gyp info spawn args   '-Dmodule_root_dir=/home/ubuntu/project/backend/node_modules/pcap',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/home/ubuntu/project/backend/node_modules/pcap/build'
  CXX(target) Release/obj.target/pcap_binding/pcap_binding.o
  CXX(target) Release/obj.target/pcap_binding/pcap_session.o
  SOLINK_MODULE(target) Release/obj.target/pcap_binding.node
  SOLINK_MODULE(target) Release/obj.target/pcap_binding.node: Finished
  COPY Release/pcap_binding.node
make: Leaving directory `/home/ubuntu/project/backend/node_modules/pcap/build'
gyp info ok 
```
Look into nan's source file nan.h.
slice form nan.h
```
#if NODE_MODULE_VERSION >= IOJS_1_0_MODULE_VERSION \
|| NODE_VERSION_AT_LEAST(0, 11, 15)
NAN_INLINE
void NanSetCounterFunction(v8::CounterLookupCallback cb) {
v8::Isolate::GetCurrent()->SetCounterFunction(cb);
}
NAN_INLINE
void NanSetCreateHistogramFunction(v8::CreateHistogramCallback cb) {
v8::Isolate::GetCurrent()->SetCreateHistogramFunction(cb);
}
NAN_INLINE
void NanSetAddHistogramSampleFunction(v8::AddHistogramSampleCallback cb) {
v8::Isolate::GetCurrent()->SetAddHistogramSampleFunction(cb);
}
NAN_INLINE bool NanIdleNotification(int idle_time_in_ms) {
return v8::Isolate::GetCurrent()->IdleNotification(idle_time_in_ms);
}
NAN_INLINE void NanLowMemoryNotification() {
v8::Isolate::GetCurrent()->LowMemoryNotification();
}
NAN_INLINE void NanContextDisposedNotification() {
v8::Isolate::GetCurrent()->ContextDisposedNotification();
}
#else
NAN_INLINE
void NanSetCounterFunction(v8::CounterLookupCallback cb) {
v8::V8::SetCounterFunction(cb);
}
NAN_INLINE
void NanSetCreateHistogramFunction(v8::CreateHistogramCallback cb) {
v8::V8::SetCreateHistogramFunction(cb);
}
NAN_INLINE
void NanSetAddHistogramSampleFunction(v8::AddHistogramSampleCallback cb) {
v8::V8::SetAddHistogramSampleFunction(cb);
}
NAN_INLINE bool NanIdleNotification(int idle_time_in_ms) {
return v8::V8::IdleNotification(idle_time_in_ms);
}
NAN_INLINE void NanLowMemoryNotification() {
v8::V8::LowMemoryNotification();
}
NAN_INLINE void NanContextDisposedNotification() {
v8::V8::ContextDisposedNotification();
}
#endif
```
These is a macro #if NODE_MODULE_VERSION >= IOJS_1_0_MODULE_VERSION \
|| NODE_VERSION_AT_LEAST(0, 11, 15)
When change NODE_VERSION_AT_LEAST(0, 11, 15) to NODE_VERSION_AT_LEAST(0, 11, 13),
nw-gyp rebuild --target=0.11.6 work well , and nody-gyp rebuild --target=0.11.13 failed to rebuild.
So It seems nw 0.11.6 use node 0.11.13-pre and node 0.11.13-pre using the same V8 API as node 0.11.15.

**Comment by ghostoy** [comment]
There are two issues here:
1. dgram API is changed after 0.11.13-pre at the time of NW11 release. That caused your initial problem.
2. NW11 is using a relatively newer V8 than node.js 0.11.13. The official node.js 0.11.13 is based on [V8 3.24.35.22](https://github.com/joyent/node/blob/v0.11.13-release/ChangeLog). NW11 is based on [V8 3.28.71](https://github.com/nwjs/v8/blob/nw11/ChangeLog). That caused the later compilation problem.

@rogerwang, do you have any plan to upgrade Node.js part for NW11 release?
Another suggestion is to try with NW12 release. Now NW12 is officially released with some regression issue fixed, would you mind to check with this version?

**Comment by layjump** [comment]
@ghostoy Thanks for your reply. I've tried NW12 and there is no compilation problem any more.
