### ISSUE TITLE
Error: Module did not self-register. when i use gdal module in node-webkit

### ISSUE THREAD

**Issue by aiming0609** [nwjs/nw.js#3130]
Uncaught node.js Error 
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:354:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (C:\Users\aiming\AppData\Local\Temp\nw8736_14028\node_modules\gdal\lib\gdal.js:7:29)
    at Module._compile (module.js:454:26)
    at Object.Module._extensions..js (module.js:472:10)
    at Module.load (module.js:354:32)
    at Function.Module._load (module.js:310:12)
##

**Comment by iwege** [comment]
gdal.js is a native module, you need to look at this : https://github.com/nwjs/nw.js/wiki/Build-native-modules-with-nw-gyp

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build?

**Comment by Christywl** [comment]
close until there is more information.
