### ISSUE TITLE
Module version mismatch

### ISSUE THREAD

**Issue by ajay-gandhi** [nwjs/nw.js#3142]
I'm encountering the following error when using a headless browser with nw.js; I tried both [Zombie.js](https://github.com/assaf/zombie) and [Phantomjs](https://github.com/sgentle/phantomjs-node) and they returned the exact same error (excluding paths, etc.). Both work fine with the same code outside nw.js.

```
[5444:0227/104710:ERROR:nw_shell.cc(325)] Error: Module version mismatch. Expected 43, got 14.
    at Error (native)
    at Module.load (module.js:346:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:356:17)
    at require (module.js:375:17)
    at bindings (/path/to/project/node_modules/phantom/node_modules/dnode/node_modules/weak/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/path/to/project/node_modules/phantom/node_modules/dnode/node_modules/weak/lib/weak.js:7:35)
    at Module._compile (module.js:451:26)
    at Object.Module._extensions..js (module.js:469:10)
    at Module.load (module.js:346:32)
[5444:0227/104710:INFO:CONSOLE(83)] "Uncaught Error: Module version mismatch. Expected 43, got 14.", source: /path/to/project/node_modules/phantom/node_modules/dnode/node_modules/weak/node_modules/bindings/bindings.js (83)
```

Note: I'm using [this workaround](https://github.com/jaeh/node-webkit-express) to start a server while running my app.

**Comment by rogerwang** [comment]
You'll need to recompile the native module for nw with nw-gyp.
