### ISSUE TITLE
ERROR:nw_shell.cc(335)] Error: Module did not self-register.

### ISSUE THREAD

**Issue by Jayin** [nwjs/nw.js#3305]
CC:
![7bcf2850-c20c-42ee-a243-02e4723004c9](https://cloud.githubusercontent.com/assets/2763894/6863304/f4d31a74-d489-11e4-9294-819c6fcad503.jpg)

When I use [jieba](https://github.com/yanyiwu/nodejieba) ,require that library occurred this error.

```shell
[706:0328/092420:ERROR:nw_shell.cc(335)] Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:346:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:356:17)
    at require (module.js:375:17)
    at Object.<anonymous> (/Users/jayin/jayin/workplace/webstorm/Voice-Editor/node_modules/nodejieba/index.js:1:77)
    at Module._compile (module.js:451:26)
    at Object.Module._extensions..js (module.js:469:10)
    at Module.load (module.js:346:32)
    at Function.Module._load (module.js:301:12)
[706:0328/092420:INFO:CONSOLE(346)] "Uncaught Error: Module did not self-register.", source: module.js (346)
```

I open a issue(https://github.com/yanyiwu/nodejieba/issues/18) at jieba  but the author said it looks like a bug of nw.js

**Comment by Jayin** [comment]
Environment:

OS X 10.10.2
nw.js v0.12.0
jieba v0.2.9

**Comment by iwege** [comment]
Is the jieba a native module? 

Maybe you need to rebuild this module: https://github.com/nwjs/nw.js/wiki/Build-native-modules-with-nw-gyp

**Comment by Jayin** [comment]
yes. thx

**Comment by mpasmino** [comment]
hello, I have a problem with the file

C:/Users/Matias/AppData/Roaming/npm/node_modules/nw-gyp/lib/build.js:85:25

![error gyp](https://cloud.githubusercontent.com/assets/12187828/7416208/2ab8c0fc-ef34-11e4-9795-72f380022229.PNG)

I use Windows OS 8.1 x64

I have installed
Python 2.7.8
Visual studio 2013
node web kit 0.12.0

**Comment by sword36** [comment]
Run "nw-gyp configure"

**Comment by sword36** [comment]
Run "node-pre-gyp configure"
