### ISSUE TITLE
Running without the SUID sandbox

### ISSUE THREAD

**Issue by ajsb85** [nwjs/nw.js#3398]
### nwjs-v0.12.1-linux-x64

``` sh
[4482:0423/052926:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[4499:0423/052927:WARNING:x11_util.cc(1490)] X error received: serial 66, error_code 8 (BadMatch (invalid parameter attributes)), request_code 72, minor_code 0 (X_PutImage)
[4521:0423/053012:WARNING:channel.cc(553)] Failed to send message to remove remote endpoint (local ID 2147483649, remote ID 3)
[4521:0423/053012:WARNING:channel.cc(553)] Failed to send message to ack remove remote endpoint (local ID 1, remote ID 1)
```
##

**Comment by blusewang** [comment]
I try to add `"chromium-args": "--disable-setuid-sandbox",` to package.json file. but it's now working!

**Comment by Christywl** [comment]
It doesn't reproduce for me. Please try the latest build.

**Comment by jcubic** [comment]
I have the same problem when I've builded and installed [gitter](https://gitlab.com/gitlab-org/gitter/desktop) on fedora. I've added `"chromium-args": "--disable-setuid-sandbox"` to package.json but that didn't work, the gitter is using `gulp` to build and create deb and rpm pages.

**Comment by Christywl** [comment]
@jcubic , could you please try your test with the latest nwjs build?

**Comment by jcubic** [comment]
I've used version 0.25.4 and have the same issue.

**Comment by Christywl** [comment]
@jcubic , I try to reproduce this on Mac, but fail to build gitter, my steps are:
1. `brew cask install java xquartz` then `brew install wine`
2. `brew install gnu-tar` then `sudo gem install fpm`
3. `git clone https://gitlab.com/gitlab-org/gitter/desktop`
4. cd desktop, and modify package.json nw and nw-builder version:
`nwversion": "0.26.6",`
`"nw-builder": "^3.4.0",`
`"nw": "^0.26.6",`
5. `npm install`
6. `gulp build:linux` --> Fail
Error:
```
$ gulp build:linux
win
osx
linux32
linux64
[13:16:18] Using gulpfile ~/test/3398/desktop/gulpfile.js
[13:16:18] Starting 'clean:opt'...
[13:16:18] Starting 'clean:artefacts'...
[13:16:18] Starting 'check-path-safety-for-windows'...
[13:16:18] Finished 'clean:opt' after 18 ms
[13:16:18] Finished 'clean:artefacts' after 15 ms
[13:16:19] Finished 'check-path-safety-for-windows' after 999 ms
[13:16:19] Starting 'build'...
[13:16:20] 'build' errored after 292 ms
[13:16:20] TypeError: builder.build(...).nodeify is not a function
    at Gulp.<anonymous> (/Users/wanming/test/3398/desktop/gulpfile.js:168:19)
    at module.exports (/Users/wanming/test/3398/desktop/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/wanming/test/3398/desktop/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/wanming/test/3398/desktop/node_modules/orchestrator/index.js:214:10)
    at /Users/wanming/test/3398/desktop/node_modules/orchestrator/index.js:279:18
    at finish (/Users/wanming/test/3398/desktop/node_modules/orchestrator/lib/runTask.js:21:8)
    at /Users/wanming/test/3398/desktop/node_modules/orchestrator/lib/runTask.js:52:4
    at f (/Users/wanming/test/3398/desktop/node_modules/once/once.js:17:25)
    at DestroyableTransform.onend (/Users/wanming/test/3398/desktop/node_modules/end-of-stream/index.js:31:18)
    at emitNone (events.js:111:20)
    at DestroyableTransform.emit (events.js:208:7)
    at endReadableNT (/Users/wanming/test/3398/desktop/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:992:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
[13:16:21] nw-builder: Using v0.26.6 (sdk)
[13:16:21] nw-builder: Create cache folder in /Users/wanming/test/3398/desktop/cache/0.26.6-sdk
[13:16:21] nw-builder: Downloading: https://dl.nwjs.io/v0.26.6/nwjs-sdk-v0.26.6-win-ia32.zip
[13:16:21] nw-builder: Create cache folder in /Users/wanming/test/3398/desktop/cache/0.26.6-sdk
[13:16:21] nw-builder: Downloading: https://dl.nwjs.io/v0.26.6/nwjs-sdk-v0.26.6-osx-x64.zip
[13:16:21] nw-builder: Create cache folder in /Users/wanming/test/3398/desktop/cache/0.26.6-sdk
```
Anything wrong in my steps?

**Comment by jcubic** [comment]
Sorry don't remember what I've did when I've build on Fedora and I don't have that distro anymore because my laptop that have it installed broke.

**Comment by Christywl** [comment]
close until there is more information
