### ISSUE TITLE
process.stdout woes on Windows

### ISSUE THREAD

**Issue by mgutz** [nwjs/nw.js#343]
I made comment on this on a closed ticket. Created this one so it would not slip by.

Many libraries use `process.stdout` instead of `console`. Running this simple statement results in errors on Windows.

    process.stdout.write('"foo");

On Windows, `Uncaught Error: Implement me. Unknown stream file type!   node.js:277`

**Comment by aleclarson** [comment]
`process.stdout` doesn't seem to exist on Mac

Any help with this?

**Comment by gordonpro** [comment]
@aleclarson 
```
[15959:0618/110837:ERROR:nw_shell.cc(335)] TypeError: object is not a function
    at resume_ (_stream_readable.js:709:12)
    at _stream_readable.js:701:7
    at process._tickCallback (node.js:375:11)
[15959:0618/110837:INFO:CONSOLE(709)] "Uncaught TypeError: object is not a function", source: _stream_readable.js (709)
```

I also use Mac, the process.stdout.on("data", function(data){})  throw a Error
