### ISSUE TITLE
`SELF_SIGNED_CERT_IN_CHAIN` error for nw 0.8.6 on https

### ISSUE THREAD

**Issue by taktran** [nwjs/nw.js#3450]
When running node webkit 0.8.6 and using the `request` library to access https sites, I get this error:

```
Error: SELF_SIGNED_CERT_IN_CHAIN
  at SecurePair.eval (tls.js:1362:32)
  at SecurePair.EventEmitter.emit (events.js:92:17)
  at SecurePair.maybeInitFinished (tls.js:974:10)
  at CleartextStream.read [as _read] (tls.js:462:15)
  at CleartextStream.Readable.read (_stream_readable.js:320:10)
  at EncryptedStream.write [as _write] (tls.js:366:25)
  at doWrite (_stream_writable.js:221:10)
  at writeOrBuffer (_stream_writable.js:211:5)
  at EncryptedStream.Writable.write (_stream_writable.js:180:11)
  at write (_stream_readable.js:583:24)
```

I found [this about the problem](http://blog.npmjs.org/post/78085451721/npms-self-signed-certificate-is-no-more), and it seems to be an npm problem. Is there a way to upgrade nw's npm?

My system npm is upgraded, but nw seems to have its own.

I want to upgrade to nw.js 0.12.1, but we have some problems with iojs, and support for windows (with non-nw related libraries).
##

**Comment by Christywl** [comment]
Is this issue still reproduced? If it's a nwjs issue, please provide a sample to reproduce it. If not, please close this issue.

**Comment by Christywl** [comment]
close until there is more information.
