### ISSUE TITLE
Unable to maximize from protractor

### ISSUE THREAD

**Issue by Dineshs91** [nwjs/nw.js#3999]
I want to maximize the nw window, before the e2e test cases run. To achieve this I added this ```browser.driver.manage().window().maximize()``` to onPrepare in protractor-conf.js. 

But I am getting the following error

```
protractor test/protractor-conf.js
Using ChromeDriver directly...
[launcher] Running 1 instances of WebDriver
/home/travis/build/Dineshs91/devlog/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:113
  var template = new Error(this.message);
                 ^
UnknownError: unknown error: cannot get automation extension
from unknown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html
  (Session info: content shell=)
  (Driver info: chromedriver=2.13 (072d56ad45f528d86ca62d8709be879fd2e7644c),platform=Linux 3.13.0-40-generic x86_64)
    at new bot.Error (/home/travis/build/Dineshs91/devlog/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:113:18)
    at Object.bot.response.checkResponse (/home/travis/build/Dineshs91/devlog/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/response.js:106:9)
    at /home/travis/build/Dineshs91/devlog/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:362:20
    at /home/travis/build/Dineshs91/devlog/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1582:15
    at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (/home/travis/build/Dineshs91/devlog/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
    at notify (/home/travis/build/Dineshs91/devlog/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:465:12)
    at notifyAll (/home/travis/build/Dineshs91/devlog/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:442:7)
    at resolve (/home/travis/build/Dineshs91/devlog/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:420:7)
    at [object Object].fulfill (/home/travis/build/Dineshs91/devlog/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:535:5)
    at /home/travis/build/Dineshs91/devlog/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1520:10
==== async task ====
WebDriver.manage().window().setSize(1600, 1000)
    at [object Object].webdriver.WebDriver.schedule (/home/travis/build/Dineshs91/devlog/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:345:15)
    at [object Object].webdriver.WebDriver.Window.setSize (/home/travis/build/Dineshs91/devlog/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:1393:23)
    at exports.config.onPrepare (/home/travis/build/Dineshs91/devlog/test/protractor-conf.js:33:35)
    at /home/travis/build/Dineshs91/devlog/node_modules/protractor/lib/util.js:54:41
    at Function.promise (/home/travis/build/Dineshs91/devlog/node_modules/protractor/node_modules/q/q.js:650:9)
    at Object.exports.runFilenameOrFn_ (/home/travis/build/Dineshs91/devlog/node_modules/protractor/lib/util.js:44:12)
    at [object Object].Runner.runTestPreparer (/home/travis/build/Dineshs91/devlog/node_modules/protractor/lib/runner.js:76:17)
    at Object.exports.run (/home/travis/build/Dineshs91/devlog/node_modules/protractor/lib/frameworks/jasmine.js:62:17)
    at /home/travis/build/Dineshs91/devlog/node_modules/protractor/lib/runner.js:326:35
[launcher] Process exited with error code 1
```

protractor-conf.js

```
'use strict';

var path = require('path');
var nw = require('nw');

exports.config = {
    chromeDriver: './support/chromedriver',
    directConnect: true,
    specs: ['e2e/**/*.js'],
    rootElement: 'html',
    capabilities: {
        browserName: 'chrome',
        chromeOptions: {
            binary: nw.findpath()
        }
    },

    onPrepare: function() {
        browser.driver.manage().window().maximize();
        browser.resetUrl = 'file://';
        browser.driver.get('file://' + path.resolve('app/index.html'));
    }
};
```

**Comment by kumarvishalvishnoi** [comment]
Facing the same issue.
