### ISSUE TITLE
nw-gyp all build steps not clear.

### ISSUE THREAD

**Issue by hartsantler** [nwjs/nw.js#4009]
All the steps to build a c++ module using nw-gyp should be outlined on the wiki here:
https://github.com/nwjs/nw.js/wiki/Build-native-modules-with-nw-gyp

The wikipage says for more info to go to: https://github.com/nwjs/nw-gyp
but all the steps required to build a hello world are not listed there either.

Here is what I understand so far from the documentation:
```bash
 npm install -g nw-gyp
$ cd myaddon
$ nw-gyp configure --target=<nw.js version number>
$ nw-gyp build
```

The github frontpage it links to this helloworld:
https://github.com/nodejs/node-v0.x-archive/tree/master/test/addons/hello-world

This is the contents of the example `binding.cc`
```c++
#include <node.h>
#include <v8.h>
using namespace v8;
void Method(const FunctionCallbackInfo<Value>& args) {
  Isolate* isolate = Isolate::GetCurrent();
  HandleScope scope(isolate);
  args.GetReturnValue().Set(String::NewFromUtf8(isolate, "world"));
}
void init(Handle<Object> target) {
  NODE_SET_METHOD(target, "hello", Method);
}
NODE_MODULE(binding, init);
```

The example requires `node.h` and `v8.h`.  The steps that are not clear to me is how to install those.  Do I need to do a full source code checkout of NW.js, Chromium, and Node.js?  And rebuild them all from source?

It would be nice to have some links where to download, and how to build Chromium and Node.js if that is required.

**Comment by spirodonfl** [comment]
node.h and v8.h come from install node-gyp if I'm not mistaken (someone can correct me). I've been fiddling around with this myself lately.

**Comment by hubbly** [comment]
C:\Users\lisq\node_modules>nw-gyp configure --target=0.18.2
gyp info it worked if it ends with ok
gyp info using nw-gyp@3.4.0
gyp info using node@7.0.0 | win32 | x64
gyp http GET http://node-webkit.s3.amazonaws.com/v0.18.2/nw-headers-v0.18.2.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:1026:11)
gyp ERR! stack     at TCP.onread (net.js:572:26)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\lisq\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\bin\\nw-gyp.js" "configure" "--target=0.18.2"
gyp ERR! cwd C:\Users\lisq\node_modules
gyp ERR! node -v v7.0.0
gyp ERR! nw-gyp -v v3.4.0
gyp ERR! not ok

**Comment by hubbly** [comment]
can not access amazonaws.com In china

**Comment by ghostoy** [comment]
@hubbly You can try to pass `--disturl=https://dl.nwjs.io` to nw-gyp.
