### ISSUE TITLE
chromedriver failed to get windows position and size

### ISSUE THREAD

**Issue by ghostoy** [nwjs/nw.js#4250]
When calling `driver.get_window_position()`, I got following error:

```none
Traceback (most recent call last):
  File "test.py", line 40, in <module>
    print driver.get_window_position()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 846, in get_window_position
    {'windowHandle': windowHandle})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 181, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: No current window
JavaScript stack:
Error: No current window
    at checkForExtensionError (chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/background.js:14:17)
    at Object.callback (chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/background.js:52:5)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:79:7)
  (Session info: chrome=48.0.2564.66)
  (Driver info: chromedriver=2.20 (f78bfbe2ce0143a245540aed91630a10e50d0e7d),platform=Linux 3.16.0-57-generic x86_64)
```

Same error for `driver.get_window_size()`.

Tested on 0.13.0-beta4 and 0.12.3.

**Comment by rogerwang** [comment]
Could you use in-chromium-tree webdriver and try again? At least stop using pip installed webdriver when you do case development.

**Comment by ghostoy** [comment]
Same error:

```none
Traceback (most recent call last):
  File "test.py", line 40, in <module>
    print driver.get_window_position()
  File "/home/user/Workspace/nw13/src/third_party/webdriver/pylib/selenium/webdriver/remote/webdriver.py", line 769, in get_window_position
    {'windowHandle': windowHandle})['value']
  File "/home/user/Workspace/nw13/src/third_party/webdriver/pylib/selenium/webdriver/remote/webdriver.py", line 157, in execute
    self.error_handler.check_response(response)
  File "/home/user/Workspace/nw13/src/third_party/webdriver/pylib/selenium/webdriver/remote/errorhandler.py", line 149, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: u'unknown error: No current window\nJavaScript stack:\nError: No current window\n    at checkForExtensionError (chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/background.js:14:17)\n    at Object.callback (chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/background.js:52:5)\n    at safeCallbackApply (extensions::sendRequest:21:15)\n    at handleResponse (extensions::sendRequest:79:7)\n  (Session info: chrome=48.0.2564.66)\n  (Driver info: chromedriver=2.20 (f78bfbe2ce0143a245540aed91630a10e50d0e7d),platform=Linux 3.16.0-57-generic x86_64)'
```

**Comment by rogerwang** [comment]
full sample?

**Comment by ghostoy** [comment]
Put this fill within the same folder as the app.

_test.py_
```python
import time
import os

from selenium import webdriver
from selenium.webdriver.chrome.options import Options

chrome_options = Options()
chrome_options.add_argument("nwapp=" + os.path.dirname(os.path.abspath(__file__)))

driver = webdriver.Chrome(executable_path=os.environ['CHROMEDRIVER'], chrome_options=chrome_options)
time.sleep(1)
try:
    print driver.get_window_position()
    print driver.get_window_size()
finally:
    driver.quit()
```

**Comment by ghostoy** [comment]
@rogerwang This issue is not NW13 specific. It also fails on previous 0.12.3.

**Comment by RebOOter** [comment]
Hello guys! Would you fix this bug? I can't resize window too while executing tests with Codeception.
