### ISSUE TITLE
cannot debug event listeners

### ISSUE THREAD

**Issue by freddyb** [nwjs/nw.js#4253]
When selecting the event listeners tab in the devtools:

```[0115/205842:INFO:nw_package.cc(175)] ./nw ../Signal-Desktop/dist/
[7510:7510:0115/210020:ERROR:CONSOLE(1405)] "TypeError: Cannot read property 'contentURL' of null TypeError: Cannot read property 'contentURL' of null
    at Object.WebInspector.EventListener (chrome-devtools://devtools/bundled/inspector.js:5984:213)
    at Object.createEventListener (chrome-devtools://devtools/bundled/inspector.js:6164:9)
    at Array.map (native)
    at Object.mycallback (chrome-devtools://devtools/bundled/inspector.js:6158:18)
    at Object.InspectorBackendClass.AgentPrototype.dispatchResponse (chrome-devtools://devtools/bundled/inspector.js:3979:10)
    at Object.InspectorBackendClass.Connection.dispatch (chrome-devtools://devtools/bundled/inspector.js:3899:60)
    at Object.InspectorBackendClass.MainConnection._dispatchMessage (chrome-devtools://devtools/bundled/inspector.js:3924:7)
    at Object.WebInspector.Object.dispatchEventToListeners (chrome-devtools://devtools/bundled/inspector.js:752:185)
    at innerDispatch (chrome-devtools://devtools/bundled/inspector.js:1405:58)
    at Object.InspectorFrontendAPIImpl._dispatch (chrome-devtools://devtools/bundled/inspector.js:1404:1)", source: chrome-devtools://devtools/bundled/inspector.js (1405)

```

```

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample and steps to reproduce it?

**Comment by freddyb** [comment]
I stopped using nwjs. Feel free to close this issue.

Am 4. Mai 2017 07:20:21 MESZ schrieb Christywl <notifications@github.com>:
