### ISSUE TITLE
404 status code downloading tarball

### ISSUE THREAD

**Issue by caibirdme** [nwjs/nw.js#4263]
when I exec `nw-gyp configure --target=0.13.0` it responses 404 err info
```
gyp info it worked if it ends with ok
gyp info using nw-gyp@0.13.0
gyp info using node@4.2.4 | darwin | x64
gyp http GET http://node-webkit.s3.amazonaws.com/v0.13.0/nw-headers-v0.13.0.tar.gz
gyp http 404 http://node-webkit.s3.amazonaws.com/v0.13.0/nw-headers-v0.13.0.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/nw-gyp/lib/install.js:236:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/nw-gyp/node_modules/request/request.js:951:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:415:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:305:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/nw-gyp" "configure" "--target=0.13.0"
gyp ERR! cwd /Users/deenjun/workspace/learnnw/node_modules/hello
gyp ERR! node -v v4.2.4
gyp ERR! nw-gyp -v v0.13.0
gyp ERR! not ok
```
then I `wget http://node-webkit.s3.amazonaws.com/v0.13.0/nw-headers-v0.13.0.tar.gz` but still responses
```
wget http://node-webkit.s3.amazonaws.com/v0.13.0/nw-headers-v0.13.0.tar.gz
--2016-01-18 14:18:59--  http://node-webkit.s3.amazonaws.com/v0.13.0/nw-headers-v0.13.0.tar.gz
Resolving node-webkit.s3.amazonaws.com... 54.231.9.249
Connecting to node-webkit.s3.amazonaws.com|54.231.9.249|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-01-18 14:19:00 ERROR 404: Not Found.
```
So I guess the resource might be deleted right?How can I deal with it

**Comment by rogerwang** [comment]
should use the full version string like 0.13.0-beta3
