### ISSUE TITLE
Error: listen EADDRINUSE but process run correctly

### ISSUE THREAD

**Issue by codekraft-studio** [nwjs/nw.js#4436]
I don't know if is useful, I just tried out the example in: [https://github.com/nwjs/nw.js/wiki/NW.js-use-express-and-similar-web-frameworks](url)
With a custom basic express file: 
```javascript
var express = require('express');
var app = express();

app.get('/', function (req, res) {
  res.send('Hello World!');
});

app.listen(8080, function () {
  console.log('Example app listening on port 8080!');
});
```

and a basic package.json file:
```javascript
{
  "name": "nw-demo",
  "version": "0.0.1",
  "node-main": "./main.js",
  "main": "http://localhost:8080",
  "dependencies": {
    "express": "^4.13.4"
  }
}

```

The process starts successfully but I get this error message at start and every time I reload:

```bash
[3206:0222/204547:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
ATTENTION: default value of option force_s3tc_enable overridden by environment.
events.js:125
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:734:11)
    at exports._exceptionWithHostPort (util.js:757:20)
    at Server._listen2 (net.js:1153:14)
    at listen (net.js:1179:10)
    at Server.listen (net.js:1266:5)
    at EventEmitter.listen (/home/commonuser/Desktop/workspace/node/myApp/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/home/commonuser/Desktop/workspace/node/myApp/main.js:8:5)
    at Module._compile (module.js:451:26)
    at Object.Module._extensions..js (module.js:469:10)
    at Module.load (module.js:346:32)
[3206:0222/204547:ERROR:channel.cc(305)] RawChannel read error (connection broken)
```

**Comment by sw360cab** [comment]
+1 
I encounter the same issue. Looks like program works as well

**Comment by codekraft-studio** [comment]
with the last version __v0.14.4__ It happens more rarely or almost never
