### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by RobertLowe** [nwjs/nw.js#459]
Hey,

The build instructions are unclear, should `node-webkit` (this repo) be the root, or is it chromium. Should it be nested inside the chromium source under `content/nw`?

> First find a place to put our code, it will take up about 14G disk space after compilation. Assume you store code under node-webkit folder, our final directory architecture will be like:

```
node-webkit/
|-- .gclient
`-- src/
    |-- many-stuff
    |-- ...
    `-- content
        |-- ...
        `-- nw
```

I wanted to take a stab at fixing #348

Specifically I was getting an error like:

```
Error: 
____ src at node
    Path is not a git repo. No .git dir.
    To resolve:
        rm -rf src
    And run gclient sync again
```

**Comment by vishalup** [comment]
Not able get code itself. Getting following error on windows.

```D:\Workspace\NW12>fetch --no-history chromium --nosvn=True
Running: 'D:\Workspace\depot_tools\python276_bin\python.exe' 'D:\Workspace\depot_tools\gclient.py' root
Running: 'D:\Workspace\depot_tools\python276_bin\python.exe' 'D:\Workspace\depot_tools\gclient.py' config --sp
ec 'solutions = [
  {
    "managed": False,
    "name": "src",
    "url": "https://chromium.googlesource.com/chromium/src.git",
    "custom_deps": {},
    "deps_file": ".DEPS.git",
    "safesync_url": "",
  },
]
'
Running: 'D:\Workspace\depot_tools\python276_bin\python.exe' 'D:\Workspace\depot_tools\gclient.py' sync --no-h
istory
Error: Command 'D:\\Workspace\\depot_tools\\python276_bin\\python.exe src/build/landmines.py' returned non-zer
o exit status 1 in D:\Workspace\NW12
Traceback (most recent call last):
  File "D:\Workspace\depot_tools\\fetch.py", line 346, in <module>
    sys.exit(main())
  File "D:\Workspace\depot_tools\\fetch.py", line 341, in main
    return run(options, spec, root)
  File "D:\Workspace\depot_tools\\fetch.py", line 335, in run
    return checkout.init()
  File "D:\Workspace\depot_tools\\fetch.py", line 142, in init
    self.run_gclient(*sync_cmd)
  File "D:\Workspace\depot_tools\\fetch.py", line 76, in run_gclient
    return self.run(cmd_prefix + cmd, **kwargs)
  File "D:\Workspace\depot_tools\\fetch.py", line 66, in run
    return subprocess.check_output(cmd, **kwargs)
  File "D:\Workspace\depot_tools\python276_bin\lib\subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '('D:\\Workspace\\depot_tools\\python276_bin\\python.exe', 'D:\\Workspa
ce\\depot_tools\\gclient.py', 'sync', '--no-history')' returned non-zero exit status 2```

I have tried to fetch without ```--nosvn=True```.

Solution is as follow:
```solutions = [
   { "name"        : "src",
     "url"         : "https://github.com/zcbenz/chromium.git@origin/node",
     "deps_file"   : ".DEPS.git",
     "managed"     : True,
     "custom_deps" : {
       "src/third_party/WebKit/LayoutTests": None,
       "src/chrome_frame/tools/test/reference_build/chrome": None,
       "src/chrome_frame/tools/test/reference_build/chrome_win": None,
       "src/chrome/tools/test/reference_build/chrome": None,
       "src/chrome/tools/test/reference_build/chrome_linux": None,
       "src/chrome/tools/test/reference_build/chrome_mac": None,
       "src/chrome/tools/test/reference_build/chrome_win": None,
     },
     "safesync_url": "",
   },
]```

System:
Window 8.1
M Visual Studio 2013 Update 5

Also tried with his URL in solution, getting same issue.
Need help? I am able to download chrome but not node webkit.

**Comment by ghostoy** [comment]
Latest build instructions can be found on official website http://docs.nwjs.io/

**Comment by vishalup** [comment]
Failed to get again. It says change from `managed:true` to `managed:false` in gclient.
