### ISSUE TITLE
Windows: native addon won't build with 0.13.0-rc3

### ISSUE THREAD

**Issue by c-geek** [nwjs/nw.js#4607]
Is this a broken ABI as stated in [wiki page](https://github.com/nwjs/nw.js/wiki/build-native-modules-with-nw-gyp)?

* nw 0.13.0-rc3
* Windows with Visual Studio 2013 Community edition

### Reproduce it

* Node 5.9.0
* Python 2.7

```
git clone https://github.com/ucoin-io/wotb
cd wotb
npm install
node-pre-gyp configure --runtime=node-webkit --target=0.13.0-rc3
set VCTargetsPath=C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120
node-pre-gyp build --runtime=node-webkit --target=0.13.0-rc3
```

> N.B.: I must use `set VCTargetsPath=C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120` otherwise I get a simple crash of the build for an unknown reason... found this quick fix [here](http://stackoverflow.com/questions/21069699/node-packages-not-building-on-windows-8-1-missing-microsoft-cpp-default-props)

### Details of build fail

```batch
C:\Users\cgeek\wotb>node-pre-gyp configure --runtime=node-webkit --target=0.13.0-rc3
```

Results in:

```text
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.23
node-pre-gyp info using node@5.9.0 | win32 | x64
gyp info it worked if it ends with ok
gyp info using nw-gyp@0.13.0
gyp info using node@5.9.0 | win32 | x64
(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
gyp info spawn python
gyp info spawn args [ 'C:\\Users\\cgeek\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\cgeek\\wotb\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\cgeek\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\cgeek\\.nw-gyp\\0.13.0-rc3\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\cgeek\\.nw-gyp\\0.13.0-rc3',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\cgeek\\wotb',
gyp info spawn args   '--depth=.',
gyp info spawn args   '-Dv13=1',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\cgeek\\wotb\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok
node-pre-gyp info ok
```

And then the failing command (build):

```
C:\Users\cgeek\wotb>node-pre-gyp build --runtime=node-webkit --target=0.13.0-rc3
```

Results in the error:

```
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.23
node-pre-gyp info using node@5.9.0 | win32 | x64
gyp info it worked if it ends with ok
gyp info using nw-gyp@0.13.0
gyp info using node@5.9.0 | win32 | x64
0.13.0-rc3
(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  wotb.cc
C:\Users\cgeek\.nw-gyp\0.13.0-rc3\src\node_buffer.h(13): warning C4068: unknown pragma [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\.nw-gyp\0.13.0-rc3\src\node_buffer.h(14): warning C4068: unknown pragma [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\.nw-gyp\0.13.0-rc3\src\node_buffer.h(16): warning C4068: unknown pragma [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(602): error C2039: 'GCEpilogueCallback' : is not a member of 'v8::Isolate' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
          C:\Users\cgeek\.nw-gyp\0.13.0-rc3\deps\v8\include\v8.h(5281) : see declaration of 'v8::Isolate'
C:\Users\cgeek\wotb\node_modules\nan\nan.h(602): error C2065: 'GCEpilogueCallback' : undeclared identifier [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(603): error C2146: syntax error : missing ')' before identifier 'callback' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(603): error C2182: 'AddGCEpilogueCallback' : illegal use of type 'void' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(603): error C2433: 'AddGCEpilogueCallback' : '__forceinline' not permitted on data declarations [C:\Users\cgeek\wotb\build\wot
b.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(603): error C2059: syntax error : ')' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(603): error C2143: syntax error : missing ';' before '{' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(603): error C2447: '{' : missing function header (old-style formal list?) [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(608): error C2039: 'GCEpilogueCallback' : is not a member of 'v8::Isolate' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
          C:\Users\cgeek\.nw-gyp\0.13.0-rc3\deps\v8\include\v8.h(5281) : see declaration of 'v8::Isolate'
C:\Users\cgeek\wotb\node_modules\nan\nan.h(608): error C2065: 'GCEpilogueCallback' : undeclared identifier [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(608): error C2146: syntax error : missing ')' before identifier 'callback' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(608): error C2182: 'RemoveGCEpilogueCallback' : illegal use of type 'void' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(608): error C2433: 'RemoveGCEpilogueCallback' : '__forceinline' not permitted on data declarations [C:\Users\cgeek\wotb\build\
wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(608): error C2059: syntax error : ')' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(608): error C2143: syntax error : missing ';' before '{' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(608): error C2447: '{' : missing function header (old-style formal list?) [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(613): error C2039: 'GCPrologueCallback' : is not a member of 'v8::Isolate' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
          C:\Users\cgeek\.nw-gyp\0.13.0-rc3\deps\v8\include\v8.h(5281) : see declaration of 'v8::Isolate'
C:\Users\cgeek\wotb\node_modules\nan\nan.h(613): error C2065: 'GCPrologueCallback' : undeclared identifier [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(614): error C2146: syntax error : missing ')' before identifier 'callback' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(614): error C2182: 'AddGCPrologueCallback' : illegal use of type 'void' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(614): error C2433: 'AddGCPrologueCallback' : '__forceinline' not permitted on data declarations [C:\Users\cgeek\wotb\build\wot
b.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(614): error C2059: syntax error : ')' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(614): error C2143: syntax error : missing ';' before '{' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(614): error C2447: '{' : missing function header (old-style formal list?) [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(619): error C2039: 'GCPrologueCallback' : is not a member of 'v8::Isolate' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
          C:\Users\cgeek\.nw-gyp\0.13.0-rc3\deps\v8\include\v8.h(5281) : see declaration of 'v8::Isolate'
C:\Users\cgeek\wotb\node_modules\nan\nan.h(619): error C2065: 'GCPrologueCallback' : undeclared identifier [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(619): error C2146: syntax error : missing ')' before identifier 'callback' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(619): error C2182: 'RemoveGCPrologueCallback' : illegal use of type 'void' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(619): error C2433: 'RemoveGCPrologueCallback' : '__forceinline' not permitted on data declarations [C:\Users\cgeek\wotb\build\
wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(619): error C2059: syntax error : ')' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(619): error C2143: syntax error : missing ';' before '{' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(619): error C2447: '{' : missing function header (old-style formal list?) [C:\Users\cgeek\wotb\build\wotb.vcxproj]
  functions.cc
C:\Users\cgeek\.nw-gyp\0.13.0-rc3\src\node_buffer.h(13): warning C4068: unknown pragma [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\.nw-gyp\0.13.0-rc3\src\node_buffer.h(14): warning C4068: unknown pragma [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\.nw-gyp\0.13.0-rc3\src\node_buffer.h(16): warning C4068: unknown pragma [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(602): error C2039: 'GCEpilogueCallback' : is not a member of 'v8::Isolate' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
          C:\Users\cgeek\.nw-gyp\0.13.0-rc3\deps\v8\include\v8.h(5281) : see declaration of 'v8::Isolate'
C:\Users\cgeek\wotb\node_modules\nan\nan.h(602): error C2065: 'GCEpilogueCallback' : undeclared identifier [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(603): error C2146: syntax error : missing ')' before identifier 'callback' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(603): error C2182: 'AddGCEpilogueCallback' : illegal use of type 'void' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(603): error C2433: 'AddGCEpilogueCallback' : '__forceinline' not permitted on data declarations [C:\Users\cgeek\wotb\build\wot
b.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(603): error C2059: syntax error : ')' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(603): error C2143: syntax error : missing ';' before '{' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(603): error C2447: '{' : missing function header (old-style formal list?) [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(608): error C2039: 'GCEpilogueCallback' : is not a member of 'v8::Isolate' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
          C:\Users\cgeek\.nw-gyp\0.13.0-rc3\deps\v8\include\v8.h(5281) : see declaration of 'v8::Isolate'
C:\Users\cgeek\wotb\node_modules\nan\nan.h(608): error C2065: 'GCEpilogueCallback' : undeclared identifier [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(608): error C2146: syntax error : missing ')' before identifier 'callback' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(608): error C2182: 'RemoveGCEpilogueCallback' : illegal use of type 'void' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(608): error C2433: 'RemoveGCEpilogueCallback' : '__forceinline' not permitted on data declarations [C:\Users\cgeek\wotb\build\
wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(608): error C2059: syntax error : ')' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(608): error C2143: syntax error : missing ';' before '{' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(608): error C2447: '{' : missing function header (old-style formal list?) [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(613): error C2039: 'GCPrologueCallback' : is not a member of 'v8::Isolate' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
          C:\Users\cgeek\.nw-gyp\0.13.0-rc3\deps\v8\include\v8.h(5281) : see declaration of 'v8::Isolate'
C:\Users\cgeek\wotb\node_modules\nan\nan.h(613): error C2065: 'GCPrologueCallback' : undeclared identifier [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(614): error C2146: syntax error : missing ')' before identifier 'callback' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(614): error C2182: 'AddGCPrologueCallback' : illegal use of type 'void' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(614): error C2433: 'AddGCPrologueCallback' : '__forceinline' not permitted on data declarations [C:\Users\cgeek\wotb\build\wot
b.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(614): error C2059: syntax error : ')' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(614): error C2143: syntax error : missing ';' before '{' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(614): error C2447: '{' : missing function header (old-style formal list?) [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(619): error C2039: 'GCPrologueCallback' : is not a member of 'v8::Isolate' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
          C:\Users\cgeek\.nw-gyp\0.13.0-rc3\deps\v8\include\v8.h(5281) : see declaration of 'v8::Isolate'
C:\Users\cgeek\wotb\node_modules\nan\nan.h(619): error C2065: 'GCPrologueCallback' : undeclared identifier [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(619): error C2146: syntax error : missing ')' before identifier 'callback' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(619): error C2182: 'RemoveGCPrologueCallback' : illegal use of type 'void' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(619): error C2433: 'RemoveGCPrologueCallback' : '__forceinline' not permitted on data declarations [C:\Users\cgeek\wotb\build\
wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(619): error C2059: syntax error : ')' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(619): error C2143: syntax error : missing ';' before '{' [C:\Users\cgeek\wotb\build\wotb.vcxproj]
C:\Users\cgeek\wotb\node_modules\nan\nan.h(619): error C2447: '{' : missing function header (old-style formal list?) [C:\Users\cgeek\wotb\build\wotb.vcxproj]
c:\users\cgeek\wotb\wotcpp\include\node.h(21): warning C4267: 'return' : conversion from 'size_t' to 'uint32_t', possible loss of data [C:\Users\cgeek\wotb\build\wotb.vc
xproj]
c:\users\cgeek\wotb\wotcpp\include\webOfTrust.h(25): warning C4267: 'return' : conversion from 'size_t' to 'uint32_t', possible loss of data [C:\Users\cgeek\wotb\build\w
otb.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\cgeek\AppData\Roaming\npm\node_modules\nw-gyp\lib\build.js:287:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\cgeek\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\bin\\nw-gyp.js" "build" "--runtime=node-webkit" "-
target=0.13.0-rc3" "--module=C:\\Users\\cgeek\\wotb\\lib\\binding\\Release\\node-webkit-v0.13.0-rc3-win32-x64\\wotb.node" "--module_name=wotb" "--module_path=C:\\Users\\
geek\\wotb\\lib\\binding\\Release\\node-webkit-v0.13.0-rc3-win32-x64"
gyp ERR! cwd C:\Users\cgeek\wotb
gyp ERR! node -v v5.9.0
gyp ERR! nw-gyp -v v0.13.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'nw-gyp.cmd build --runtime=node-webkit --target=0.13.0-rc3 --module=C:\Users\cgeek\wotb\lib\binding\Release\node-webkit
v0.13.0-rc3-win32-x64\wotb.node --module_name=wotb --module_path=C:\Users\cgeek\wotb\lib\binding\Release\node-webkit-v0.13.0-rc3-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\cgeek\AppData\Roaming\npm\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:100:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:850:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\cgeek\\AppData\\Roaming\\npm\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "build" "--runti
e=node-webkit" "--target=0.13.0-rc3"
node-pre-gyp ERR! cwd C:\Users\cgeek\wotb
node-pre-gyp ERR! node -v v5.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.23
node-pre-gyp ERR! not ok
Failed to execute 'nw-gyp.cmd build --runtime=node-webkit --target=0.13.0-rc3 --module=C:\Users\cgeek\wotb\lib\binding\Release\node-webkit-v0.13.0-rc3-win32-x64\wotb.nod
 --module_name=wotb --module_path=C:\Users\cgeek\wotb\lib\binding\Release\node-webkit-v0.13.0-rc3-win32-x64' (1)
```

**Comment by c-geek** [comment]
Updated nan@2.1.0 to nan@2.2.0 and this is now OK.

Sorry about this.
