### ISSUE TITLE
Cannot register Command key on 0.14.* (osx)

### ISSUE THREAD

**Issue by yeliex** [nwjs/nw.js#4737]
``` javascript
      shortcut = new nw.Shortcut({
        key: "Command+Ctrl+F",
        active: function () {
          win.toggleFullscreen();
        },
        failed: function (err) {
          console.log(err);
        }
      });
      nw.App.registerGlobalHotKey(shortcut);
```

Error: 

``` javascript
Error: Unable to register the hotkey
    at Function.Shortcut.registerGlobalHotKey (extensions::nw.Shortcut:204:29)
    at Object.bindingsAPI.compiledApi.registerGlobalHotKey (extensions::nw.App:114:45)
    at http://localhost:8989/index.js:23930:15
    at Object.<anonymous> (http://localhost:8989/index.js:23933:4)
    at Object.<anonymous> (http://localhost:8989/index.js:23944:31)
    at __webpack_require__ (http://localhost:8989/common.js:586:30)
    at fn (http://localhost:8989/common.js:110:20)
    at Object.<anonymous> (http://localhost:8989/index.js:6:19)
    at __webpack_require__ (http://localhost:8989/common.js:586:30)
    at webpackJsonpCallback (http://localhost:8989/common.js:22:20)
```

**Comment by ghostoy** [comment]
@yeliex Hot keys are registered globally. If any other app has registered the same hot keys, it will fail. Could you check if you can register other keys, such as `Command+Alt+F`? If other keys can be registered, `Command+Ctrl+F` might be registered already by other apps. If you just want to use hotkeys inside your app, try use menu bars (see http://docs.nwjs.io/en/latest/For%20Users/Advanced/Customize%20Menubar/).

**Comment by yeliex** [comment]
@ghostoy I can resist the same hot key on 0.14.1 and other earlier versions,but it just do not work on 0.14.2

**Comment by Christywl** [comment]
I can't reproduce this issue on Mac with nwjs-sdk-v0.21.6. `Command+Ctrl+F` works fine. No errors.

**Comment by Christywl** [comment]
close until there is more information
