### ISSUE TITLE
Opening and closing DevTools set nwjs.exe exit code to 258 and return error in child_process methods calls

### ISSUE THREAD

**Issue by vsemozhetbyt** [nwjs/nw.js#4798]
Win 7 SP 1, NW.js 0.15.0-beta2.

1) Create any simple NW.js test application.

2) Create this script for Node.js:

```javascript
require('child_process').exec(
  'path_to_nw.exe path_to_test_app',
  err => {console.error(err);}
);
```

3) Run the script with Node.js. After the app starts, just close it. The output is:

`null`

3) Run the script. After the app starts, open DevTools, close DevTools, then close the app. The output is:

```
{ Error: Command failed: path_to_nw.exe path_to_test_app

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:485:12)
  killed: false,
  code: 258,
  signal: null,
  cmd: 'path_to_nw.exe path_to_test_app' }
```

**Comment by march1993** [comment]
`console.error('' + err);` may help

**Comment by Christywl** [comment]
I can reproduce this issue on Windows 8 with nwjs-sdk-v0.21.6(This error doesn't occur on Linux).
