### ISSUE TITLE
WebGL & Frameless & Toolbar & DevTools errors

### ISSUE THREAD

**Issue by TheAifam5** [nwjs/nw.js#5128]
Version: v0.15.4
Commit hash: 63bc85a-0fc8753-3ee2c58-8655cb9
(Downloaded from website)

I wanted to test this application since Electron its horrible written and they not using specific code style. Its just ugly and unreadable. Name is "Electron" but everythwere is "Atom" -.-.
Nevermind.

I ran: "nwjs.app/Contents/MacOS/nwjs ./webgl" on MacOSX 10.11.06.
WebGL is master from the zcbenz/nw-sample-apps

Log from application using "WebGL Example" and "Frameless Example" directly after run:
(Yea logs are -i think- similar)
```
2016-07-20 10:05:00.816 nwjs[1053:19859] NSWindow warning: adding an unknown subview: <WebContentsViewCocoa: 0x7fd812edbea0>. Break on NSLog to debug.
2016-07-20 10:05:00.817 nwjs[1053:19859] Call stack:
(
	0   AppKit                              0x00007fff902f07b7 -[NSThemeFrame addSubview:] + 107
	1   nwjs Framework                      0x000000010cc3e52e _ZN2v88UnlockerD1Ev + 20640574
	2   nwjs Framework                      0x000000010cc3de76 _ZN2v88UnlockerD1Ev + 20638854
	3   nwjs Framework                      0x000000010cc3cfca _ZN2v88UnlockerD1Ev + 20635098
	4   nwjs Framework                      0x000000010d8f5ab9 _ZN2v88UnlockerD1Ev + 33974473
	5   nwjs Framework                      0x000000010d847cd1 _ZN2v88UnlockerD1Ev + 33262305
	6   nwjs Framework                      0x000000010d913081 _ZN2v88UnlockerD1Ev + 34094737
	7   nwjs Framework                      0x000000010d914e7f _ZN2v88UnlockerD1Ev + 34102415
	8   nwjs Framework                      0x000000010d915118 _ZN2v88UnlockerD1Ev + 34103080
	9   nwjs Framework                      0x000000010d92e2c9 _ZN2v88UnlockerD1Ev + 34205913
	10  nwjs Framework                      0x000000010d92e191 _ZN2v88UnlockerD1Ev + 34205601
	11  nwjs Framework                      0x000000010dadd5bf _ZN2v88UnlockerD1Ev + 35972047
	12  nwjs Framework                      0x000000010d29d9f1 _ZN2v88UnlockerD1Ev + 27322369
	13  nwjs Framework                      0x000000010d061e07 _ZN2v88UnlockerD1Ev + 24980503
	14  nwjs Framework                      0x000000010d1bb779 _ZN2v88UnlockerD1Ev + 26396041
	15  nwjs Framework                      0x000000010a951128 ChromeMain + 16232280
	16  nwjs Framework                      0x0000000109e91b6b ChromeMain + 4962715
	17  nwjs Framework                      0x0000000109eb4303 ChromeMain + 5103923
	18  nwjs Framework                      0x0000000109eb461c ChromeMain + 5104716
	19  nwjs Framework                      0x0000000109eb480b ChromeMain + 5105211
	20  nwjs Framework                      0x0000000109e86e91 ChromeMain + 4918465
	21  nwjs Framework                      0x0000000109ea9e3a ChromeMain + 5061738
	22  nwjs Framework                      0x0000000109e86894 ChromeMain + 4916932
	23  CoreFoundation                      0x00007fffa0916881 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	24  CoreFoundation                      0x00007fffa08f5fbc __CFRunLoopDoSources0 + 556
	25  CoreFoundation                      0x00007fffa08f54df __CFRunLoopRun + 927
	26  CoreFoundation                      0x00007fffa08f4ed8 CFRunLoopRunSpecific + 296
	27  HIToolbox                           0x00007fff8cc6c935 RunCurrentEventLoopInMode + 235
	28  HIToolbox                           0x00007fff8cc6c76f ReceiveNextEventCommon + 432
	29  HIToolbox                           0x00007fff8cc6c5af _BlockUntilNextEventMatchingListInModeWithFilter + 71
	30  AppKit                              0x00007fff902d5df6 _DPSNextEvent + 1067
	31  AppKit                              0x00007fff902d5226 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
	32  AppKit                              0x00007fff902c9d80 -[NSApplication run] + 682
	33  nwjs Framework                      0x0000000109e87606 ChromeMain + 4920374
	34  nwjs Framework                      0x0000000109e86ce4 ChromeMain + 4918036
	35  nwjs Framework                      0x0000000109ecae03 ChromeMain + 5196851
	36  nwjs Framework                      0x0000000109a60468 ChromeMain + 565912
	37  nwjs Framework                      0x000000010cfa1c67 _ZN2v88UnlockerD1Ev + 24193655
	38  nwjs Framework                      0x000000010cfa4242 _ZN2v88UnlockerD1Ev + 24203346
	39  nwjs Framework                      0x000000010cf9d93d _ZN2v88UnlockerD1Ev + 24176461
	40  nwjs Framework                      0x0000000109e49b41 ChromeMain + 4667761
	41  nwjs Framework                      0x0000000109e48cc6 ChromeMain + 4664054
	42  nwjs Framework                      0x00000001099d6212 ChromeMain + 66
	43  nwjs                                0x000000010976ed52 main + 530
	44  nwjs                                0x000000010976eb34 nwjs + 2868
	45  ???                                 0x0000000000000002 0x0 + 2
)
```

In Frameless example DevTools doesn't work:
```
chrome-extension://pkhgemapnfafkbpdhglknfhnidbaicdj/frameless_window.js:83
    if (win.isDevToolsOpen()) {
            ^

TypeError: win.isDevToolsOpen is not a function
    at HTMLButtonElement.document.querySelector.onclick (chrome-extension://pkhgemapnfafkbpdhglknfhnidbaicdj/frameless_window.js:83:13)
chrome-extension://pkhgemapnfafkbpdhglknfhnidbaicdj/frameless_window.js:83
    if (win.isDevToolsOpen()) {
            ^
```

In FileExplorerExample throwing when i click "About":
```
extensions::schemaUtils:34
      throw new Error(message);
      ^

Error: Invalid value for argument 2. Property 'toolbar': Unexpected property.
    at validate (extensions::schemaUtils:34:13)
    at Object.normalizeArgumentsAndValidate (extensions::schemaUtils:117:3)
    at Object.<anonymous> (extensions::binding:414:30)
    at Object.about (chrome-extension://npfnmehgalggmdjddldgojjmnapbkmgd/main.js:18:34)
    at HTMLAnchorElement.onclick (chrome-extension://npfnmehgalggmdjddldgojjmnapbkmgd/index.html:33:65)
```

I think that's all.

**Comment by Christywl** [comment]
WebGL issue: only reproduce on Mac OS
Frameless-window/FileExplorer: reproduce on Linux/Windows/Mac OS
`nwjs version: sdk-0.21.3`
