### ISSUE TITLE
some modules build error.

### ISSUE THREAD

**Issue by duncup** [nwjs/nw.js#5172]
I want to build some modules to control my printer.
[modules issues](https://github.com/EmergingTechnologyAdvisors/node-serialport/issues/889#issuecomment-236027496)
And i can't get some help to build this.
Thanks so much.

**Comment by ghostoy** [comment]
@duncup The error was from frameworks of OSX and I can't reproduce on my machine.

Does it happen if you just run `npm install serialport --build-from-source` without specifying `--runtime=node-webkit` and `--target=0.16.0`?

**Comment by duncup** [comment]
@ghostoy I try this `npm install serialport --build-from-source`,and get error too.
```
> serialport@4.0.1 install /Users/steppenwolf/gbl/posOrderChecker/node_modules/serialport
> node-pre-gyp install --fallback-to-build

  CXX(target) Release/obj.target/serialport/src/serialport.o
  CXX(target) Release/obj.target/serialport/src/serialport_unix.o
In file included from /System/Library/Frameworks/IOKit.framework/Headers/usb/IOUSBLib.h:27:0,
                 from ../src/serialport_unix.cpp:14:
/System/Library/Frameworks/IOKit.framework/Headers/usb/USB.h:612:23: error: too many #pragma options align=reset
 #pragma options align=reset
                       ^
In file included from /System/Library/Frameworks/IOKit.framework/Headers/usb/IOUSBLib.h:27:0,
                 from ../src/serialport_unix.cpp:14:
/System/Library/Frameworks/IOKit.framework/Headers/usb/USB.h:782:23: error: too many #pragma options align=reset
 #pragma options align=reset
                       ^
/System/Library/Frameworks/IOKit.framework/Headers/usb/USB.h:834:23: error: too many #pragma options align=reset
 #pragma options align=reset
                       ^
/System/Library/Frameworks/IOKit.framework/Headers/usb/USB.h:852:23: error: too many #pragma options align=reset
 #pragma options align=reset
                       ^
/System/Library/Frameworks/IOKit.framework/Headers/usb/USB.h:872:23: error: too many #pragma options align=reset
 #pragma options align=reset
                       ^
make: *** [Release/obj.target/serialport/src/serialport_unix.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/steppenwolf/gbl/posOrderChecker/node_modules/serialport/build/Release/serialport.node" "--module_name=serialport" "--module_path=/Users/steppenwolf/gbl/posOrderChecker/node_modules/serialport/build/Release"
gyp ERR! cwd /Users/steppenwolf/gbl/posOrderChecker/node_modules/serialport
gyp ERR! node -v v4.4.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/steppenwolf/gbl/posOrderChecker/node_modules/serialport/build/Release/serialport.node --module_name=serialport --module_path=/Users/steppenwolf/gbl/posOrderChecker/node_modules/serialport/build/Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/steppenwolf/gbl/posOrderChecker/node_modules/serialport/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Darwin 15.4.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/steppenwolf/gbl/posOrderChecker/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/steppenwolf/gbl/posOrderChecker/node_modules/serialport
node-pre-gyp ERR! node -v v4.4.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.29
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/steppenwolf/gbl/posOrderChecker/node_modules/serialport/build/Release/serialport.node --module_name=serialport --module_path=/Users/steppenwolf/gbl/posOrderChecker/node_modules/serialport/build/Release' (1)
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "serialport" "--build-from-source"
npm ERR! node v4.4.2
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! serialport@4.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serialport@4.0.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs serialport
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/steppenwolf/gbl/posOrderChecker/npm-debug.log
```
I get gcc version message
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/local/libexec/gcc/x86_64-apple-darwin15/4.9.3/lto-wrapper
Target: x86_64-apple-darwin15
Configured with: /opt/local/var/macports/build/_opt_mports_dports_lang_gcc49/gcc49/work/gcc-4.9.3/configure --prefix=/opt/local --build=x86_64-apple-darwin15 --enable-languages=c,c++,objc,obj-c++,lto,fortran,java --libdir=/opt/local/lib/gcc49 --includedir=/opt/local/include/gcc49 --infodir=/opt/local/share/info --mandir=/opt/local/share/man --datarootdir=/opt/local/share/gcc-4.9 --with-local-prefix=/opt/local --with-system-zlib --disable-nls --program-suffix=-mp-4.9 --with-gxx-include-dir=/opt/local/include/gcc49/c++/ --with-gmp=/opt/local --with-mpfr=/opt/local --with-mpc=/opt/local --with-isl=/opt/local --disable-isl-version-check --with-cloog=/opt/local --disable-cloog-version-check --enable-stage1-checking --disable-multilib --enable-lto --enable-libstdcxx-time --with-as=/opt/local/bin/as --with-ld=/opt/local/bin/ld --with-ar=/opt/local/bin/ar --with-bugurl=https://trac.macports.org/newticket --with-pkgversion='MacPorts gcc49 4.9.3_0' --with-build-config=bootstrap-debug
Thread model: posix
gcc version 4.9.3 (MacPorts gcc49 4.9.3_0) 
```

**Comment by duncup** [comment]
Mybe i just use a wrong gcc version?
Any idea?

**Comment by ghostoy** [comment]
@duncup I was using the default system toolchains from XCode (see below).

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by duncup** [comment]
@ghostoy Can i get some help to change this?
I change this a long time.

**Comment by duncup** [comment]
I see i use the `ports` install the mp-gcc49,and want to change this to use apple gcc.
Thanks.

**Comment by ghostoy** [comment]
Currently OSX is using cLang/clang++ instead of gcc/g++. You can `CC` and `CXX` env to temporarily using specified clang/clang++ installed with XCode. e.g.

```bash
export CC=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
export CXX=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
```

**Comment by duncup** [comment]
I can build this now.
Thanks again.
