### ISSUE TITLE
Issue running protractor test on nwjs(0.15.4) app which was working fine on nwjs version 0.12.3

### ISSUE THREAD

**Issue by vsathyak** [nwjs/nw.js#5289]
Hi guys,

 After updating to nwjs 0.15.4 from 0.12.3, our e2e test script built using protractor framework to test the nwjs app is not working. Can someone pls look at this issue and let me know if there is anything wrong with our conf.js?

```
nwjs version : 0.15.4
node version : 6.5.0
protractor version : 4.0.4
chrome driver : 2.23
OS version : Mac OS 10.11.6 
```

Protracor conf.js : 

```
exports.config = {
    directConnect: true,
    chromeDriver: '/usr/local/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.23',

    capabilities: {
        browserName: 'chrome',
        chromeOptions: {
            binary: '/Applications/....../..../MacOS/nwjs'
        }
    },
    baseUrl: '',
    rootElement: 'html',
    onPrepare: function() {
        browser.resetUrl = '';
        // browser.driver.get('file://');
    },

    getPageTimeout: 150000,
    allScriptsTimeout: 150000,
    framework: 'jasmine2',
    specs: ['../test/abc/*_spec.js'],
    jasmineNodeOpts: {
        showColors: true,
        defaultTimeoutInterval: 150000
    }
};
```

Error : 

```
dhcp-10-150-29-108:project test$ protractor conf.js
[12:04:10] I/direct - Using ChromeDriver directly...
[12:04:10] I/launcher - Running 1 instances of WebDriver
[12:05:10] E/launcher - unknown error: unable to discover open pages
  (Driver info: chromedriver=2.23.409710 (0c4084804897ac45b5ff65a690ec6583b97225c0),platform=Mac OS X 10.11.3 x86_64)

[12:05:10] E/launcher - WebDriverError: unknown error: unable to discover open pages
  (Driver info: chromedriver=2.23.409710 (0c4084804897ac45b5ff65a690ec6583b97225c0),platform=Mac OS X 10.11.3 x86_64)
    at WebDriverError (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:27:5)
    at Object.checkLegacyResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:639:15)
    at parseHttpResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:538:13)
    at client_.send.then.response (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:472:11)
    at ManagedPromise.invokeCallback_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1379:14)
    at TaskQueue.execute_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2913:14)
    at TaskQueue.executeNext_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2896:21)
    at asyncRun (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2820:25)
    at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (internal/process/next_tick.js:103:7)

From: Task: WebDriver.createSession()
    at Function.createSession (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:329:24)
    at Driver (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/chrome.js:778:38)
    at Direct.getNewDriver (/usr/local/lib/node_modules/protractor/built/driverProviders/direct.js:68:26)
    at Runner.createBrowser (/usr/local/lib/node_modules/protractor/built/runner.js:190:43)
    at /usr/local/lib/node_modules/protractor/built/runner.js:264:30
    at _fulfilled (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/protractor/node_modules/q/q.js:556:49
    at runSingle (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:137:13)
[12:05:10] E/launcher - Process exited with error code 199
dhcp-10-150-29-108:project test$ 
```

**Comment by ghostoy** [comment]
Are you using the `chromedriver` bundled with NW.js SDK package? If not, please try to replace your own chromedriver with it.
