### ISSUE TITLE
gRPC fails on Mac OS X Sierra

### ISSUE THREAD

**Issue by troylelandshields** [nwjs/nw.js#5360]
Read the following before submitting your issue, thank you.

OS: Mac OS X Sierra 10.12
NWJS: 0.15.4
Node: 6.2.1

I installed the gRPC module with `npm install grpc --build-from-source --runtime=node-webkit --target=0.15.4 --target_arch=x64` based on the suggestion from https://github.com/nwjs/nw.js/issues/5103, but it's still not working.

Error when running an nwjs app that uses grpc:

```
nw .
Using nw.js v0.15.4
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

[59476:54023:1013/101446:ERROR:login_database.cc(419)] Password store database is too new, kCurrentVersionNumber=17, GetCompatibleVersionNumber=18

[59476:54023:1013/101446:ERROR:password_store_proxy_mac.cc(95)] Could not create/open login database.

[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0


module.js:610
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: dlopen(/Users/troyshields/projects/omgrpc/node_modules/grpc/src/node/extension_binary/grpc_node.node, 1): Symbol not found: _GENERAL_NAME_free
  Referenced from: /Users/troyshields/projects/omgrpc/node_modules/grpc/src/node/extension_binary/grpc_node.node
  Expected in: flat namespace
 in /Users/troyshields/projects/omgrpc/node_modules/grpc/src/node/extension_binary/grpc_node.node
    at Error (native)
    at Object.Module._extensions..node (module.js:610:18)
    at Module.load (module.js:482:32)
    at tryModuleLoad (module.js:441:12)
    at Function.Module._load (module.js:433:3)
    at Module.require (module.js:492:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/troyshields/projects/omgrpc/node_modules/grpc/src/node/src/grpc_extension.js:38:15)
    at Module._compile (module.js:565:32)
    at Object.Module._extensions..js (module.js:580:10)
```

Any help that can be given is much appreciated, thanks!

PS: When using the latest version of nwjs I get a different issue (it fails to build actually). I wanted to try to get version 0.15.4 working since I know that it worked for that other issue.

**Comment by rogerwang** [comment]
0.15 contains Chromium 51, which don't support Sierra well. Please use latest 0.18. If you have other issues, please follow up in #5103. If you have questions, please ask them in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
