### ISSUE TITLE
can t buid nw 0.19

### ISSUE THREAD

**Issue by smolleyes** [nwjs/nw.js#5541]
hi 

when using gclient sync it always fail on 

`gclient sync -v --with_branch_heads --jobs=16 -> `

```
Traceback (most recent call last):
  File "/opt/nwjs_build/depot_tools/download_from_google_storage.py", line 538, in <module>
    sys.exit(main(sys.argv))
  File "/opt/nwjs_build/depot_tools/download_from_google_storage.py", line 534, in main
    options.extract)
  File "/opt/nwjs_build/depot_tools/download_from_google_storage.py", line 358, in download_from_google_storage
    ignore_errors, output, sha1_file, auto_platform)
  File "/opt/nwjs_build/depot_tools/download_from_google_storage.py", line 152, in enumerate_work_queue
    raise FileNotFoundError('%s not found.' % input_filename)
__main__.FileNotFoundError: src/v8/test/fuzzer/wasm.tar.gz.sha1 not found.
Error: Command 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-fuzzer -s src/v8/test/fuzzer/wasm.tar.gz.sha1' returned non-zero exit status 1 in /opt/nwjs_build/build_dir


```

my .gclient is

```
solutions = [
  { "name"        : "src",
    "url"         : "https://github.com/nwjs/chromium.src.git@origin/nw19",
    "deps_file"   : "DEPS",
    "managed"     : True,
    "custom_deps" : {
    "src/third_party/WebKit/LayoutTests": None,
    "src/chrome_frame/tools/test/reference_build/chrome": None,
    "src/chrome_frame/tools/test/reference_build/chrome_win": None,
    "src/chrome/tools/test/reference_build/chrome": None,
    "src/chrome/tools/test/reference_build/chrome_linux": None,
    "src/chrome/tools/test/reference_build/chrome_mac": None,
    "src/chrome/tools/test/reference_build/chrome_win": None,
    },
  },
]
cache_dir = None
```

an idear why ?

**Comment by broken** [comment]
I'm running into the same issue. @smolleyes what did you do to fix it?

**Comment by Ontopic** [comment]
Same issue here. Any known solutions?
