### ISSUE TITLE
outdated doc for osX build (on sierra)

### ISSUE THREAD

**Issue by smolleyes** [nwjs/nw.js#5555]
i builded nwjs yesterday on osx Sierra

1/ for the .glcient even if i select nw19 for the doc it always show 

```
mkdir -p $HOME/nwjs
cd $HOME/nwjs
gclient config --name=src https://github.com/nwjs/chromium.src.git@origin/nw**17**

```

2 / for osx build, the doc tell us

> Xcode 7
> 
> Mac SDK 10.11 as part of Xcode 7 is not supported yet. If you have upgraded to Xcode 7, either downgrade to Xcode 6 or copy Mac SDK 10.10 from other machines under  `xcode-select -p`/Platforms/MacOSX.platform/Developer/SDKs as suggested by Chromium document.

this is not true anymore, i builded it with xcode 8.2 installed i just had to copy osx sdk 10**.11** and not 10.**10**  in /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs

and have to do 

``xcode-select -p`/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs`

not 

``xcode-select -p`/Platforms/MacOSX.platform/Developer/SDKs`

and everything was fine (not working with 10.10 sdk)

thanks!

**Comment by smolleyes** [comment]
hello @ghostoy 

possible to add some minimalistic infos on chroot 32 for linux :p ?

i just tried, with schroot, i have a full chroot with all folders needed binded with fstab etc ...

i don t know if i need to export new GYP_DEFINES (and what if yes x68 / ia32 ?)

and when i run gen out/nw .... i have 

```
Traceback (most recent call last):
  File "/opt/nwjs_build/depot_tools/gn.py", line 38, in <module>
    sys.exit(main(sys.argv))
  File "/opt/nwjs_build/depot_tools/gn.py", line 33, in main
    return subprocess.call([gn_path] + args[1:])
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

```
can t find wich file/folder is missing

thanks

**Comment by smolleyes** [comment]
ok

tried many think, need doc to build linux 32 bits  from x64 host thru chroot :(

**Comment by smolleyes** [comment]
last try end with

```
gn gen out/nw  --args='is_debug=false is_component_ffmpeg=true target_cpu="x86" is_official_build=true ffmpeg_branding="Chrome" nwjs_sdk=false proprietary_codecs=true enable_ac3_eac3_audio_demuxing=true enable_hevc_demuxing=true remove_webcore_debug_symbols=true symbol_level=0 use_sysroot=true'

Done. Made 5002 targets from 1117 files in 906ms

sylvain@sylvain-pc:/opt/nwjs_build/build_dir/src$ ninja -j8 -C out/nw nwjs

ninja: Entering directory `out/nw'
[1/24223] CXX obj/base/base/message_pump_uv.o
FAILED: obj/base/base/message_pump_uv.o 
../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/base/base/message_pump_uv.o.d -DUSE_SYMBOLIZE -DV8_DEPRECATION_WARNINGS -DENABLE_MDNS=1 -DENABLE_NOTIFICATIONS -DENABLE_PEPPER_CDMS -DENABLE_PLUGINS=1 -DENABLE_PDF=1 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DUSE_UDEV -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_CLIPBOARD_AURAX11=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DNO_TCMALLOC -DENABLE_WEBRTC=1 -DDISABLE_NACL -DENABLE_EXTENSIONS=1 -DENABLE_TASK_MANAGER=1 -DENABLE_THEMES=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_SERVICE_DISCOVERY=1 -DUSE_PROPRIETARY_CODECS -DOFFICIAL_BUILD -DCHROMIUM_BUILD -DENABLE_MEDIA_ROUTER=1 -DFIELDTRIAL_TESTING_ENABLED -DCR_CLANG_REVISION=282487-1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DBASE_IMPLEMENTATION -I../.. -Igen -I../../build/linux/debian_wheezy_i386-sysroot/usr/include/glib-2.0 -I../../build/linux/debian_wheezy_i386-sysroot/usr/lib/i386-linux-gnu/glib-2.0/include -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pipe -B../../third_party/binutils/Linux_x64/Release/bin -fcolor-diagnostics -fdebug-prefix-map=/opt/nwjs_build/build_dir/src=. -pthread -m32 -msse2 -mfpmath=sse -mmmx -momit-leaf-frame-pointer -mstack-alignment=16 -mstackrealign -Wall -Werror -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-deprecated-register -Wno-unneeded-internal-declaration -Wno-inconsistent-missing-override -Wno-shift-negative-value -Wno-undefined-var-template -Wno-nonportable-include-path -Wno-address-of-packed-member -g0 --sysroot=../../build/linux/debian_wheezy_i386-sysroot -fvisibility=hidden -Xclang -load -Xclang ../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-ipc -Wheader-hygiene -Wstring-conversion -Wno-char-subscripts -Wexit-time-destructors -Wexit-time-destructors -O2 -fno-ident -fdata-sections -ffunction-sections -fno-threadsafe-statics -fvisibility-inlines-hidden -std=gnu++11 -fno-rtti -fno-exceptions -c ../../base/message_loop/message_pump_uv.cc -o obj/base/base/message_pump_uv.o
In file included from ../../base/message_loop/message_pump_uv.cc:26:
../../content/nw/src/common/node_hooks.h:55:3: error: unknown type name 'VoidIntFn'
V(VoidIntFn, "g_uv_init_nw", g_uv_init_nw_fn)
  ^
1 error generated.
[8/24223] CXX obj/base/base/file_util_posix.o
ninja: build stopped: subcommand failed.

```

**Comment by ghostoy** [comment]
Node is built with GYP. You must missed the step of `./build/gyp_chromium -I third_party/node/common.gypi third_party/node/node.gyp`.

As for the build error, you should manually update all NW.js specific repositories: v8, content/nw and third_party/node. They were not automatically updated by `gclient`.

**Comment by ghostoy** [comment]
Official build steps and parameters can be found in our buildbot http://buildbot-master.node-webkit.org:8010. For example, for 32-bit Linux SDK build for nw19, you can find all information in http://buildbot-master.node-webkit.org:8010/builders/nw19_sdk_linux32. If you look into specific build, you can check the "log" links for each step, and it will show you all the environments, full CLI arguments and outputs.

**Comment by smolleyes** [comment]
hi @ghostoy 

it s exactly what i did... 

i replied here

https://groups.google.com/forum/#!topic/nwjs-dev/88DsXVIyxPg

curious to see the answer :p

**Comment by smolleyes** [comment]
linux 32 build done, now i have an error with ffmpeg build... seems a clang 4 bug ... boring
