### ISSUE TITLE
I test it with chromedriver using selenium tool, but got WebDriverException : No current window when running code "driver.maximize_window()"

### ISSUE THREAD

**Issue by kirazhou** [nwjs/nw.js#5593]
I test it with chromedriver using selenium tool, but got WebDriverException "No current window"  when running code "driver.maximize_window()" I don't know how to solve it, and I don't want to set fullscreen in package.json file. Can anyone help me? Thanks you!

Code: 
chromeOptions = webdriver.ChromeOptions()
path_f = sys.path[0]
prefs = {"download.default_directory": self.path_f}
chromeOptions.add_experimental_option("prefs", prefs)
executable_path = "G:\\automation\\ddd\\nwjs-sdk-v0.19.3-win-x64\\chromedriver.exe"
driver = webdriver.Chrome(executable_path=executable_path, chrome_options=chromeOptions)
time_start = time.time()
driver.get("https://" + para.TEST_SERVER_IP)
driver.maximize_window()

Error:
Traceback (most recent call last):
    driver.maximize_window()
  File "C:\Python27\lib\site-packages\selenium-2.47.3-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 514, in maximize_window
    self.execute(command, {"windowHandle": "current"})
  File "C:\Python27\lib\site-packages\selenium-2.47.3-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium-2.47.3-py2.7.egg\selenium\webdriver\remote\errorhandler.py", line 181, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: No current window
JavaScript stack:
Error: No current window
    at checkForExtensionError (chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/background.js:14:17)
    at Object.callback (chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/background.js:67:5)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:81:7)
  (Session info: chrome=55.0.2883.87)
  (Driver info: chromedriver=2.24 (1888409316e3ba2f332a6acd74e601c83c720226),platform=Windows NT 10.0.14393 x86_64)

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

btw, our test cases are running well with chromedriver, you can have a check: https://github.com/nwjs/nw.js/tree/nw19/test/sanity

**Comment by kirazhou** [comment]
Thank you!
