### ISSUE TITLE
Running native module failed with Uncaught Error: The specified procedure could not be found.

### ISSUE THREAD

**Issue by qqq219** [nwjs/nw.js#5812]
Hello, Everybody.
    I had create a new module hello world and build it with nw-gpy success.
    But when I call the api in js like below:

    var addon = require('../native/build/Release/vlcwrap.node');
    exports.hello = function() { return addon.hello();}

    There is an error happens:
    
Uncaught Error: The specified procedure could not be found.
\\?\D:\develop\nwjs\nwjs-sdk-v0.21.3-win-x64\src\native\build\Release\vlcwrap.node
    at Object.Module._extensions..node (module.js:640:18)
    at Module.load (module.js:512:32)
    at tryModuleLoad (module.js:471:12)
    at Function.Module._load (module.js:463:3)
    at Module.require (module.js:522:17)
    at require (internal/module.js:20:19)
    at self.require (<anonymous>:11:26)

   Is there anybody knows how to handle it? Thanks for any suggestion.

**Comment by rogerwang** [comment]
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general
