### ISSUE TITLE
Building nw18 for ARMv7 fails

### ISSUE THREAD

**Issue by LeonardLaszlo** [nwjs/nw.js#5856]
@rogerwang @ghostoy @jtg-gg

When I run `python build/gyp_chromium -Goutput_dir=out_gn_arm third_party/node/node.gyp` during the build of **nw18** I get the following error message:
```
leonard@ubuntu:~/nwjs/src$ python build/gyp_chromium -Goutput_dir=out_gn_arm third_party/node/node.gyp
Updating projects from gyp files...
Traceback (most recent call last):
  File "build/gyp_chromium", line 12, in <module>
    execfile(__file__ + '.py')
  File "build/gyp_chromium.py", line 361, in <module>
    sys.exit(main())
  File "build/gyp_chromium.py", line 348, in main
    gyp_rc = gyp.main(args)
  File "/home/leonard/nwjs/src/tools/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/home/leonard/nwjs/src/tools/gyp/pylib/gyp/__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/home/leonard/nwjs/src/tools/gyp/pylib/gyp/generator/ninja.py", line 2469, in GenerateOutput
    pool.map(CallGenerateOutputForConfig, arglists)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
AssertionError: ../../v8/include$!PRODUCT_DIR/gen
```

If I checkout **nw-v0.18.8** tag in `third_party/node` directory the command does not fail, but the building process fails in a later stage, when I am running `ninja -C out_gn_arm/Release node` with the following error message:
```
leonard@ubuntu:~/nwjs/src$ ninja -C out_gn_arm/Release node
ninja: Entering directory `out_gn_arm/Release'
[628/1129] CC obj/third_party/node/deps/openssl/asm/arm-void-gas/aes/openssl.aes-armv4.o
FAILED: obj/third_party/node/deps/openssl/asm/arm-void-gas/aes/openssl.aes-armv4.o
../../third_party/llvm-build/Release+Asserts/bin/clang -MMD -MF obj/third_party/node/deps/openssl/asm/arm-void-gas/aes/openssl.aes-armv4.o.d -D_REENTRANT -DPURIFY -DOPENSSL_NO_COMP -DOPENSSL_NO_SSL3 -DOPENSSL_NO_HEARTBEATS -DOPENSSL_NO_HW -DV8_DEPRECATION_WARNINGS -D_FILE_OFFSET_BITS=64 '-DENGINESDIR="/dev/null"' -DTERMIOS '-DOPENSSLDIR="/etc/ssl"' -DNWJS_SDK -DCHROMIUM_BUILD -DCR_CLANG_REVISION=278861-1 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1 -DUSE_X11=1 -DUSE_CLIPBOARD_AURAX11=1 -DENABLE_WEBRTC=1 -DENABLE_MEDIA_ROUTER=1 -DUSE_PROPRIETARY_CODECS -DENABLE_PEPPER_CDMS -DENABLE_NOTIFICATIONS -DUSE_UDEV -DFIELDTRIAL_TESTING_ENABLED -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PDF=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_MDNS=1 -DENABLE_SERVICE_DISCOVERY=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DL_ENDIAN -DAES_ASM -DCPUID_ASM -DOPENSSL_BN_ASM_MONT -DOPENSSL_CPUID_OBJ -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DGHASH_ASM -DDSO_DLFCN -DHAVE_DLFCN_H -DUSE_LIBPCI=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DNDEBUG -DNO_UNWIND_TABLES -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../../third_party/node/deps/openssl -I../../third_party/node/deps/openssl/openssl -I../../third_party/node/deps/openssl/openssl/crypto -I../../third_party/node/deps/openssl/openssl/crypto/asn1 -I../../third_party/node/deps/openssl/openssl/crypto/evp -I../../third_party/node/deps/openssl/openssl/crypto/md2 -I../../third_party/node/deps/openssl/openssl/crypto/modes -I../../third_party/node/deps/openssl/openssl/crypto/store -I../../third_party/node/deps/openssl/openssl/include -Igen -fstack-protector --param=ssp-buffer-size=4 -Werror -pthread -fno-strict-aliasing -Wall -Wno-unused-parameter -Wno-missing-field-initializers -pipe -fPIC -fcolor-diagnostics -Xclang -load -Xclang /home/leonard/nwjs/src/third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-templates -Xclang -plugin-arg-find-bad-constructs -Xclang follow-macro-expansion -Xclang -plugin-arg-find-bad-constructs -Xclang check-ipc -g -Wno-missing-field-initializers -Wno-error=unused-command-line-argument -Wno-error=parentheses-equality -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-deprecated-register -Wno-inconsistent-missing-override -Wno-shift-negative-value -Wno-undefined-var-template -Wno-nonportable-include-path -Wno-unused-variable -target arm-linux-gnueabihf -march=armv7-a -mtune=generic-armv7-a -mfpu=neon -mfloat-abi=hard -mthumb --sysroot=/home/leonard/nwjs/src/build/linux/debian_wheezy_arm-sysroot -O2 -fno-ident -fdata-sections -ffunction-sections -fno-unwind-tables -fno-asynchronous-unwind-tables   -c ../../third_party/node/deps/openssl/asm/arm-void-gas/aes/aes-armv4.S -o obj/third_party/node/deps/openssl/asm/arm-void-gas/aes/openssl.aes-armv4.o
../../third_party/node/deps/openssl/asm/arm-void-gas/aes/aes-armv4.S:172:13: error: invalid operand for instruction
 sub r10,r3,#AES_encrypt-AES_Te @ Te
            ^
../../third_party/node/deps/openssl/asm/arm-void-gas/aes/aes-armv4.S:440:13: error: invalid operand for instruction
 sub r10,r3,#_armv4_AES_set_encrypt_key-AES_Te-1024 @ Te4
            ^
../../third_party/node/deps/openssl/asm/arm-void-gas/aes/aes-armv4.S:935:13: error: invalid operand for instruction
 sub r10,r3,#AES_decrypt-AES_Td @ Td
            ^
[630/1129] CC obj/third_party/node/deps/openssl/asm/arm-void-gas/bn/openssl.armv4-gf2m.o
FAILED: obj/third_party/node/deps/openssl/asm/arm-void-gas/bn/openssl.armv4-gf2m.o
../../third_party/llvm-build/Release+Asserts/bin/clang -MMD -MF obj/third_party/node/deps/openssl/asm/arm-void-gas/bn/openssl.armv4-gf2m.o.d -D_REENTRANT -DPURIFY -DOPENSSL_NO_COMP -DOPENSSL_NO_SSL3 -DOPENSSL_NO_HEARTBEATS -DOPENSSL_NO_HW -DV8_DEPRECATION_WARNINGS -D_FILE_OFFSET_BITS=64 '-DENGINESDIR="/dev/null"' -DTERMIOS '-DOPENSSLDIR="/etc/ssl"' -DNWJS_SDK -DCHROMIUM_BUILD -DCR_CLANG_REVISION=278861-1 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1 -DUSE_X11=1 -DUSE_CLIPBOARD_AURAX11=1 -DENABLE_WEBRTC=1 -DENABLE_MEDIA_ROUTER=1 -DUSE_PROPRIETARY_CODECS -DENABLE_PEPPER_CDMS -DENABLE_NOTIFICATIONS -DUSE_UDEV -DFIELDTRIAL_TESTING_ENABLED -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PDF=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_MDNS=1 -DENABLE_SERVICE_DISCOVERY=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DL_ENDIAN -DAES_ASM -DCPUID_ASM -DOPENSSL_BN_ASM_MONT -DOPENSSL_CPUID_OBJ -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DGHASH_ASM -DDSO_DLFCN -DHAVE_DLFCN_H -DUSE_LIBPCI=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DNDEBUG -DNO_UNWIND_TABLES -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../../third_party/node/deps/openssl -I../../third_party/node/deps/openssl/openssl -I../../third_party/node/deps/openssl/openssl/crypto -I../../third_party/node/deps/openssl/openssl/crypto/asn1 -I../../third_party/node/deps/openssl/openssl/crypto/evp -I../../third_party/node/deps/openssl/openssl/crypto/md2 -I../../third_party/node/deps/openssl/openssl/crypto/modes -I../../third_party/node/deps/openssl/openssl/crypto/store -I../../third_party/node/deps/openssl/openssl/include -Igen -fstack-protector --param=ssp-buffer-size=4 -Werror -pthread -fno-strict-aliasing -Wall -Wno-unused-parameter -Wno-missing-field-initializers -pipe -fPIC -fcolor-diagnostics -Xclang -load -Xclang /home/leonard/nwjs/src/third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-templates -Xclang -plugin-arg-find-bad-constructs -Xclang follow-macro-expansion -Xclang -plugin-arg-find-bad-constructs -Xclang check-ipc -g -Wno-missing-field-initializers -Wno-error=unused-command-line-argument -Wno-error=parentheses-equality -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-deprecated-register -Wno-inconsistent-missing-override -Wno-shift-negative-value -Wno-undefined-var-template -Wno-nonportable-include-path -Wno-unused-variable -target arm-linux-gnueabihf -march=armv7-a -mtune=generic-armv7-a -mfpu=neon -mfloat-abi=hard -mthumb --sysroot=/home/leonard/nwjs/src/build/linux/debian_wheezy_arm-sysroot -O2 -fno-ident -fdata-sections -ffunction-sections -fno-unwind-tables -fno-asynchronous-unwind-tables   -c ../../third_party/node/deps/openssl/asm/arm-void-gas/bn/armv4-gf2m.S -o obj/third_party/node/deps/openssl/asm/arm-void-gas/bn/openssl.armv4-gf2m.o
../../third_party/node/deps/openssl/asm/arm-void-gas/bn/armv4-gf2m.S:145:17: error: invalid operand for instruction
 vmov.32 d26, r2, r1
                ^
../../third_party/node/deps/openssl/asm/arm-void-gas/bn/armv4-gf2m.S:146:18: error: invalid operand for instruction
 vmov.32 d27, r12, r3
                 ^
[631/1129] CC obj/third_party/node/deps/openssl/asm/arm-void-gas/aes/openssl.bsaes-armv7.o
FAILED: obj/third_party/node/deps/openssl/asm/arm-void-gas/aes/openssl.bsaes-armv7.o
../../third_party/llvm-build/Release+Asserts/bin/clang -MMD -MF obj/third_party/node/deps/openssl/asm/arm-void-gas/aes/openssl.bsaes-armv7.o.d -D_REENTRANT -DPURIFY -DOPENSSL_NO_COMP -DOPENSSL_NO_SSL3 -DOPENSSL_NO_HEARTBEATS -DOPENSSL_NO_HW -DV8_DEPRECATION_WARNINGS -D_FILE_OFFSET_BITS=64 '-DENGINESDIR="/dev/null"' -DTERMIOS '-DOPENSSLDIR="/etc/ssl"' -DNWJS_SDK -DCHROMIUM_BUILD -DCR_CLANG_REVISION=278861-1 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1 -DUSE_X11=1 -DUSE_CLIPBOARD_AURAX11=1 -DENABLE_WEBRTC=1 -DENABLE_MEDIA_ROUTER=1 -DUSE_PROPRIETARY_CODECS -DENABLE_PEPPER_CDMS -DENABLE_NOTIFICATIONS -DUSE_UDEV -DFIELDTRIAL_TESTING_ENABLED -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PDF=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_MDNS=1 -DENABLE_SERVICE_DISCOVERY=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DL_ENDIAN -DAES_ASM -DCPUID_ASM -DOPENSSL_BN_ASM_MONT -DOPENSSL_CPUID_OBJ -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DGHASH_ASM -DDSO_DLFCN -DHAVE_DLFCN_H -DUSE_LIBPCI=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DNDEBUG -DNO_UNWIND_TABLES -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../../third_party/node/deps/openssl -I../../third_party/node/deps/openssl/openssl -I../../third_party/node/deps/openssl/openssl/crypto -I../../third_party/node/deps/openssl/openssl/crypto/asn1 -I../../third_party/node/deps/openssl/openssl/crypto/evp -I../../third_party/node/deps/openssl/openssl/crypto/md2 -I../../third_party/node/deps/openssl/openssl/crypto/modes -I../../third_party/node/deps/openssl/openssl/crypto/store -I../../third_party/node/deps/openssl/openssl/include -Igen -fstack-protector --param=ssp-buffer-size=4 -Werror -pthread -fno-strict-aliasing -Wall -Wno-unused-parameter -Wno-missing-field-initializers -pipe -fPIC -fcolor-diagnostics -Xclang -load -Xclang /home/leonard/nwjs/src/third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-templates -Xclang -plugin-arg-find-bad-constructs -Xclang follow-macro-expansion -Xclang -plugin-arg-find-bad-constructs -Xclang check-ipc -g -Wno-missing-field-initializers -Wno-error=unused-command-line-argument -Wno-error=parentheses-equality -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-deprecated-register -Wno-inconsistent-missing-override -Wno-shift-negative-value -Wno-undefined-var-template -Wno-nonportable-include-path -Wno-unused-variable -target arm-linux-gnueabihf -march=armv7-a -mtune=generic-armv7-a -mfpu=neon -mfloat-abi=hard -mthumb --sysroot=/home/leonard/nwjs/src/build/linux/debian_wheezy_arm-sysroot -O2 -fno-ident -fdata-sections -ffunction-sections -fno-unwind-tables -fno-asynchronous-unwind-tables   -c ../../third_party/node/deps/openssl/asm/arm-void-gas/aes/bsaes-armv7.S -o obj/third_party/node/deps/openssl/asm/arm-void-gas/aes/openssl.bsaes-armv7.o
../../third_party/node/deps/openssl/asm/arm-void-gas/aes/bsaes-armv7.S:86:12: error: invalid operand for instruction
 add r6,r6,#.LM0ISR-_bsaes_decrypt8
           ^
../../third_party/node/deps/openssl/asm/arm-void-gas/aes/bsaes-armv7.S:572:12: error: invalid operand for instruction
 sub r6,r6,#_bsaes_encrypt8-.LM0SR
           ^
../../third_party/node/deps/openssl/asm/arm-void-gas/aes/bsaes-armv7.S:1003:12: error: invalid operand for instruction
 sub r6,r6,#_bsaes_key_convert-.LM0
           ^
../../third_party/node/deps/openssl/asm/arm-void-gas/aes/bsaes-armv7.S:1352:14: error: invalid operand for instruction
 add r8, r6, #.LREVM0SR-.LM0 @ borrow r8
             ^
../../third_party/node/deps/openssl/asm/arm-void-gas/aes/bsaes-armv7.S:1409:14: error: invalid operand for instruction
 sub r6, r8, #.LREVM0SR-.LSR @ pass constants
             ^
[632/1129] CC obj/third_party/node/deps/openssl/openssl/engines/openssl.e_ubsec.o
ninja: build stopped: subcommand failed.
```

Do you have any idea what is causing this problem?

**Comment by jtg-gg** [comment]
@LeonardLaszlo you'll need to run gclient runhooks after you reset your git
gclient runhooks will apply patches to the sub repo

**Comment by LeonardLaszlo** [comment]
It is not that. Even if I run gclient runhooks and patches are applied I get the same error.

**Comment by jtg-gg** [comment]
@LeonardLaszlo after you reset ALL your git repo to 0.18.8
run "gclient runhooks"
python build/gyp_chromium -Goutput_dir=out_gn_arm third_party/node/node.gyp
then "ninja -C out_gn_arm/Release node"

**Comment by LeonardLaszlo** [comment]
With this tag it passed through the point where it was failing. The build didn't finish yet, but so far everything is all right.

I think the modifications in /src/third_party/node on branch nw18 after the nw-v0.18.8 tag are breaking the build, but this is just a guess.

**Comment by LeonardLaszlo** [comment]
Now I got a different error when linking Node:

http://www.text-share.com/view/7dd399a5

**Comment by LeonardLaszlo** [comment]
I am following this building guide:

https://github.com/LeonardLaszlo/nw.js-armv7-binaries/blob/master/docs/build-nwjs-v0.18.x.md

**Comment by jtg-gg** [comment]
looks like something wrong in your nwjs build, it is not the arm version
gn gen out/nw --args="$GN_ARGS"
I can't find your GN_ARGS, you'll need to use these:
is_debug=false is_component_ffmpeg=true enable_nacl=true target_cpu="arm"

**Comment by LeonardLaszlo** [comment]
I managed to build nw18. On of the changes introduced in my latest commit solved the issue, but I am not sure which one:

https://github.com/LeonardLaszlo/nw.js-armv7-binaries/commit/54bb12067eea2d74bcacbe57ae164bae45e3607f

**Comment by LeonardLaszlo** [comment]
I think the problem is caused by:

```
./build/gyp_chromium -Goutput_dir=out_gn_arm -I third_party/node/common.gypi -I third_party/node/config.gypi third_party/node/node.gyp
```

command.

I am getting the same error when I build nw19. However with nw19 the command: 

```
python build/gyp_chromium -Goutput_dir=out_gn_arm third_party/node/node.gyp
```
does not work.

**Comment by LeonardLaszlo** [comment]
I found the problem!

Running:

```
python build/gyp_chromium -Goutput_dir=out_gn_arm -I third_party/node/build/common.gypi third_party/node/node.gyp
```
instead of:
```
./build/gyp_chromium -Goutput_dir=out_gn_arm -I third_party/node/common.gypi -I third_party/node/config.gypi third_party/node/node.gyp
```

solved the error!

**Comment by LeonardLaszlo** [comment]
Offtopic:

@jtg-gg could you take a look at this issue? I am not sure if referencing you from that project sends you notifications:

https://github.com/LeonardLaszlo/nw.js-armv7-binaries/issues/7
