### ISSUE TITLE
"nw": "^0.22.3" findpath on Mac Yosemite bug

### ISSUE THREAD

**Issue by umiyo** [nwjs/nw.js#5939]
OS X Yosemite and installed by npm.

I found the findpath function source code:
```
...
  if (process.platform === 'darwin') {
    if (fs.existsSync(path.join(bin, 'Contents'))) {
      bin = path.join(bin, 'Contents', 'MacOS', 'nwjs');
    } else {
      bin = path.join(bin, 'nwjs.app', 'Contents', 'MacOS', 'nwjs');
    }
  }
...
```
After path.join, the exec path is 'node_modules/nw/nwjs/nwjs.app/Contents/MacOS/nwjs'. But using `npm install nw --save-dev`, the exec path is below:
![nw in npm](https://cloud.githubusercontent.com/assets/19969577/26618518/35a86b20-460d-11e7-8418-deb9c9149735.png)
Then I got the error:
```
{ Error: Command failed: .../node_modules/nw/nwjs/nwjs.app/Contents/MacOS/nwjs 
.../bin/sh: .../node_modules/nw/nwjs/nwjs.app/Contents/MacOS/nwjs: No such file or directory

    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
  killed: false,
  code: 127,
  signal: null,
  cmd: '.../node_modules/nw/nwjs/nwjs.app/Contents/MacOS/nwjs ...' }  /bin/sh: .../node_modules/nw/nwjs/nwjs.app/Contents/MacOS/nwjs: No such file or directory
```

**Comment by Christywl** [comment]
I can find `node_modules/nw/nwjs/nwjs.app/Contents/MacOS/nwjs`. Here is my result using `npm install nw --save-dev`:
```
WebQAs-MacBook-Pro-2:nw WebQA$ pwd
/Users/WebQA/node_modules/nw
WebQAs-MacBook-Pro-2:nw WebQA$ tree -L 2
.
├── README.md
├── bin
│   ├── autobump
│   └── nw
├── index.js
├── lib
│   ├── app_assets.js
│   └── findpath.js
├── node_modules
│   ├── chalk
│   ├── decompress
│   ├── download
│   ├── file-exists
│   ├── merge
│   ├── multimeter
│   ├── rimraf
│   ├── semver
│   └── yargs
├── nwjs
│   ├── credits.html
│   └── nwjs.app
├── package.json
└── scripts
    └── install.js

15 directories, 9 files
WebQAs-MacBook-Pro-2:bin WebQA$ cd ..
WebQAs-MacBook-Pro-2:nw WebQA$ cd nwjs/nwjs.app/Contents/MacOS/
WebQAs-MacBook-Pro-2:MacOS WebQA$ ls
nwjs
```

**Comment by Christywl** [comment]
close until there is more information.
