### ISSUE TITLE
"sudo npm install -g nw" is error

### ISSUE THREAD

**Issue by cybibo** [nwjs/nw.js#5966]
> nw@0.23.2 postinstall /usr/local/lib/node_modules/nw
> node scripts/install.js

fs.js:651
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/usr/local/lib/node_modules/nw/node_modules/array-unique/index.js'
    at Object.fs.openSync (fs.js:651:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at Object.Module._extensions..js (module.js:579:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/nw/node_modules/micromatch/lib/utils.js:13:16)
    at Module._compile (module.js:569:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nw@0.23.2 postinstall: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nw@0.23.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by Christywl** [comment]
I don't meet this error on ubuntu with `sudo npm install -g nw`.

**Comment by cybibo** [comment]
this error find on mac,i resolve。

**Comment by jensoomen** [comment]
How did you resolved it?

**Comment by webkostya** [comment]
How did you resolved it?
