### ISSUE TITLE
npm run prod error using example

### ISSUE THREAD

**Issue by nimeso** [nwjs/nw.js#6048]
Hi ya,

I followed this tutorial https://www.sitepoint.com/cross-platform-desktop-app-nw-js/
and I'm getting an error when I try and run npm  run prod

Here is my log file

```
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\program files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\nimeso\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'prod' ]
2 info using npm@5.0.3
3 info using node@v6.10.2
4 verbose run-script [ 'preprod', 'prod', 'postprod' ]
5 info lifecycle nw.js-example@1.0.0~preprod: nw.js-example@1.0.0
6 silly lifecycle nw.js-example@1.0.0~preprod: no script for preprod, continuing
7 info lifecycle nw.js-example@1.0.0~prod: nw.js-example@1.0.0
8 verbose lifecycle nw.js-example@1.0.0~prod: unsafe-perm in lifecycle true
9 verbose lifecycle nw.js-example@1.0.0~prod: PATH: C:\Users\nimeso\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;D:\test\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\wamp\bin\php\php5.4.12;D:\wamp\bin\php\php5.4.12;D:\wamp\bin\php\php5.5.12;C:\cygwin64\bin;C:\Python27;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\cURL\bin;C:\Program Files (x86)\Git\cmd;D:\XAMPP\php;C:\ProgramData\ComposerSetup\bin;D:\xamppfin\php;C:\Users\nimeso\AppData\Roaming\Composer\vendor\bin;C:\Users\nimeso\AppData\Roaming\npm;C:\Users\nimeso\AppData\Roaming\Dashlane\4.6.0.17042\bin\Firefox_Extension\{442718d9-475e-452a-b3e1-fb1ee16b8e9f}\components;C:\Users\nimeso\AppData\Roaming\Dashlane\4.6.1.18109\bin\Firefox_Extension\{442718d9-475e-452a-b3e1-fb1ee16b8e9f}\components;C:\Program Files (x86)\Skype\Phone\;D:\program files\nodejs\;D:\programfiles\AndroidLocalSettings\tools;D:\programfiles\AndroidLocalSettings\platform-tools\;D:\program files\java\bin;D:\programfiles\gradle\bin;C:\Users\nimeso\AppData\Roaming\Composer\vendor\bin;C:\Users\nimeso\AppData\Roaming\Dashlane\4.6.5.21982\bin\Firefox_Extension\{442718d9-475e-452a-b3e1-fb1ee16b8e9f}\components;C:\Users\nimeso\AppData\Roaming\Dashlane\4.6.6.23032\bin\Firefox_Extension\{442718d9-475e-452a-b3e1-fb1ee16b8e9f}\components;C:\Users\nimeso\AppData\Roaming\npm;C:\Users\nimeso\AppData\Roaming\Dashlane\4.8.3.33472\bin\Firefox_Extension\{442718d9-475e-452a-b3e1-fb1ee16b8e9f}\components;C:\Users\nimeso\AppData\Roaming\Dashlane\4.8.3.33472\ucrt
10 verbose lifecycle nw.js-example@1.0.0~prod: CWD: D:\test
11 silly lifecycle nw.js-example@1.0.0~prod: Args: [ '/d /s /c',
11 silly lifecycle   'nwbuild --platforms win32,win64 --buildDir dist/ src/' ]
12 silly lifecycle nw.js-example@1.0.0~prod: Returned: code: 1  signal: null
13 info lifecycle nw.js-example@1.0.0~prod: Failed to exec prod script
14 verbose stack Error: nw.js-example@1.0.0 prod: `nwbuild --platforms win32,win64 --buildDir dist/ src/`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\nimeso\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\nimeso\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid nw.js-example@1.0.0
16 verbose cwd D:\test
17 verbose Windows_NT 10.0.10586
18 verbose argv "D:\\program files\\nodejs\\node.exe" "C:\\Users\\nimeso\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "prod"
19 verbose node v6.10.2
20 verbose npm  v5.0.3
21 error code ELIFECYCLE
22 error errno 1
23 error nw.js-example@1.0.0 prod: `nwbuild --platforms win32,win64 --buildDir dist/ src/`
23 error Exit status 1
24 error Failed at the nw.js-example@1.0.0 prod script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by Christywl** [comment]
I try the [example](https://github.com/sitepoint-editors/nw.js-examples/) , `npm run prod` works fine for me for all platforms, except that `osx64 `failed since another error. I change the `nw `and `nw-builder` version in `package.json` to the latest.

**Comment by Christywl** [comment]
close until there is more information.
