### ISSUE TITLE
error in async function will cause crash, any sugguest to prevent from crash

### ISSUE THREAD

**Issue by chatcan** [nwjs/nw.js#6153]
```json
{
  "main": "index.html",
  "name": "canhuang2",
  "appname": "canhuang2",
  "version": "1.0.0",
  "window": {
    "title": "v1.0.0",
    "toolbar": true,
    "width": 800,
    "height": 800,
    "frame": true
  }
}
```

```html
<!DOCTYPE html>
<html lang="zh-CN">

<head>
  <meta charset="utf-8">
</head>

<body>
  <div id="container" class="container"></div>
  <script src="index.js"></script>
</body>

</html>
```

```
// index.js
require('core.js')
```

```
// core.js
setTimeout(() => {
  b()
}, 3000)

window.addEventListener('error', (event) => {
  console.log(event)
})
```

since in  17.6  window.addEventListener could prevent app from crash
but in 24.4 althought window.addEventListener could catch the error, app crash

any sugguest

```
ReferenceError: b is not defined
    at Timeout.setTimeout [as _onTimeout] (/Users/can/main/testtest/core.js:3:3)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
Error: async hook stack has become corrupted (actual: 2, expected: 3)
 1: node::Environment::AsyncHooks::pop_ids(double) [/Users/can/nw23/nwjs.app/Contents/Versions/59.0.3071.115/nwjs Framework.framework/libnode.dylib]
 2: node::AsyncWrap::MakeCallback(v8::Local<v8::Function>, int, v8::Local<v8::Value>*) [/Users/can/nw23/nwjs.app/Contents/Versions/59.0.3071.115/nwjs Framework.framework/libnode.dylib]
 3: node::(anonymous namespace)::TimerWrap::OnTimeout(uv_timer_s*) [/Users/can/nw23/nwjs.app/Contents/Versions/59.0.3071.115/nwjs Framework.framework/libnode.dylib]
 4: uv__run_timers [/Users/can/nw23/nwjs.app/Contents/Versions/59.0.3071.115/nwjs Framework.framework/libnode.dylib]
 5: uv_run [/Users/can/nw23/nwjs.app/Contents/Versions/59.0.3071.115/nwjs Framework.framework/libnode.dylib]
 6: v8::internal::InterpreterDispatchDescriptor::InitializePlatformSpecific(v8::internal::CallInterfaceDescriptorData*) [/Users/can/nw23/nwjs.app/Contents/Versions/59.0.3071.115/nwjs Framework.framework/Versions/A/nwjs Framework]
 7: g_uv_runloop_once [/Users/can/nw23/nwjs.app/Contents/Versions/59.0.3071.115/nwjs Framework.framework/libnode.dylib]
 8: v8::internal::InterpreterDispatchDescriptor::InitializePlatformSpecific(v8::internal::CallInterfaceDescriptorData*) [/Users/can/nw23/nwjs.app/Contents/Versions/59.0.3071.115/nwjs Framework.framework/Versions/A/nwjs Framework]
 9: v8::internal::InterpreterDispatchDescriptor::InitializePlatformSpecific(v8::internal::CallInterfaceDescriptorData*) [/Users/can/nw23/nwjs.app/Contents/Versions/59.0.3071.115/nwjs Framework.framework/Versions/A/nwjs Framework]
10: v8::internal::InterpreterDispatchDescriptor::InitializePlatformSpecific(v8::internal::CallInterfaceDescriptorData*) [/Users/can/nw23/nwjs.app/Contents/Versions/59.0.3071.115/nwjs Framework.framework/Versions/A/nwjs Framework]
11: v8::internal::InterpreterDispatchDescriptor::InitializePlatformSpecific(v8::internal::CallInterfaceDescriptorData*) [/Users/can/nw23/nwjs.app/Contents/Versions/59.0.3071.115/nwjs Framework.framework/Versions/A/nwjs Framework]
12: v8::internal::InterpreterDispatchDescriptor::InitializePlatformSpecific(v8::internal::CallInterfaceDescriptorData*) [/Users/can/nw23/nwjs.app/Contents/Versions/59.0.3071.115/nwjs Framework.framework/Versions/A/nwjs Framework]
13: v8::internal::InterpreterDispatchDescriptor::InitializePlatformSpecific(v8::internal::CallInterfaceDescriptorData*) [/Users/can/nw23/nwjs.app/Contents/Versions/59.0.3071.115/nwjs Framework.framework/Versions/A/nwjs Framework]
14: v8::internal::InterpreterDispatchDescriptor::InitializePlatformSpecific(v8::internal::CallInterfaceDescriptorData*) [/Users/can/nw23/nwjs.app/Contents/Versions/59.0.3071.115/nwjs Framework.framework/Versions/A/nwjs Framework]
15: v8::internal::InterpreterDispatchDescriptor::InitializePlatformSpecific(v8::internal::CallInterfaceDescriptorData*) [/Users/can/nw23/nwjs.app/Contents/Versions/59.0.3071.115/nwjs Framework.framework/Versions/A/nwjs Framework]
16: ChromeMain [/Users/can/nw23/nwjs.app/Contents/Versions/59.0.3071.115/nwjs Framework.framework/Versions/A/nwjs Framework]
17: main [/Users/can/nw23/nwjs.app/Contents/Versions/59.0.3071.115/nwjs Helper.app/Contents/MacOS/nwjs Helper]
18: start [/usr/lib/system/libdyld.dylib]
```

**Comment by Christywl** [comment]
I can reproduce this issue on Linux with nwjs-sdk-v0.25.0. 
On nwjs v0.17.6, window.addEventListener could prevent app from crash.

**Comment by lin-chao** [comment]
find a way to prevent crash

```javascript
process.on('uncaughtException', (err) => {
  console.error(err)

})

```

**Comment by rogerwang** [comment]
Exceptions thrown in Node should be caught with Node. Thanks.

**Comment by rogerwang** [comment]
Reopen and will add a way to prevent the crash when there is no `uncaughtException` set.

**Comment by cTn-dev** [comment]
Indeed this would make the most sense, are you planning to just prevent the crash.
When it comes to throwing error inside a timer callback, crashing the node worker vs not crashing it by throwing the error outside of the timer, is an expected behavior?

Seems i will have to hook up the uncaughtException handler and look a little bit more into whats happening.

**Comment by rogerwang** [comment]
It will be handled the same when there is an uncaught exception in browser.

**Comment by rogerwang** [comment]
@cTn-dev this is not related to `--enable-node-worker`. Similar case crashes in normal mode too.

**Comment by cTn-dev** [comment]
Aaah, i see!
