### ISSUE TITLE
When using the third-party module [require ('ffi')], the program hangs

### ISSUE THREAD

**Issue by vchenpeng** [nwjs/nw.js#6177]
When I use binary compiled dll, run the application immediately crash, but in the console directly in the command line to run the code, you can run normally.

The specific code runs here:
```
var FFI = require('ffi');    //app hangs up here
var user32 = new FFI.Library('user32', {
  'MessageBoxW':  ['int32', ['int32', 'string', 'string', 'int32']]
});
```
debug.log file content:
[0927/090034.189:ERROR:http_transport_win.cc(170)] WinHttpCrackUrl: The URL does not use an identifiable protocol  (0x2ee6)
[0927/091939.954:ERROR:http_transport_win.cc(170)] WinHttpCrackUrl: The URL does not use an identifiable protocol  (0x2ee6)

Node: v8.4.0(32-bit)
NWJS Version : v0.25.3(32-bit)
Operating System : windows 7(64-bit)

**Comment by Christywl** [comment]
Could you please provide the steps to reproduce it?

**Comment by vchenpeng** [comment]
Compiling ffi and ref is successful
```
..\app\dkq\node_modules\ffi>node-gyp rebuild --target=0.25.3 -arch=ia32 --msvs_version=2015
..\app\dkq\node_modules\ref>node-gyp rebuild --target=0.25.3 -arch=ia32 --msvs_version=2015

//The above two lines are successful
```
next step:
In the console，run this code is ok:
```
let FFI = require('ffi');   //in windows CMD
```

But after packing with NW.js，When I run this line of code, the application hangs up
```
let FFI = require('ffi');    //run packing myapp.exe,and press F12 in console 
```

**Comment by Christywl** [comment]
You should rebuild ffi and ref with **nw-gyp**, see http://docs.nwjs.io/en/latest/For%20Users/Advanced/Use%20Native%20Node%20Modules/#nw-gyp.

I try to rebuild ffi module with nw-gyp, but failed with an error, similar to  [node-ffi issue](https://github.com/node-ffi/node-ffi/issues/411) :
```
C:\nwjs\bugs\6177\nw-demo\node_modules\ffi>nw-gyp rebuild --target=0.25.4

...
...
..\src\ffi.cc(126): error C2664: 'v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>,v8::Local<v8::Value>,v8::
Local<v8::Value>,v8::PropertyAttribute)': cannot convert argument 3 from 'v8::PropertyAttribute' to 'v8::Local<v8::Valu
e>' [C:\nwjs\bugs\6177\nw-demo\node_modules\ffi\build\ffi_bindings.vcxproj]
  ..\src\ffi.cc(126): note: No user-defined-conversion operator available that can perform this conversion, or the oper
  ator cannot be called
..\src\ffi.cc(132): error C2664: 'v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>,v8::Local<v8::Value>,v8::
Local<v8::Value>,v8::PropertyAttribute)': cannot convert argument 3 from 'v8::PropertyAttribute' to 'v8::Local<v8::Valu
e>' [C:\nwjs\bugs\6177\nw-demo\node_modules\ffi\build\ffi_bindings.vcxproj]
  ..\src\ffi.cc(132): note: No user-defined-conversion operator available that can perform this conversion, or the oper
  ator cannot be called
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\WebQA\AppData\Roaming\npm\node_modules\nw-gyp\lib\build.js:294:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\WebQA\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\bin\\nw-gyp.js" "rebuild" "--target=0.25.4"
gyp ERR! cwd C:\nwjs\bugs\6177\nw-demo\node_modules\ffi
gyp ERR! node -v v7.8.0
gyp ERR! nw-gyp -v v3.4.0
gyp ERR! not ok
```
ref module works fine after nw-gyp rebuild.

**Comment by rogerwang** [comment]
close until more information is available.
