### ISSUE TITLE
nwjs 0.30.0 build fails - No such file or directory: adapter.mojom.js

### ISSUE THREAD

**Issue by josendf** [nwjs/nw.js#6579]
NWJS Version : 0.30.0

Operating System : Windows

nwjs 0.30.0 build fails:

`
No such file or directory: '..\\..\\outst\\nw\\gen\\device\\bluetooth\\public\\interfaces\\adapter.mojom.js'
`

On commit [fa93b142ca746c85c0714be0f2e1eee194f65697](https://github.com/nwjs/chromium.src/commit/fa93b142ca746c85c0714be0f2e1eee194f65697) upstream modified `chrome/browser/browser_resources.grd`, changing the location of the following files:

```
adapter.mojom.js, 
device.mojom.js
uuid.mojom.js
```

The file `chrome/browser/nwjs_resources.grd` should be updated to reflect this changes.

Thank you,

```
ninja: Entering directory `src/outst/nw'
[20787/35838] ACTION //chrome/browser:resources_grit(//build/toolchain/win:win_clang_x64)
FAILED: gen/chrome/resources_stamp.d.stamp gen/chrome/grit/browser_resources.h gen/chrome/browser_resources.pak gen/chrome/browser_resources.pak.info
C:/depot_tools/win_tools-2_7_6_bin/python/bin/python.exe ../../tools/grit/grit.py -i ../../chrome/browser/nwjs_resources.grd build -o gen/chrome --depdir . --depfile gen/chrome/resources_stamp.d --write-only-new=1 --depend-on-stamp -D _chromium -E CHROMIUM_BUILD=chromium -D toolkit_views -D use_aura -D enable_app_list=false -D enable_background_mode=true -D enable_background_contents=true -D enable_extensions=true -D enable_google_now=false -D enable_hangout_services_extension=false -D enable_plugins=true -D enable_print_preview=true -D enable_printing=true -D enable_service_discovery=true -D enable_webrtc=true -D enable_vr=true -D mac_views_browser=false -D safe_browsing_mode=0 -D optimize_webui=true -E additional_modules_list_file=gen/chrome/browser/internal/additional_modules_list.txt -E root_gen_dir=gen -f ../../tools/gritsettings/resource_ids -p ../../tools/gritsettings/startup_resources_win.txt --assert-file-list=obj/chrome/browser/resources_expected_outputs.txt
Error processing node <?xml version="1.0" encoding="UTF-8"?>
<include compress="gzip" file="${root_gen_dir}\device\bluetooth\public\interfaces\adapter.mojom.js" name="IDR_BLUETOOTH_ADAPTER_MOJO_JS" type="BINDATA" use_base_dir="false" />
Traceback (most recent call last):
  File "../../tools/grit/grit.py", line 15, in <module>
	grit.grit_runner.Main(sys.argv[1:])
  File "D:\build\nw30_win64\node-webkit\src\tools\grit\grit\grit_runner.py", line 249, in Main
	toolobject.Run(options, args[1:])
  File "D:\build\nw30_win64\node-webkit\src\tools\grit\grit\tool\build.py", line 256, in Run
	self.Process()
  File "D:\build\nw30_win64\node-webkit\src\tools\grit\grit\tool\build.py", line 397, in Process
	self.ProcessNode(self.res, output, outfile)
  File "D:\build\nw30_win64\node-webkit\src\tools\grit\grit\tool\build.py", line 320, in ProcessNode
	formatted = formatter(node, output_node.GetLanguage(), output_dir=base_dir)
  File "D:\build\nw30_win64\node-webkit\src\tools\grit\grit\format\data_pack.py", line 83, in Format
	value = node.GetDataPackValue(lang, UTF8)
  File "D:\build\nw30_win64\node-webkit\src\tools\grit\grit\node\include.py", line 86, in GetDataPackValue
	data = util.ReadFile(filename, util.BINARY)
  File "D:\build\nw30_win64\node-webkit\src\tools\grit\grit\util.py", line 207, in ReadFile
	with open(filename, mode) as f:
IOError: [Errno 2] No such file or directory: u'..\\..\\outst\\nw\\gen\\device\\bluetooth\\public\\interfaces\\adapter.mojom.js'
[20796/35838] CXX obj/v8/v8_base/objects.obj
ninja: build stopped: subcommand failed.

```

**Comment by rogerwang** [comment]
Thanks for reporting. This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
