### ISSUE TITLE
"Error: Could not locate the bindings file" when using ffi/ref 

### ISSUE THREAD

**Issue by Devorlin** [nwjs/nw.js#6660]
======== environment ========
--Operating System : win7 sp1 x64
--NWJS version: 0.30.5 win x64
--nodejs version: 10.1.0 x64
--python2.7, msvs_tools 2015
======== issues========
i allready use **npm** install node-gyp,nw-gyp,ffi,ref with **--save**
then try to use cmd: **nw-gyp build --target=0.30.5** build ref,ffi in their dirs , and all return info ok!
so i begin use the demo code in my app.js
```js
       var ffi = require('ffi');
       // You can also access just functions in the current process by passing a null
	var current = ffi.Library(null, {
              'atoi': [ 'int', [ 'string' ] ]
	});
	console.log( current.atoi('1234')); // 1234
```
and then run in nw, but caught this error in dev tools
````js
Uncaught Error: Could not locate the bindings file. Tried:
 → C:\Users\Administrator.USER-20180305LN\Desktop\nwjs-sdk\zhsb\node_modules\ref\build\binding.node
 → C:\Users\Administrator.USER-20180305LN\Desktop\nwjs-sdk\zhsb\node_modules\ref\build\Debug\binding.node
 → C:\Users\Administrator.USER-20180305LN\Desktop\nwjs-sdk\zhsb\node_modules\ref\build\Release\binding.node
 → C:\Users\Administrator.USER-20180305LN\Desktop\nwjs-sdk\zhsb\node_modules\ref\out\Debug\binding.node
 → C:\Users\Administrator.USER-20180305LN\Desktop\nwjs-sdk\zhsb\node_modules\ref\Debug\binding.node
 → C:\Users\Administrator.USER-20180305LN\Desktop\nwjs-sdk\zhsb\node_modules\ref\out\Release\binding.node
 → C:\Users\Administrator.USER-20180305LN\Desktop\nwjs-sdk\zhsb\node_modules\ref\Release\binding.node
 → C:\Users\Administrator.USER-20180305LN\Desktop\nwjs-sdk\zhsb\node_modules\ref\build\default\binding.node
 → C:\Users\Administrator.USER-20180305LN\Desktop\nwjs-sdk\zhsb\node_modules\ref\compiled\10.1.0\win32\x64\binding.node
    at bindings (C:\Users\Administrator.USER-20180305LN\Desktop\nwjs-sdk\zhsb\node_modules\bindings\bindings.js:88:9)
    at Object.<anonymous> (C:\Users\Administrator.USER-20180305LN\Desktop\nwjs-sdk\zhsb\node_modules\ref\lib\ref.js:5:47)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:719:10)
    at Module.load (internal/modules/cjs/loader.js:613:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:552:12)
    at Function.Module._load (internal/modules/cjs/loader.js:544:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\Administrator.USER-20180305LN\Desktop\nwjs-sdk\zhsb\node_modules\ffi\lib\ffi.js:6:11)
````

this is my first time use nwjs and node-ffi, 
i have read many docs on the net and try to fixed it, 
may be i miss some operate, 
please help me analyze and resolve this problem,
thks!

### Expected behavior

is the nw-gyp can't not build ffi on version of nw-0.30.5 ?
i check the build dir and there has .node file in build>Release>binding.node
i try to use npm rebuild but it does'n work 

### How to reproduce
some step:
1. open cmd in app dir
2. use **npm install ffi ref --save**
3. use **nw-gyp configure --target=0.30.5 --arch=x64** in app\node_modules\ref
    and try to build with **nw-gyp build --target=0.30.5** , return info ok!
4. the same as step3 in in app\node_modules\ffi , also return info ok!
5. write js code in app.js(load in index.html when windows open)
6. check dev tools find this error

some code in package.json
````json
{
  "main": "index.html",
  "name": "demo",
  "nodejs": true,
  "node-main": "main.js",
  "inject_js_start": "app.js",
  "dependencies": {
    "ffi": "^2.2.0",
    "ref": "^1.3.5"
  }
}

**Comment by Devorlin** [comment]
that is node-ffi's issues, i was give up use it and make a DIY addon to replace
