### ISSUE TITLE
send a http request with proxy doesn`t work in version 0.32

### ISSUE THREAD

**Issue by jiangcl714** [nwjs/nw.js#6760]
1. send a s3 get  request with proxy-agent.the code is like : 
http.request(options,callback), option.agent is a proxyAgent.

 the following exception raised(172.19.64.37 is the proxy server):
 { NetworkingError: connect EACCES 172.19.64.37:8080
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1162:14)
  message: 'connect EACCES 172.19.64.37:8080',
  errno: 'EACCES',
  code: 'NetworkingError',
  syscall: 'connect',
  address: '172.19.64.37',
  port: 8080,
  region: '',
  hostname: 'obs.myhwclouds.com',
  retryable: true,
  time: 2018-08-09T01:49:22.394Z }
NetworkingError: connect EACCES 172.19.64.37:8080
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1162:14)

Same code run in pure nodejs command env,and it works.

2. remove the proxy-agent parameter,call http.request(options),options.host is the proxy ip,the problem is still there. and it works in pure nodejs command too.

when it failed. there are no http package been sended in wireshark.

**Comment by jiangcl714** [comment]
it seems the company security policy cause this issue，close it
