### ISSUE TITLE
Error: A dynamic link library (DLL) initialization routine failed. (..)\node_modules\usb\src\binding\usb_bindings.node

### ISSUE THREAD

**Issue by chipimix** [nwjs/nw.js#6769]
Hi!

I'm trying to use [this node_module](https://github.com/sandeepmistry/node-sensortag) with nwjs. My code works when I run it on node.js.
I'm working on a windows10 x64 OS and I've followed [this non-LTS Releases doc](http://docs.nwjs.io/en/latest/For%20Users/Advanced/Use%20Native%20Node%20Modules/):
As such, I run the following commands with no issues:
```
npm install -g nw-gyp  
set PYTHON=C:\Python27\python.exe 
set npm_config_target=0.32.3
set npm_config_arch=x64
set npm_config_runtime=node-webkit
set npm_config_build_from_source=true
set npm_config_node_gyp=C:\Users\DanielRocha\AppData\Roaming\npm\node_modules\nw-gyp\bin\nw-gyp.js
npm install sensortag --msvs_version=2015
```
package.json contents:
```
{
  "name": "helloworld",
  "main": "helloSensortag.html",
  "window": {
    "toolbar": true
  },
  "dependencies": {
    "sensortag": "^1.3.0"
  }
}

```
I run the command` nw.exe .` in the correct directory, with no issue.
However, upon page inspection, I get the following error on the console: 

```
Uncaught Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\DanielRocha\Desktop\ibeb\helloNWJS\node_modules\usb\src\binding\usb_bindings.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:760:18)
    at Module.load (internal/modules/cjs/loader.js:623:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:562:12)
    at Function.Module._load (internal/modules/cjs/loader.js:554:3)
    at Module.require (internal/modules/cjs/loader.js:661:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\DanielRocha\Desktop\ibeb\helloNWJS\node_modules\usb\usb.js:5:38)
    at Module._compile (internal/modules/cjs/loader.js:713:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:730:10)
    at Module.load (internal/modules/cjs/loader.js:623:32)
```
I have checked the file C:\Users\DanielRocha\Desktop\ibeb\helloNWJS\node_modules\usb\src\binding\usb_bindings.node exists and is human-incomprehensible hex code thingamabob.
 🤔 
Does anyone have a clue what am I doing wrong?

Thanks in advance!🙇

**Comment by rogerwang** [comment]
Could you please try `--msvs_version=2017`?

**Comment by chipimix** [comment]
I did! 
Did not work 😞

**Comment by rogerwang** [comment]
Could you please provide a full sample (not code snippets) so we can reproduce?

**Comment by chipimix** [comment]
Sure!
Basically i'm trying to run [this script](https://github.com/sandeepmistry/node-sensortag/blob/master/test-discover.js) on the front end HTML.
I don't know how to get this working on nwjs yet but I did manage to get it working on electron:
At first I encontered a similar error:
```
Uncaught Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\DanielRocha\Desktop\electronSensorTag1\node_modules\usb\src\binding\usb_bindings.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\DanielRocha\Desktop\electronSensorTag1\node_modules\usb\usb.js:5:38)
    at Object.<anonymous> (C:\Users\DanielRocha\Desktop\electronSensorTag1\node_modules\usb\usb.js:417:3)
```

I then ran the command `./node_modules/.bin/electron-rebuild.cmd` [as advised here](https://github.com/electron/electron/blob/v0.37.2/docs/tutorial/using-native-node-modules.md#using-native-node-modules) on my project directory and now the DLL error is gone!

Thanks!

**Comment by rogerwang** [comment]
It seems you didn't set `npm_config_target_arch` as in the document. The module `usb_bindings.node` can be loaded directly here without any issues. I didn't try `sensortag` though because you didn't provide a ready-to-use sample.

**Comment by rogerwang** [comment]
<img width="481" alt="bug" src="https://user-images.githubusercontent.com/165401/44614236-844a1680-a853-11e8-9ed7-1d6440d6fe43.png">
