### ISSUE TITLE
iohook - Uncaught Error: Module did not self-register.

### ISSUE THREAD

**Issue by Erdong3ye** [nwjs/nw.js#6790]
NWJS Version :0.30.2，0.30.5，0.33.2；
Operating System :win10-64;

I tried installing iohook in the SDK package of nw.js using "npm install iohook -- save" and successfully loaded iohook - v0.2.0. But after double clicking nw.exe, the console output the following error:

Uncaught Error: Module did not self-register.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:760:18)
    at Module.load (internal/modules/cjs/loader.js:623:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:562:12)
    at Function.Module._load (internal/modules/cjs/loader.js:554:3)
    at Module.require (internal/modules/cjs/loader.js:661:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\E\nwjs-sdk-v0.33.2-win-x64-1\node_modules\iohook\index.js:16:21)
    at Module._compile (internal/modules/cjs/loader.js:713:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:730:10)
    at Module.load (internal/modules/cjs/loader.js:623:32)

The following is the error of my code and interface：
![1](https://user-images.githubusercontent.com/31117941/45417623-3176b880-b6b5-11e8-98c1-4c3b9a2e3993.png)

Thank you very much for your help.

**Comment by rogerwang** [comment]
I think it is or depends on native modules? Please check http://docs.nwjs.io/en/latest/For%20Users/Advanced/Use%20Native%20Node%20Modules/
