### ISSUE TITLE
npm install nw error

### ISSUE THREAD

**Issue by six-666** [nwjs/nw.js#6843]
```
Downloading nw to /root/.nvm/versions/node/v8.12.0/lib/node_modules/nw_tmp
Copying /root/.nvm/versions/node/v8.12.0/lib/node_modules/nw_tmp/_nw@0.34.1@nw to /root/.nvm/versions/node/v8.12.0/lib/node_modules/nw
Installing nw's dependencies to /root/.nvm/versions/node/v8.12.0/lib/node_modules/nw/node_modules
[1/9] merge@^1.2.0 installed at node_modules/_merge@1.2.1@merge
[2/9] file-exists@^2.0.0 installed at node_modules/_file-exists@2.0.0@file-exists
[3/9] semver@^5.1.0 installed at node_modules/_semver@5.6.0@semver
[4/9] multimeter@^0.1.1 installed at node_modules/_multimeter@0.1.1@multimeter
[5/9] chalk@~1.1.3 installed at node_modules/_chalk@1.1.3@chalk
[6/9] rimraf@^2.2.8 installed at node_modules/_rimraf@2.6.2@rimraf
[7/9] yargs@^3.2.1 installed at node_modules/_yargs@3.32.0@yargs
[8/9] download@^5.0.3 installed at node_modules/_download@5.0.3@download
[9/9] decompress@^3.0.0 installed at node_modules/_decompress@3.0.0@decompress
execute post install 1 scripts...
[1/1] scripts.postinstall nw@0.34.1 run "node scripts/install.js"
Response code 404 (Not Found)
Install fail! Error: post install error, please remove node_modules before retry!
Run "sh -c node scripts/install.js" error, exit code 1
Error: post install error, please remove node_modules before retry!
Run "sh -c node scripts/install.js" error, exit code 1
    at ChildProcess.proc.on.code (/root/.nvm/versions/node/v8.12.0/lib/node_modules/cnpm/node_modules/runscript/index.js:74:21)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

node: v8.12.0
npm: 6.4.1

**Comment by QQ-ing** [comment]
+1
