### ISSUE TITLE
Error rebuilding with nw-gyp 'can't open file: [Errno 2] No such file or directory'

### ISSUE THREAD

**Issue by tonetechnician** [nwjs/nw.js#7002]
Hey there, 

NWJS Version : 0.36.3
Operating System : Windows 10 x64

I'm hoping someone has experienced something similar and can help me. I'm trying to install the cap package using nw-gyp. Firstly, when I install cap I run into the error that the "dll could not be initialized in module.js". In order to fix this I have been referencing this issue [#48](https://github.com/mscdex/cap/issues/48).

Now, after replacing web_delay_load_hook.cc and rebuilding nw-gyp to my nwjs version, I keep running into an error where nw-gyp can't find a directory as it is building. Here is the debug output. I have starred out my username. 

I doubt it's an issue, but I have my username as two words seperated by a space i.e "Late Game" 

gyp info it worked if it ends with ok
gyp info using nw-gyp@3.6.3
gyp info using node@8.11.3 | win32 | x64
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Users\\### ###\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\git-repos\\repo\\node_modules\\cap\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\### ###\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\### ###\\.nw-gyp\\0.36.3\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\### ###\\.nw-gyp\\0.36.3',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\### ###\\AppData\\Roaming\\npm\\node_modules\\nw-gyp',
gyp info spawn args   '-Dnode_lib_file="C:\\Users\\### ###\\.nw-gyp\\0.36.3\\<(target_arch)\\node.lib"',
gyp info spawn args   '-Dnw_lib_file="C:\\Users\\### ###\\.nw-gyp\\0.36.3\\<(target_arch)\\nw.lib"',
gyp info spawn args   '-Dmodule_root_dir=D:\\git-repos\\repo\\node_modules\\cap',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '-Dv13=1',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\git-repos\\repo\\node_modules\\cap\\build',
gyp info spawn args   '-Goutput_dir=.' ]
C:\Python27\python.exe: can't open file 'C:\Users\###': [Errno 2] No such file or directory
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\### ###\AppData\Roaming\npm\node_modules\nw-gyp\lib\configure.js:359:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "D:\\coding\\nodejs\\node.exe" "C:\\Users\\### ###\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\bin\\nw-gyp.js" "rebuild" "--target=0.36.3"
gyp ERR! cwd D:\git-repos\repo\node_modules\cap
gyp ERR! node -v v8.11.3
gyp ERR! nw-gyp -v v3.6.3
gyp ERR! not ok

### How to reproduce

1. I installed nwjs using 

`npm install nw nwjs_build_type=sdk`

2. Then I installed [cap](https://www.npmjs.com/package/cap) with all the prerequisites for windows. I.e windows-build-tools + winPCAP. 

3. I then am unable to run my nwjs project because of the "dll could not be initialized in module.js".

4. Now I installed nw-gyp using 

`npm -g install nw-gyp`

5. Replaced the web_delay_load_hook.cc in the npm node_modules for node-gyp. 

6. Then I try rebuild the cap package within the cap directory using 

`nw-gyp rebuild --target=0.36.3` 

and am given the error shown above. 

Any help would be greatly appreciated! Been battling with about a day now.

All the best,

**Comment by tonetechnician** [comment]
Have been doing some more searching and it seems to be the same problem as this [#116](https://github.com/nwjs/nw-gyp/issues/116)
