### ISSUE TITLE
Windows 10 component=shared_library "redeclared without 'dllimport' attribute" Error

### ISSUE THREAD

**Issue by zelid** [nwjs/nw.js#7067]
I'm building on Windows 10 from latest sources using these commands:

```
set DEPOT_TOOLS_WIN_TOOLCHAIN=0
set GYP_DEFINES="is_debug=true is_component_build=true target_cpu=x64 target_arch=x64"
set GYP_CHROMIUM_NO_ACTION=0
gn gen out/nw
```

On linking the build fails with errors:

```
PS E:\dev\nwjs\src> ninja -C out/nw nwjs
ninja: Entering directory `out/nw'
[23705/36432] CXX obj/chrome/browser/browser/chrome_content_browser_client.obj
FAILED: obj/chrome/browser/browser/chrome_content_browser_client.obj
../../third_party/llvm-build/Release+Asserts/bin/clang-cl.exe /nologo /showIncludes  "-imsvcC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-imsvcC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-imsvcC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-imsvcC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-imsvcC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-imsvcC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-imsvcC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-imsvcC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -DZLIB_CONST -DUSE_AURA=1 -DNO_TCMALLOC -DNWJS_SDK -DCHROMIUM_BUILD "-DCR_CLANG_REVISION=\"351477-1\"" -D_HAS_NODISCARD -D_HAS_EXCEPTIONS=0 -DCOMPONENT_BUILD -D__STD_C -D_CRT_RAND_S -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_DEPRECATE -D_ATL_NO_OPENGL -D_WINDOWS -DCERT_CHAIN_PARA_HAS_EXTRA_FIELDS -DPSAPI_VERSION=2 -DWIN32 -D_SECURE_ATL -D_USING_V110_SDK71_ -DWINAPI_FAMILY=WINAPI_FAMILY_DESKTOP_APP -DWIN32_LEAN_AND_MEAN -DNOMINMAX -D_UNICODE -DUNICODE -DNTDDI_VERSION=0x0A000002 -D_WIN32_WINNT=0x0A00 -DWINVER=0x0A00 -D_DEBUG -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DWTF_USE_DYNAMIC_ANNOTATIONS=1 -D_HAS_ITERATOR_DEBUGGING=0 -DWEBP_EXTERN=extern -DUSE_EGL -DTOOLKIT_VIEWS=1 -DEXPAT_RELATIVE_PATH -DSYNC_PASSWORD_REUSE_DETECTION_ENABLED -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DUSE_CHROMIUM_ICU=1 -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DUCHAR_TYPE=wchar_t -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DPROTOBUF_USE_DLLS -DBORINGSSL_SHARED_LIBRARY -DWEBRTC_NON_STATIC_TRACE_EVENT_HANDLERS=0 -DWEBRTC_CHROMIUM_BUILD -DWEBRTC_WIN -DABSL_ALLOCATOR_NOTHROW=1 -DNO_MAIN_THREAD_WRAPPING -DV8_USE_EXTERNAL_STARTUP_DATA -DSK_HAS_PNG_LIBRARY -DSK_HAS_WEBP_LIBRARY -DSK_HAS_JPEG_LIBRARY -DSKIA_DLL -DGR_GL_IGNORE_ES3_MSAA=0 -DSKCMS_API=__declspec(dllexport) -DSK_SUPPORT_GPU=1 "-DSK_GPU_WORKAROUNDS_HEADER=\"gpu/config/gpu_driver_bug_workaround_autogen.h\"" -DGR_GL_FUNCTION_TYPE=__stdcall -DLEVELDB_PLATFORM_CHROMIUM=1 -DDeleteFile=DeleteFileW -DLEVELDB_PLATFORM_CHROMIUM=1 -DLEVELDB_SHARED_LIBRARY -DUSING_V8_SHARED -DV8_SHARED -DUSING_V8_PLATFORM_SHARED -DV8_ENABLE_CHECKS -DV8_DEPRECATION_WARNINGS -DPERFETTO_BUILD_WITH_EMBEDDER -DPERFETTO_BUILD_WITH_CHROMIUM -DPERFETTO_SHARED_LIBRARY -DPERFETTO_FORCE_DLOG=0 "-DI18N_ADDRESS_VALIDATION_DATA_URL=\"https://chromium-i18n.appspot.com/ssl-aggregate-address/\"" -DAUDIO_PROCESSING_IN_AUDIO_SERVICE -DSECURITY_WIN32 -DHUNSPELL_STATIC -DHUNSPELL_CHROME_CLIENT -DUSE_HUNSPELL -DVR_USE_COMMAND_BUFFER -DGL_GLEXT_PROTOTYPES -I../.. -Igen -I../../third_party/libwebp/src -I../../third_party/wtl/include -I../../third_party/khronos -I../../gpu -I../../third_party/libyuv/include -I../../third_party/jsoncpp/overrides/include -I../../third_party/jsoncpp/source/include -I../../third_party/ced/src -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -I../../third_party/protobuf/src -Igen/protoc_out -I../../third_party/protobuf/src -I../../third_party/boringssl/src/include -I../../third_party/webrtc_overrides -I../../third_party/webrtc -Igen/third_party/webrtc -I../../third_party/abseil-cpp -I../../skia/config -I../../skia/ext -I../../third_party/skia/include/c -I../../third_party/skia/include/config -I../../third_party/skia/include/core -I../../third_party/skia/include/docs -I../../third_party/skia/include/effects -I../../third_party/skia/include/encode -I../../third_party/skia/include/gpu -I../../third_party/skia/include/pathops -I../../third_party/skia/include/ports -I../../third_party/skia/include/utils -I../../third_party/skia/include/codec -I../../third_party/skia/src/gpu -I../../third_party/skia/src/sksl -I../../third_party/skia/modules/skottie/include -I../../third_party/libwebm/source -I../../third_party/leveldatabase -I../../third_party/leveldatabase/src -I../../third_party/leveldatabase/src/include -I../../v8/include -Igen/v8/include -I../../third_party/perfetto/include -Igen/third_party/perfetto/protos -I../../testing/gtest/include -Igen/third_party/perfetto/protos -Igen/third_party/perfetto/protos -Igen/third_party/metrics_proto -I../../third_party/re2/src -I../../third_party/mesa_headers -Igen -Igen -Igen -Igen -Igen -I../../third_party/libaddressinput/src/cpp/include -Igen -Igen -Igen -Igen -I../../third_party/cacheinvalidation/overrides -I../../third_party/cacheinvalidation/src -I../../third_party/flatbuffers/src/include -I../../third_party/libxml/src/include -I../../third_party/libxml/win32/include -I../../third_party/zlib -I../../third_party/crashpad/crashpad -I../../third_party/crashpad/crashpad/compat/win /utf-8 /X -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -fcolor-diagnostics -fmerge-all-constants -Xclang -mllvm -Xclang -instcombine-lower-dbg-declare=0 -no-canonical-prefixes -fcomplete-member-pointers /Gy /FS /bigobj /d2FastFail /Zc:sizedDealloc- -fmsc-version=1911 /Zc:dllexportInlines- -m64 /Brepro /W4 -Wimplicit-fallthrough -Wthread-safety /WX /wd4091 /wd4127 /wd4251 /wd4275 /wd4312 /wd4324 /wd4351 /wd4355 /wd4503 /wd4589 /wd4611 /wd4100 /wd4121 /wd4244 /wd4505 /wd4510 /wd4512 /wd4610 /wd4838 /wd4995 /wd4996 /wd4456 /wd4457 /wd4458 /wd4459 /wd4200 /wd4201 /wd4204 /wd4221 /wd4245 /wd4267 /wd4305 /wd4389 /wd4702 /wd4701 /wd4703 /wd4661 /wd4706 /wd4715 /wd4275 /wd4702 -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-nonportable-include-path -Wno-ignored-pragma-optimize /Od /Ob0 /GF /Z7 -fno-standalone-debug /MDd -Xclang -add-plugin -Xclang find-bad-constructs -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wexit-time-destructors /FIbuild/precompile.h -Wno-inconsistent-missing-override -Wno-shorten-64-to-32 -Wno-exit-time-destructors -DLIBXML_STATIC= /Fpobj/chrome/browser/browser_cc.pch /Yubuild/precompile.h -Wno-undefined-bool-conversion -Wno-tautological-undefined-compare /TP /wd4577 /GR- /c ../../chrome/browser/chrome_content_browser_client.cc /Foobj/chrome/browser/browser/chrome_content_browser_client.obj /Fd"obj/chrome/browser/browser_cc.pdb"
In file included from ../../chrome/browser/chrome_content_browser_client.cc:16:
../..\content/nw/src/nw_content.h(84,7):  error: 'nw::GetUserAgentFromManifest' redeclared without 'dllimport' attribute: previous 'dllimport' ignored [-Werror,-Winconsistent-dllimport]
 bool GetUserAgentFromManifest(std::string* agent);
      ^
../..\content/nw/src/common/nw_content_common_hooks.h(14,21):  note: previous declaration is here
CONTENT_EXPORT bool GetUserAgentFromManifest(std::string* agent);
                    ^
../..\content/nw/src/common/nw_content_common_hooks.h(14,1):  note: previous attribute is here
CONTENT_EXPORT bool GetUserAgentFromManifest(std::string* agent);
^
../..\content/common/content_export.h(14,35):  note: expanded from macro 'CONTENT_EXPORT'
#define CONTENT_EXPORT __declspec(dllimport)
                                  ^
In file included from ../../chrome/browser/chrome_content_browser_client.cc:16:
../..\content/nw/src/nw_content.h(85,7):  error: 'nw::SetUserAgentOverride' redeclared without 'dllimport' attribute: previous 'dllimport' ignored [-Werror,-Winconsistent-dllimport]
 void SetUserAgentOverride(const std::string& agent,
      ^
../..\content/nw/src/common/nw_content_common_hooks.h(16,21):  note: previous declaration is here
CONTENT_EXPORT void SetUserAgentOverride(const std::string& agent,
                    ^
../..\content/nw/src/common/nw_content_common_hooks.h(16,1):  note: previous attribute is here
CONTENT_EXPORT void SetUserAgentOverride(const std::string& agent,
^
../..\content/common/content_export.h(14,35):  note: expanded from macro 'CONTENT_EXPORT'
#define CONTENT_EXPORT __declspec(dllimport)
                                  ^
2 errors generated.
[23742/36432] CXX obj/chrome/browser/browser/browser_prefs.obj
ninja: build stopped: subcommand failed.
```

Did I miss some steps in the middle?
Is it fixable by disabling ` [-Werror,-Winconsistent-dllimport]` somehow or requires NW.js source changes with adding `dllimport`?

**Comment by zelid** [comment]
Update 1:

Had to edit `src\content\nw\src\nw_content.h`
and change lines 86-87 from:
```
 bool GetUserAgentFromManifest(std::string* agent);
 void SetUserAgentOverride(const std::string& agent,
                           const std::string& name,
                           const std::string& version);
```
to:
```
 CONTENT_EXPORT bool GetUserAgentFromManifest(std::string* agent);
 CONTENT_EXPORT void SetUserAgentOverride(const std::string& agent,
                           const std::string& name,
                           const std::string& version);
```

in order to match declarations in `src\content\nw\src\common\nw_content_common_hooks.h`

Looks like it helped.

**Comment by zelid** [comment]
Update 2:

Failed on linking with non resolvable me error:

```
PS E:\dev\nwjs\src> ninja -C out/nw nwjs
ninja: Entering directory `out/nw'
[15/259] LINK v8_context_snapshot_generator.exe v8_context_snapshot_generator.exe.pdb
FAILED: v8_context_snapshot_generator.exe v8_context_snapshot_generator.exe.pdb
ninja -t msvc -e environment.x64 -- ../../third_party/llvm-build/Release+Asserts/bin/lld-link.exe /nologo /OUT:./v8_context_snapshot_generator.exe /PDB:./v8_context_snapshot_generator.exe.pdb @./v8_context_snapshot_generator.exe.rsp
lld-link: error: duplicate symbol: "public: static void __cdecl v8::V8::SetFlagsFromString(char const *, int)" (?SetFlagsFromString@V8@v8@@SAXPEBDH@Z) in obj/v8/v8_base/api.obj and in v8.dll
[16/259] LINK(DLL) content.dll content.dll.lib content.dll.pdb
ninja: build stopped: subcommand failed.
```

**Comment by rogerwang** [comment]
Please try this patch:
````
diff --git a/tools/v8_context_snapshot/BUILD.gn b/tools/v8_context_snapshot/BUILD.gn
index 6f0f5d01db60..7fdd0e5ccfab 100644
--- a/tools/v8_context_snapshot/BUILD.gn
+++ b/tools/v8_context_snapshot/BUILD.gn
@@ -104,7 +104,7 @@ if (use_v8_context_snapshot) {
       "//services/service_manager/public/cpp",
       "//third_party/blink/public:blink",
       "//v8",
-      "//v8:v8_initializers",
+      #"//v8:v8_initializers",
     ]

     if (is_linux && !is_component_build) {
````

**Comment by zelid** [comment]
@rogerwang I'm a bit confused. Automatic patch apply didn't work because of the different line numbers. `"//v8:v8_initializers",` is on line 107 in my version of [E:\dev\nw\src\tools\v8_context_snapshot\BUILD.gn](https://gist.github.com/zelid/4254f5ac5960795cf64220625ae59949#file-e-dev-nw-src-tools-v8_context_snapshot-build-gn-L107) which gives an idea I have different source code version.

I decided to delete sources and run all commands from scratch in cmd having VS2017 with MFC/ATL installed:

```
E:\dev\nw> gclient config --name=src https://github.com/nwjs/chromium.src.git@origin/nw38
E:\dev\nw> git clone -b nw38 https://github.com/nwjs/nw.js src/content/nw
E:\dev\nw> git clone -b nw38 https://github.com/nwjs/node src/third_party/node-nw
E:\dev\nw> git clone -b nw38 https://github.com/nwjs/v8 src/v8
E:\dev\nw\src>gclient sync --with_branch_heads
```

This time even `gclient sync --with_branch_heads` failed with `nw` patch of `E:\dev\nw\src\buildtools` (yesterday everything was fine):

```
Hook ''E:\dev\depot_tools\win_tools-2_7_13_chromium7_bin\python\bin\python.exe' src/third_party/depot_tools/download_from_google_storage.py --no_resume --no_auth -u --bucket v8-wasm-fuzzer -s src/v8/test/fuzzer/wasm_corpus.tar.gz.sha1' took 19.71 secs
Running hooks:  48% (37/77) nw_patch
________ running 'E:\dev\depot_tools\win_tools-2_7_13_chromium7_bin\python\bin\python.exe src/content/nw/tools/patcher.py' in 'E:\dev\nw'

Apply selenium.patch in E:\dev\nw\src\third_party\webdriver\pylib
        21      0       selenium/webdriver/chrome/options.py
... successfully applied.

Apply ffmpeg.patch in E:\dev\nw\src\third_party\ffmpeg
        8       4       BUILD.gn
... successfully applied (with warnings):
        warning: BUILD.gn has type 100644, expected 100755

Apply icu.patch in E:\dev\nw\src\third_party\icu
        7       0       icu.gyp
... successfully applied.

Apply buildtools.patch in E:\dev\nw\src\buildtools
... patch directory is not a repository root.
-------------------------------------------------------------------------------
!!!! ERROR: This patch failed to apply. Your build will not be correct.
-------------------------------------------------------------------------------

4 patches total (3 applied, 0 skipped, 1 failed)

-------------------------------------------------------------------------------
!!!! ERROR: 1 patches failed to apply. Your build will not be correct.
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "src/content/nw/tools/patcher.py", line 121, in <module>
    apply_patch_config()
  File "src/content/nw/tools/patcher.py", line 96, in apply_patch_config
    results['fail'])
Exception: 1 patches failed to apply. Your build will not be correct.
Error: Command 'E:\\dev\\depot_tools\\win_tools-2_7_13_chromium7_bin\\python\\bin\\python.exe src/content/nw/tools/patcher.py' returned non-zero exit status 1 in E:\dev\nw
```

Is anything wrong in commands or git branches I"m trying to use?

**Comment by rogerwang** [comment]
For now please use `nw38-log` branch for the chromium repo, v8 repo and Node repo. I'll update the 'nw38' branch soon, or update the build documentation. Thanks.
