### ISSUE TITLE
"ERROR: This patch failed to apply. Your build will not be correct." when building nw41

### ISSUE THREAD

**Issue by sirisian** [nwjs/nw.js#7162]
(I did not test against the latest version, just nw41 branch which should build fine).

I followed this exactly on Windows 10: http://docs.nwjs.io/en/latest/For%20Developers/Building%20NW.js/

I made sure to checkout the required branches and verified they're all nw41. I deleted it all and tried again even thinking I made a mistake, but I got the same result.

On the line:

`gclient sync --with_branch_heads`

It outputs this after a while:
```
...
Running hooks:  48% (37/76) nw_patch
________ running 'C:\depot_tools\bootstrap-3_8_0b1_chromium_1_bin\python\bin\python.exe src/content/nw/tools/patcher.py' in 'C:\Users\username\Desktop\nwjs'

Apply selenium.patch in C:\Users\username\Desktop\nwjs\src\third_party\webdriver\pylib
        21      0       selenium/webdriver/chrome/options.py
... failed to apply:
        error: patch failed: selenium/webdriver/chrome/options.py:25
        error: selenium/webdriver/chrome/options.py: patch does not apply
-------------------------------------------------------------------------------
!!!! ERROR: This patch failed to apply. Your build will not be correct.
-------------------------------------------------------------------------------

Apply ffmpeg.patch in C:\Users\username\Desktop\nwjs\src\third_party\ffmpeg
        8       4       BUILD.gn
... failed to apply:
        warning: BUILD.gn has type 100644, expected 100755
        error: patch failed: BUILD.gn:264
        error: BUILD.gn: patch does not apply
-------------------------------------------------------------------------------
!!!! ERROR: This patch failed to apply. Your build will not be correct.
-------------------------------------------------------------------------------

Apply icu.patch in C:\Users\username\Desktop\nwjs\src\third_party\icu
        7       0       icu.gyp
... failed to apply:
        error: patch failed: icu.gyp:41
        error: icu.gyp: patch does not apply
-------------------------------------------------------------------------------
!!!! ERROR: This patch failed to apply. Your build will not be correct.
-------------------------------------------------------------------------------

3 patches total (0 applied, 0 skipped, 3 failed)

-------------------------------------------------------------------------------
!!!! ERROR: 3 patches failed to apply. Your build will not be correct.
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "src/content/nw/tools/patcher.py", line 121, in <module>
    apply_patch_config()
  File "src/content/nw/tools/patcher.py", line 96, in apply_patch_config
    results['fail'])
Exception: 3 patches failed to apply. Your build will not be correct.
Error: Command 'C:\\depot_tools\\bootstrap-3_8_0b1_chromium_1_bin\\python\\bin\\python.exe src/content/nw/tools/patcher.py' returned non-zero exit status 1 in C:\Users\username\Desktop\nwjs
```

I just formatted this machine so the development environment on it is basically pristine. Unsure what I did wrong.

**Comment by jiangjianping** [comment]
@sirisian 
I encounter the same problem based on the nw40 firstly.  Which version of your VS?  try the 2017 not  2019?

**Comment by sirisian** [comment]
I haven't even run gn yet. Isn't the patch step purely just python?

In any case I have both VS2019 and VS2017 installed. Running gclient in either admin console produces the same result.

**Comment by sirisian** [comment]
Kind of off-topic, but I did try to build just ffmpeg using VS2019 (with vcvarsall.bat amd64 if it matters) following http://docs.nwjs.io/en/latest/For%20Developers/Enable%20Proprietary%20Codecs/:
```
gn gen out/nw "--args=is_debug=false is_component_ffmpeg=true target_cpu=\"x64\" is_official_build=true ffmpeg_branding=\"Chrome\""
ninja -C out/nw ffmpeg
```
and it says:

```
[1/78] LINK nasm.exe nasm.exe.pdb
FAILED: nasm.exe nasm.exe.pdb
ninja -t msvc -e environment.x64 -- ../../third_party/llvm-build/Release+Asserts/bin/lld-link.exe /nologo /OUT:./nasm.exe /PDB:./nasm.exe.pdb @./nasm.exe.rsp
lld-link: error: libcmt.lib(chkstk.obj): machine type x86 conflicts with x64
[18/78] CC obj/third_party/opus/opus/NSQ_del_dec.obj
ninja: build stopped: subcommand failed.
```

Works fine with VS2017 using the exact same commands though.
