### ISSUE TITLE
NW2: Uncaught ReferenceError. 

### ISSUE THREAD

**Issue by prominentdetail** [nwjs/nw.js#7315]
NWJS Version : 0.43.4
Operating System : win10

### Expected behavior

tilesetWindow.eval(null, "tileSet.refresh( );" ); should successfully call the tileSet.refresh()

### Actual behavior

An error:
Uncaught ReferenceError: tileSet is not defined
    at <anonymous>:1:1
    at NWWindow.eval (extensions::nw.Window:379:20)
    at mainData.tab (chrome-extension://jdgkbifmkkkcgglljmlojibojoafmlhi/mainWin.js:16:17)
    at <anonymous>:1:6
    at NWWindow.eval (extensions::nw.Window:379:20)
    at configData.chooseTab (chrome-extension://jdgkbifmkkkcgglljmlojibojoafmlhi/second.html:44:13)
    at haveParent (chrome-extension://jdgkbifmkkkcgglljmlojibojoafmlhi/second.html:26:11)
    at NWWindow.<anonymous> (chrome-extension://jdgkbifmkkkcgglljmlojibojoafmlhi/mainWin.js:40:18)
    at NWWindow.<anonymous> (extensions::nw.Window:199:18)

### How to reproduce

Run the attached code
[nwjsTest.zip](https://github.com/nwjs/nw.js/files/4049821/nwjsTest.zip)

**IF I USE 
  "chromium-args": "--disable-features=nw2"
THEN IT WILL WORK.**

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by rogerwang** [comment]
The nightly build for this issue is available at https://dl.nwjs.io/live-build/nw43/20200112-162000/425569548
