### ISSUE TITLE
Problems building native modules with nw-gyp

### ISSUE THREAD

**Issue by mightytyphoon** [nwjs/nw.js#7604]
NWJS Version : 0.49.1
Operating System :  [version 10.0.18363.1139]

### Expected behavior

Hi ! I would like a native module for nwjs on windows as shown in the documentation (doc : http://docs.nwjs.io/en/latest/For%20Users/Advanced/Use%20Native%20Node%20Modules/)

### Actual behavior

When trying to build node-pty module with the proposed method in nwjs documentation to get rid of dll problems, I get this output : 

```
> node-pty@0.9.0 install C:\Users\Maison\Desktop\nw-pty-test\node_modules\node-pty
> node scripts/install.js


C:\Users\Maison\Desktop\nw-pty-test\node_modules\node-pty>if not defined npm_config_node_gyp (node "C:\Users\Maison\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Maison\AppData\Roaming\npm\node_modules\nw-gyp\bin\nw-gyp.js" rebuild )
Les projets sont générés individuellement dans cette solution. Pour activer la génération en parallèle, ajoutez le commutateur "/m".
clang-cl : warning : argument unused during compilation: '/MP' [-Wunused-command-line-argument] [C:\Users\Maison\Desktop\nw-pty-test\node_modules\node-pty\build\conpty.vcxproj]
clang-cl : warning : argument unused during compilation: '/Gm-' [-Wunused-command-line-argument] [C:\Users\Maison\Desktop\nw-pty-test\node_modules\node-pty\build\conpty.vcxproj]
..\src\win\conpty.cc(167): warning : unused variable '_piClient' [-Wunused-variable] [C:\Users\Maison\Desktop\nw-pty-test\node_modules\node-pty\build\conpty.vcxproj]
..\src\win\conpty.cc(165): warning : unused variable 'fSuccess' [-Wunused-variable] [C:\Users\Maison\Desktop\nw-pty-test\node_modules\node-pty\build\conpty.vcxproj]
..\src\win\conpty.cc(183): warning : unused variable 'debug' [-Wunused-variable] [C:\Users\Maison\Desktop\nw-pty-test\node_modules\node-pty\build\conpty.vcxproj]
..\src\win\conpty.cc(321): warning : suggest braces around initialization of subobject [-Wmissing-braces] [C:\Users\Maison\Desktop\nw-pty-test\node_modules\node-pty\build\conpty.vcxproj]
..\src\win\path_util.cc(60): warning : comparison of array 'searchPath' equal to a null pointer is always false [-Wtautological-pointer-compare] [C:\Users\Maison\Desktop\nw-pty-test\node_modu
les\node-pty\build\conpty.vcxproj]
  conpty.vcxproj -> C:\Users\Maison\Desktop\nw-pty-test\node_modules\node-pty\build\Release\\conpty.node
clang-cl : warning : argument unused during compilation: '/MP' [-Wunused-command-line-argument] [C:\Users\Maison\Desktop\nw-pty-test\node_modules\node-pty\build\conpty_console_list.vcxproj]
clang-cl : warning : argument unused during compilation: '/Gm-' [-Wunused-command-line-argument] [C:\Users\Maison\Desktop\nw-pty-test\node_modules\node-pty\build\conpty_console_list.vcxproj]
  conpty_console_list.vcxproj -> C:\Users\Maison\Desktop\nw-pty-test\node_modules\node-pty\build\Release\\conpty_console_list.node
clang-cl : warning : argument unused during compilation: '/MP' [-Wunused-command-line-argument] [C:\Users\Maison\Desktop\nw-pty-test\node_modules\node-pty\build\deps\winpty\src\winpty.vcxproj
]
clang-cl : warning : argument unused during compilation: '/Gm-' [-Wunused-command-line-argument] [C:\Users\Maison\Desktop\nw-pty-test\node_modules\node-pty\build\deps\winpty\src\winpty.vcxpro
j]
..\..\..\..\deps\winpty\src\libwinpty\winpty.cc(563): warning : moving a local object in a return statement prevents copy elision [-Wpessimizing-move] [C:\Users\Maison\Desktop\nw-pty-test\nod
e_modules\node-pty\build\deps\winpty\src\winpty.vcxproj]
  ..\..\..\..\deps\winpty\src\libwinpty\winpty.cc(563): note: remove std::move call here
..\..\..\..\deps\winpty\src\shared\WindowsSecurity.cc(209): warning : moving a local object in a return statement prevents copy elision [-Wpessimizing-move] [C:\Users\Maison\Desktop\nw-pty-te
st\node_modules\node-pty\build\deps\winpty\src\winpty.vcxproj]
  ..\..\..\..\deps\winpty\src\shared\WindowsSecurity.cc(209): note: remove std::move call here
..\..\..\..\deps\winpty\src\shared\WindowsVersion.cc(57): warning : 'GetVersionExW' is deprecated [-Wdeprecated-declarations] [C:\Users\Maison\Desktop\nw-pty-test\node_modules\node-pty\build\
deps\winpty\src\winpty.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\sysinfoapi.h(392): note: expanded from macro 'GetVersionEx'
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\sysinfoapi.h(382): note: 'GetVersionExW' has been explicitly marked deprecated here
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\sysinfoapi.h(37): note: expanded from macro 'NOT_BUILD_WINDOWS_DEPRECATE'
C:\Users\Maison\AppData\Roaming\npm\node_modules\nw-gyp\src\win_delay_load_hook.cc(34): error : no matching function for call to 'GetModuleHandleW' [C:\Users\Maison\Desktop\nw-pty-test\node_m
odules\node-pty\build\deps\winpty\src\winpty.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\libloaderapi.h(274): note: expanded from macro 'GetModuleHandle'
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\libloaderapi.h(269): note: candidate function not viable: no known conversion from 'const char [9]' to 'LPCWSTR' (aka 'const w
  char_t *') for 1st argument
C:\Users\Maison\AppData\Roaming\npm\node_modules\nw-gyp\src\win_delay_load_hook.cc(35): error : no matching function for call to 'GetModuleHandleW' [C:\Users\Maison\Desktop\nw-pty-test\node_m
odules\node-pty\build\deps\winpty\src\winpty.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\libloaderapi.h(274): note: expanded from macro 'GetModuleHandle'
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\libloaderapi.h(269): note: candidate function not viable: no known conversion from 'const char [7]' to 'LPCWSTR' (aka 'const w
  char_t *') for 1st argument
clang-cl : warning : argument unused during compilation: '/MP' [-Wunused-command-line-argument] [C:\Users\Maison\Desktop\nw-pty-test\node_modules\node-pty\build\deps\winpty\src\winpty-agent.v
cxproj]
clang-cl : warning : argument unused during compilation: '/Gm-' [-Wunused-command-line-argument] [C:\Users\Maison\Desktop\nw-pty-test\node_modules\node-pty\build\deps\winpty\src\winpty-agent.
vcxproj]
..\..\..\..\deps\winpty\src\agent\Terminal.cc(70): warning : unused variable 'SGR_BACK_HI' [-Wunused-const-variable] [C:\Users\Maison\Desktop\nw-pty-test\node_modules\node-pty\build\deps\winp
ty\src\winpty-agent.vcxproj]
..\..\..\..\deps\winpty\src\shared\WindowsSecurity.cc(209): warning : moving a local object in a return statement prevents copy elision [-Wpessimizing-move] [C:\Users\Maison\Desktop\nw-pty-te
st\node_modules\node-pty\build\deps\winpty\src\winpty-agent.vcxproj]
  ..\..\..\..\deps\winpty\src\shared\WindowsSecurity.cc(209): note: remove std::move call here
..\..\..\..\deps\winpty\src\shared\WindowsVersion.cc(57): warning : 'GetVersionExW' is deprecated [-Wdeprecated-declarations] [C:\Users\Maison\Desktop\nw-pty-test\node_modules\node-pty\build\
deps\winpty\src\winpty-agent.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\sysinfoapi.h(392): note: expanded from macro 'GetVersionEx'
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\sysinfoapi.h(382): note: 'GetVersionExW' has been explicitly marked deprecated here
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\sysinfoapi.h(37): note: expanded from macro 'NOT_BUILD_WINDOWS_DEPRECATE'
C:\Users\Maison\AppData\Roaming\npm\node_modules\nw-gyp\src\win_delay_load_hook.cc(34): error : no matching function for call to 'GetModuleHandleW' [C:\Users\Maison\Desktop\nw-pty-test\node_m 
odules\node-pty\build\deps\winpty\src\winpty-agent.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\libloaderapi.h(274): note: expanded from macro 'GetModuleHandle'
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\libloaderapi.h(269): note: candidate function not viable: no known conversion from 'const char [9]' to 'LPCWSTR' (aka 'const w 
  char_t *') for 1st argument
C:\Users\Maison\AppData\Roaming\npm\node_modules\nw-gyp\src\win_delay_load_hook.cc(35): error : no matching function for call to 'GetModuleHandleW' [C:\Users\Maison\Desktop\nw-pty-test\node_m 
odules\node-pty\build\deps\winpty\src\winpty-agent.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\libloaderapi.h(274): note: expanded from macro 'GetModuleHandle'
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\libloaderapi.h(269): note: candidate function not viable: no known conversion from 'const char [7]' to 'LPCWSTR' (aka 'const w 
  char_t *') for 1st argument
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Maison\AppData\Roaming\npm\node_modules\nw-gyp\lib\build.js:271:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Maison\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\bin\\nw-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Maison\Desktop\nw-pty-test\node_modules\node-pty
gyp ERR! node -v v12.19.0
gyp ERR! nw-gyp -v v3.6.5
gyp ERR! not ok
npm WARN nw-pty-test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty@0.9.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-pty@0.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Maison\AppData\Roaming\npm-cache\_logs\2020-10-23T16_07_11_105Z-debug.log
```

### How to reproduce

1. init npm project
2. install last version of nw globally
3. install globally nw-gyp & node-gyp
4. use the documentation to set up nw-gyp
* set npm_config_target=0.21.6
* set npm_config_arch=x64
* set npm_config_runtime=node-webkit
* set npm_config_build_from_source=true
* set npm_config_node_gyp=C:\Users\xxxxxxxxx\AppData\Roaming\npm\node_modules\nw-gyp\bin\nw-gyp.js
(xxxxxxxxxx being your user folder)
5. add to package.json the native module to build (in my case node-pty)
6.  install as shown in the documentation => npm install --msvs_version=2015
(make sure to delete package-lock.json)

Thanks for your help.
Regards.

**Comment by Jackson-he** [comment]
I get the same error, do you resolve this?

**Comment by mightytyphoon** [comment]
Hi ! 

I didn't find a solution to this, but maybe it's time to get back on this project. I will give it another try soon (probably after end of this year) and keep you updated. If you managed to find before I do, thank you in advance for sharing your solution. 

Regards.

**Comment by anlate** [comment]
I got the same error when I execute the script `nw-gyp rebuild --target=0.51.0 --arch=x64`
```
node-pty:0.10.0 and 0.10.1
node:10~16
nw-gyp:3.6.5
```
and the node-pty can't work.

then I tried the version 0.10.0-beta8,something intersting happened. the error still exits. but when I start NWJS, it works well.
