### ISSUE TITLE
DLL initialization routine failed in leveldown\prebuilds\win32-x64\node.napi.node

### ISSUE THREAD

**Issue by brailateo** [nwjs/nw.js#7617]
Working on a nwjs project that is using pouchdb
Everything is OK on Linux, tried to install project on Windows.
The app.js is working fine on windows, when I can access the documents in  pouchdb but only when I am using node with :
`$ node app.js
`
but when I started my app with nwjs for the UI I got the following error

node:internal/modules/cjs/loader:1187 Uncaught Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\IEUser\Desktop\nwjs-sdk-v0.49.2-win-x64\appteo\node_modules\leveldown\prebuilds\win32-x64\node.napi.node
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1187:18)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:88:18)
    at load (C:\Users\IEUser\Desktop\nwjs-sdk-v0.49.2-win-x64\appteo\node_modules\node-gyp-build\index.js:20:10)
    at Object.<anonymous> (C:\Users\IEUser\Desktop\nwjs-sdk-v0.49.2-win-x64\appteo\node_modules\leveldown\binding.js:1:43)
    at Module._compile (node:internal/modules/cjs/loader:1107:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1142:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)

Any suggestions?
Teo

**Comment by xaronnn** [comment]
Needs to fix, i'm waiting for the update.
