### ISSUE TITLE
ZLib inflation fails since 0.49.0+

### ISSUE THREAD

**Issue by Kruithne** [nwjs/nw.js#7627]
```
Error: incorrect data check
    at Zlib.zlibOnError [as onerror] (zlib.js:180:17)
    at processChunkSync (zlib.js:429:12)
    at zlibBufferSync (zlib.js:168:12)
    at Object.syncBufferWrapper [as inflateSync] (zlib.js:763:14)
    at BufferWrapper.readBuffer (D:\wow.export\src\js\buffer.js:457:15)
    at BLTEReader._decompressBlock (D:\wow.export\src\js\casc\blte-reader.js:204:23)
    at BLTEReader._handleBlock (D:\wow.export\src\js\casc\blte-reader.js:189:10)
    at BLTEReader._processBlock (D:\wow.export\src\js\casc\blte-reader.js:147:8)
    at BLTEReader._checkBounds (D:\wow.export\src\js\casc\blte-reader.js:280:9)
    at BLTEReader._readInt (D:\wow.export\src\js\buffer.js:918:9) {
  [stack]: 'Error: incorrect data check\n' +
    '    at Zlib.zlibOnError [as onerror] (zlib.js:180:17)\n' +
    '    at processChunkSync (zlib.js:429:12)\n' +
    '    at zlibBufferSync (zlib.js:168:12)\n' +
    '    at Object.syncBufferWrapper [as inflateSync] (zlib.js:763:14)\n' +
    '    at BufferWrapper.readBuffer (D:\\wow.export\\src\\js\\buffer.js:457:15)\n' +
    '    at BLTEReader._decompressBlock (D:\\wow.export\\src\\js\\casc\\blte-reader.js:204:23)\n' +
    '    at BLTEReader._handleBlock (D:\\wow.export\\src\\js\\casc\\blte-reader.js:189:10)\n' +
    '    at BLTEReader._processBlock (D:\\wow.export\\src\\js\\casc\\blte-reader.js:147:8)\n' +
    '    at BLTEReader._checkBounds (D:\\wow.export\\src\\js\\casc\\blte-reader.js:280:9)\n' +
    '    at BLTEReader._readInt (D:\\wow.export\\src\\js\\buffer.js:918:9)',
  [message]: 'incorrect data check',
  errno: -3,
  code: 'Z_DATA_ERROR'
}
```

Potentially related to #7625.

Affected versions: 0.49.0, 0.49.1, 0.49.2, 0.50.0

**Comment by rogerwang** [comment]
merge with #7625. Please follow up there.
