### ISSUE TITLE
NW.js crashes when launched by Microsoft Playwright (testing utility)

### ISSUE THREAD

**Issue by TheJaredWilcurt** [nwjs/nw.js#7663]
**NW.js Version:** 0.51.0-sdk
**Operating System:** Win 10

### Expected behavior

Run playwright with custom path pointing to NW.js executable

### Actual behavior

debug log states:
```
[0124/233623.899:ERROR:resource_bundle.cc(960)] Failed to load C:\Users\wilcurtj\Desktop\playwright2\node_modules\nw\nwjs\chrome_100_percent.pak
Some features may not be available.
[0124/233623.900:ERROR:resource_bundle.cc(960)] Failed to load C:\Users\wilcurtj\Desktop\playwright2\node_modules\nw\nwjs\chrome_200_percent.pak
Some features may not be available.
[0124/233638.941:INFO:child_thread_impl.cc(838)] ChildThreadImpl::EnsureConnected()
```

### How to reproduce

Run playwright and point it to NW.js

```js
const path = require('path');
const { chromium } = require('playwright');

try {
  (async () => {
    const browser = await chromium.launch({
      executablePath: path.resolve(__dirname, 'node_modules/nw/nwjs/nw.exe')
    });
    const page = await browser.newPage();
    // await page.goto('https://nwjs.io');
    await page.screenshot({ path: 'example.png' });

    await browser.close();
  })();
} catch (err) {
  console.log(err);
}
```

**Reproduction attached.**

* [nw-playwright.zip](https://github.com/nwjs/nw.js/files/5864269/nw-playwright.zip)

**Full command line output from reproduction:**

```
(node:14844) UnhandledPromiseRejectionWarning: browserContext.newPage: Protocol error (Target.createTarget): Browser closed.
==================== Browser output: ====================
<launching> C:\nw-playwright\node_modules\nw\nwjs\nw.exe --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI,BlinkGenPropertyTrees,ImprovedCookieControls,SameSiteByDefaultCookies,LazyFrameLoading --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --user-data-dir=C:\Users\owner\AppData\Local\Temp\playwright_chromiumdev_profile-Ijx831 --remote-debugging-pipe --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --no-startup-window
<launched> pid=10888
[err] [0124/235308.371:ERROR:resource_bundle.cc(960)] Failed to load C:\nw-playwright\node_modules\nw\nwjs\chrome_100_percent.pak
[err] Some features may not be available.
[err] [0124/235308.372:ERROR:resource_bundle.cc(960)] Failed to load C:\nw-playwright\node_modules\nw\nwjs\chrome_200_percent.pak
[err] Some features may not be available.
    at Connection.sendMessageToServer (C:\nw-playwright\node_modules\playwright\lib\client\connection.js:69:15)
    at Proxy.<anonymous> (C:\nw-playwright\node_modules\playwright\lib\client\channelOwner.js:44:61)
    at C:\nw-playwright\node_modules\playwright\lib\client\browserContext.js:95:58
    at ChromiumBrowserContext._wrapApiCall (C:\nw-playwright\node_modules\playwright\lib\client\channelOwner.js:72:34)
    at ChromiumBrowserContext.newPage (C:\nw-playwright\node_modules\playwright\lib\client\browserContext.js:92:21)
    at ChromiumBrowser.newPage (C:\nw-playwright\node_modules\playwright\lib\client\browser.js:58:36)
    at async C:\nw-playwright\play.js:9:18
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14844) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:14844) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by abflow** [comment]
It might be related to #586 and the lack of stdin support by the nw process...

**Comment by abflow** [comment]
Playwright uses the `--remote-debugging-pipe` flag which passes the remote debug protocol messages over stdio pipes [in=3, out=4], but as `process.stdin` is faulty, it crashes.
