### ISSUE TITLE
'CERT_HAS_EXPIRED' error

### ISSUE THREAD

**Issue by KoopintheHub** [nwjs/nw.js#7664]
NW.JS Version: 0.51.0-sdk
Operating System: Windows 10 x64

### **Expected behavior**
It should download SDK zip files.

### **Actual Behaviour**
But instead it threw this error:

```
Latest Version: v0.51.0
Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1502:34)
    at TLSSocket.emit (events.js:314:20)
    at TLSSocket._finishInit (_tls_wrap.js:937:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:711:12) {
  code: 'CERT_HAS_EXPIRED'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Zangpule-Run@1.0.0 prod: `nwbuild --platforms win32,win64,osx64,linux32,linux64 --buildDir dist/ src/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Zangpule-Run@1.0.0 prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\**********\AppData\Roaming\npm-cache\_logs\2021-01-25T11_38_46_696Z-debug.log
```

### **How to produce**

This is the LOG file:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'prod'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v12.19.0
4 verbose run-script [ 'preprod', 'prod', 'postprod' ]
5 info lifecycle Zangpule-Run@1.0.0~preprod: Zangpule-Run@1.0.0
6 info lifecycle Zangpule-Run@1.0.0~prod: Zangpule-Run@1.0.0
7 verbose lifecycle Zangpule-Run@1.0.0~prod: unsafe-perm in lifecycle true
8 verbose lifecycle Zangpule-Run@1.0.0~prod: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\***********\Zangpule Run!\HTML\Zangpule-Run\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\Wiimm\SZS;C:\Program Files\heroku\bin;C:\Users\***********\AppData\Local\Programs\Microsoft VS Code\bin;"C:\PS\psx\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\Wiimm\SZS";"C:\PS\pssn\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\Wiimm\SZS";"C:\PS\pssn\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\Wiimm\SZS";"C:\PS\psxgraph\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\Wiimm\SZS";C:\snesdev\msys\bin;C:\Program Files\Wiimm\SZS
9 verbose lifecycle Zangpule-Run@1.0.0~prod: CWD: C:\Users\***********\Zangpule Run!\HTML\Zangpule-Run
10 silly lifecycle Zangpule-Run@1.0.0~prod: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'nwbuild --platforms win32,win64,osx64,linux32,linux64 --buildDir dist/ src/'
10 silly lifecycle ]
11 silly lifecycle Zangpule-Run@1.0.0~prod: Returned: code: 1  signal: null
12 info lifecycle Zangpule-Run@1.0.0~prod: Failed to exec prod script
13 verbose stack Error: Zangpule-Run@1.0.0 prod: `nwbuild --platforms win32,win64,osx64,linux32,linux64 --buildDir dist/ src/`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid Zangpule-Run@1.0.0
15 verbose cwd C:\Users\***********\Zangpule Run!\HTML\Zangpule-Run
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "prod"
18 verbose node v12.19.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error Zangpule-Run@1.0.0 prod: `nwbuild --platforms win32,win64,osx64,linux32,linux64 --buildDir dist/ src/`
22 error Exit status 1
23 error Failed at the Zangpule-Run@1.0.0 prod script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```
[source.zip](https://github.com/nwjs/nw.js/files/5866325/source.zip)
and this is the source.

**Comment by KoopintheHub** [comment]
Nevermind I have solved it.

**Comment by SuperKirik** [comment]
hello @KoopintheHub  !

How did you solve it, I have the same issue

**Comment by zxfrank** [comment]
> Nevermind I have solved it.

Hello @KoopintheHub, you came here for help. When you find the solution, let others know to help them.

thanks

**Comment by zxfrank** [comment]
a "temporary" workaround may be to add `process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0'`
