### ISSUE TITLE
CustomEvent not work in latest nw.js build 0.73.0

### ISSUE THREAD

**Issue by omenus** [nwjs/nw.js#8034]
### Issue Type

Before opening an issue, please search and see if it has already been raised.

- [ ] Bug Report
- [ ] Uncaught TypeError: Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event'.
    at index.js:9:8

- [ x] Successfully reproduced against the latest version of NW.js? yes 0.73.0

> Please use our [mailing list](https://groups.google.com/forum/#!forum/nwjs-general) or [Gitter chatroom](https://gitter.im/nwjs/nw.js) to ask questions. The issue tracker is only for bugs and feature requests, in English only. Please note that issues without a repro or code snippet are less likely to be resolved.

### Current/Missing Behavior
CustomEvent 
### Expected/Proposed Behavior
class CustomEvent extends Event {} (when this is added to code, then its work, but not always can be added in libraries scope like uPlot

there is error:
Uncaught TypeError: Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event'.
at index.js:9:8

There is no such issue in older version like 0.52.x but in 0.70.x there is was this event
### Additional Info

- Operating System: Windows 10
- NW.js Version: 0.73.0
- Repro Link: 
- Code snippet:
- 

window.addEventListener("testevent", (e) => {
console.log(e);
});

let ev = new CustomEvent("testevent", { bubbles: true, cancelable: false });
window.dispatchEvent(ev);

- Crash report:
- Uncaught TypeError: Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event'.
    at index.js:9:8

[nwapp.zip](https://github.com/nwjs/nw.js/files/10875104/nwapp.zip)

**Comment by tharatau** [comment]
I made an automated test using [Chromedriver first] (https://github.com/tharatau/idea-maze/tree/main/lib/nw) but the test passed for me.

I also manually ran your code snippet and it worked for me.
![image](https://user-images.githubusercontent.com/14110965/222556767-051590e1-2d09-47e7-bb43-133d0eb47157.png)

My guess is this has to do with your IDE.

**Comment by omenus** [comment]
Please try download latest 0.73.0 sdk version (Windows), unzip and add my zipped mini app test, and run: 
npm run dev or 
..\\nwjs-sdk-v0.73.0-win-x64\\nw.exe .
-as configured in package.json. There is no IDE, just simple run (npm -v 8.19.2, node v18.12.1 - but this should be not important)

**Comment by tharatau** [comment]
Apologies! I must skipped over the attached zip file. Currently afk but will try it out soon.

**Comment by tharatau** [comment]
Was able to reproduce. This only happens in Mixed Content:

![image](https://user-images.githubusercontent.com/14110965/225436885-d99335ce-1ed7-4e08-b62b-ff2ad96ae3c1.png)

Let me investigate if this is a bug or intended behaviour.

**Comment by tharatau** [comment]
This might be a limitation of [Mixed Context](https://nwjs.readthedocs.io/en/latest/For%20Users/Advanced/JavaScript%20Contexts%20in%20NW.js/#working-with-multiple-contexts).

> While differences of contexts are generally benefitial, sometimes they may constitute a problem in your (or some other person’s) code, and a need for a workaround arises.

> For example, in different browser contexts, the global objects are not identical and some type checking tricks will fail with multiple contexts.

I don't know enough about the internals and maybe @rogerwang can weight in here?

**Comment by tripl3inf** [comment]
Observing the same breaking change. This has always worked in previous NW versions running in "mixed-context" mode. "CustomEvent" inherits from "Event" (which does work). This is certainly a bug. @rogerwang -- please advise.

**Comment by tharatau** [comment]
What was the last version this worked?

**Comment by tripl3inf** [comment]
Appears to have broken in v0.70.1.
 
![v0 70 1](https://user-images.githubusercontent.com/6551456/232850362-43299a4e-9b74-4769-a4ea-67de4a3c82c6.png)

![v0 70 0](https://user-images.githubusercontent.com/6551456/232850392-2abcf492-335c-4167-8dfa-6bc3a49a3422.png)

**Comment by iqrok** [comment]
![image](https://github.com/nwjs/nw.js/assets/7772479/94c1f2bc-1df4-45df-bb2f-710ca59a99ab)

CustomEvent still doesn't work on 0.84 linux

**Comment by xenobytezero** [comment]
Also not working for me in 0.84 Windows, does not happen when not using `--mixed-context`

![image](https://github.com/nwjs/nw.js/assets/5059527/55fc2ddc-04a8-495d-9ed7-1c9af7123d88)

**Comment by harrychiling** [comment]
A work around:

let ev = document.createEvent("customevent");
ev.initCustomEvent('dcs-update', true, true, {
    name: 'Harry'
});
document.dispatchEvent(ev);

This is supposed to be deprecated but works in the newest NWjs.  Of course a class could be created to extend out the CustomEvent from the Event class with the above code in the constructor, since ev instanceof Event is true.

**Comment by ssnangua** [comment]
An interim solution, writing a polyfill:
```js
class CustomEvent extends Event {
  constructor(type, options = {}) {
    super(type, options);
    this.detail = options?.detail ?? null;
  }
}
```

**Comment by GnorTech** [comment]
Tested on 0.111.1 — cross-context CustomEvent dispatchEvent no longer throws. instanceof Event returns false across Node/DOM contexts as expected, but the dispatch itself works. This was fixed upstream since 0.73.0.
