### ISSUE TITLE
Unable to build node (libcpp.lib not found)

### ISSUE THREAD

**Issue by lab313ru** [nwjs/nw.js#8048]
I don't sure where should I post this issue, but as I understand its building rule belongs to `out/nw`, so it should be here. Anyway, here is what happens:

For now it's impossible to build node correctly. This is what I get:
```
FAILED: node.dll node.dll.lib node.dll.pdb
f:\dev\depot_tools\bootstrap-2@3_8_10_chromium_26_bin\python\bin\python.exe gyp-win-tool link-with-manifests environment.x64 True node.dll "f:\dev\depot_tools\bootstrap-2@3_8_10_chromium_26_bin\python\bin\python.exe gyp-win-tool link-wrapper environment.x64 False ..\..\third_party/llvm-build/Release+Asserts/bin/lld-link.exe /nologo /IMPLIB:node.dll.lib /DLL /OUT:node.dll @node.dll.rsp" 2 mt.exe rc.exe "obj\third_party\node-nw\node.node.dll.intermediate.manifest" obj\third_party\node-nw\node.node.dll.generated.manifest
lld-link: error: could not open '../nw/obj/buildtools/third_party/libc++/libcpp.lib': no such file or directory
lld-link: error: /failifmismatch: mismatch detected for 'RuntimeLibrary':
>>> obj\third_party\node-nw\src\node.tls_wrap.obj has value MTd_StaticDebug
>>> ../nw/obj/v8\v8_libplatform/trace-object.obj has value MDd_DynamicDebug
Traceback (most recent call last):
  File "gyp-win-tool", line 323, in <module>
    sys.exit(main(sys.argv[1:]))
  File "gyp-win-tool", line 29, in main
    exit_code = executor.Dispatch(args)
  File "gyp-win-tool", line 71, in Dispatch
    return getattr(self, method)(*args[1:])
  File "gyp-win-tool", line 179, in ExecLinkWithManifests
    subprocess.check_call(ldcmd + add_to_ld)
  File "f:\dev\depot_tools\bootstrap-2@3_8_10_chromium_26_bin\python\bin\lib\subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'f:\dev\depot_tools\bootstrap-2@3_8_10_chromium_26_bin\python\bin\python.exe gyp-win-tool link-wrapper environment.x64 False ..\..\third_party/llvm-build/Release+Asserts/bin/lld-link.exe /nologo /IMPLIB:node.dll.lib /DLL /OUT:node.dll @node.dll.rsp node.dll.manifest.res' returned non-zero exit status 1
ninja: build stopped: subcommand failed.
```

I also tried to call build manually like this:
```
f:\nwjs\src>autoninja -C out\nw libcpp
"f:\dev\depot_tools\bootstrap-2@3_8_10_chromium_26_bin\python3\bin\python3.exe" F:\dev\depot_tools\ninja.py -C out\nw libcpp -j 34
ninja: Entering directory `out\nw'
[2/2] LIB obj/buildtools/third_party/libc++/libcpp.lib

f:\nwjs\src>autoninja -C out\nw libc++
"f:\dev\depot_tools\bootstrap-2@3_8_10_chromium_26_bin\python3\bin\python3.exe" F:\dev\depot_tools\ninja.py -C out\nw libc++ -j 34
ninja: Entering directory `out\nw'
ninja: no work to do.
```

And it shows, that it does something, but doesn't generate any output file in case of libcpp.

Related issue at the `node` repo: https://github.com/nwjs/node/issues/53

**Comment by lab313ru** [comment]
I also checked what the `libcpp` rule does:
![image](https://user-images.githubusercontent.com/7189309/229275837-dae5b026-51c9-407c-81ef-b4de02e7e1a7.png)

And as I understand there are no outputs here.
