### ISSUE TITLE
Building NW54 on macOS Ventura fails at LINK ./v8_context_snapshot_generator

### ISSUE THREAD

**Issue by Suuuuuzy** [nwjs/nw.js#8059]
### Issue Type

Before opening an issue, please search and see if it has already been raised.

- [ ] Bug Report
- [ ] Feature Request

- [ ] Successfully reproduced against the latest version of NW.js?

> Please use our [mailing list](https://groups.google.com/forum/#!forum/nwjs-general) or [Gitter chatroom](https://gitter.im/nwjs/nw.js) to ask questions. The issue tracker is only for bugs and feature requests, in English only. Please note that issues without a repro or code snippet are less likely to be resolved.

### Current/Missing Behavior
Building fails at LINK ./v8_context_snapshot_generator
 
### Expected/Proposed Behavior
Should build successfully.

### Additional Info
I have researched the mailing list but only got this:
https://groups.google.com/g/nwjs-general/c/n6pAQk5Zmiw/m/71l4FYjZAAAJ
I tried with the arguments suggested in the discussion but did not succeed. Could you kindly take a look?

- Operating System: macOS Ventura
- NW.js Version: NW54
- Repro Link:
- Code snippet:
- Crash report:
ninja -C out/nw nwjs
ninja: Entering directory `out/nw'
[1259/48359] ACTION //content/nw/src/a...rator(//build/toolchain/mac:clang_x64)
nw.MenuItem must have a namespace-level comment. This will appear on the API summary page.
[1390/48359] ACTION //content/nw/src/a...ation(//build/toolchain/mac:clang_x64)
nw.MenuItem must have a namespace-level comment. This will appear on the API summary page.
[1393/48359] ACTION //content/nw/src/a...chema(//build/toolchain/mac:clang_x64)
nw.MenuItem must have a namespace-level comment. This will appear on the API summary page.
[47888/48359] LINK ./v8_context_snapshot_generator
FAILED: v8_context_snapshot_generator
TOOL_VERSION=1681369089 ../../build/toolchain/apple/linker_driver.py -Wcrl,strippath,/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip ../../third_party/llvm-build/Release+Asserts/bin/clang++ -B /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/  -Wl,-fatal_warnings -stdlib=libc++ -arch x86_64 -Werror -Wl,-dead_strip -nostdlib++ -isysroot ../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -mmacosx-version-min=10.11.0 -Wl,-ObjC -Wl,-rpath,@loader_path/. -lc++abi -Wl,-rpath,@loader_path/../../.. -Wl,-no_deduplicate -o "./v8_context_snapshot_generator" -Wl,-filelist,"./v8_context_snapshot_generator.rsp"   ./libgin.dylib ./libmojo_core_embedder.dylib ./libservice_manager_cpp.dylib ./libv8.dylib ./libbase.dylib ./libabsl.dylib ./libboringssl.dylib ./libperfetto.dylib ./libicui18n.dylib ./libicuuc.dylib ./libservice_manager_cpp_types.dylib ./libbindings.dylib ./libbindings_base.dylib ./libmojo_public_system_cpp.dylib ./libmojo_public_system.dylib ./libmojo_cpp_platform.dylib ./libmessage_support.dylib ./libmojo_mojom_bindings.dylib ./libmojo_mojom_bindings_shared.dylib ./libservice_manager_mojom.dylib ./libservice_manager_mojom_shared.dylib ./libservice_manager_mojom_constants_shared.dylib ./libmojo_base_mojom_shared.dylib ./libservice_manager_mojom_constants.dylib ./libmojo_base_mojom.dylib ./libmojo_base_lib.dylib ./libmojo_base_shared_typemap_traits.dylib ./libbase_i18n.dylib ./libmojo_base_typemap_traits.dylib ./libservice_manager_mojom_traits.dylib ./liburl.dylib ./libnet.dylib ./libprotobuf_lite.dylib ./libcrcrypto.dylib ./libskia.dylib ./libblink_common.dylib ./libprivacy_budget.dylib ./libmetrics_cpp.dylib ./liburl_mojom_traits.dylib ./libnetwork_cpp.dylib ./libnetwork_cpp_base.dylib ./libcookies_mojom_support.dylib ./libcrash_keys.dylib ./libcross_origin_embedder_policy.dylib ./libip_address_mojom_support.dylib ./libnetwork_param_mojom_support.dylib ./libschemeful_site_mojom_support.dylib ./libcontent_settings_features.dylib ./libipc.dylib ./libipc_mojom.dylib ./libipc_mojom_shared.dylib ./libtracing_cpp.dylib ./libstartup_tracing.dylib ./libtracing_mojom.dylib ./libtracing_mojom_shared.dylib ./libwebrtc_component.dylib ./liburl_ipc.dylib ./libskia_shared_typemap_traits.dylib ./libweb_feature_mojo_bindings_mojom.dylib ./libweb_feature_mojo_bindings_mojom_shared.dylib ./libmojom_platform_shared.dylib ./libandroid_mojo_bindings_shared.dylib ./libauthenticator_test_mojo_bindings_shared.dylib ./libcolor_scheme_mojo_bindings_shared.dylib ./libmojom_mhtml_load_result_shared.dylib ./libscript_type_mojom_shared.dylib ./libdom_storage_mojom_shared.dylib ./libframe_mojom_shared.dylib ./libblink_gpu_mojom_shared.dylib ./libservice_worker_storage_mojom_shared.dylib ./libtokens_mojom_shared.dylib ./libusb_shared.dylib ./libui_base_dragdrop_mojom_shared.dylib ./libgfx.dylib ./libcolor_space.dylib ./libcolor_utils.dylib ./libgeometry.dylib ./libgeometry_skia.dylib ./libgfx_switches.dylib ./libanimation.dylib ./libcodec.dylib ./librange.dylib ./libcc_paint.dylib ./libcc_base.dylib ./libcc_debug.dylib ./libgfx_native_types_shared_mojom_traits.dylib ./libgfx_shared_mojom_traits.dylib ./libgpu_shared_mojom_traits.dylib ./libgpu.dylib ./libmailbox.dylib ./libgfx_ipc.dylib ./libgfx_ipc_geometry.dylib ./libvulkan_ycbcr_info.dylib ./liblearning_common.dylib ./libmedia_learning_shared_typemap_traits.dylib ./libmedia_session_base_cpp.dylib ./libgl_wrapper.dylib ./libplatform.dylib ./libseatbelt_extension.dylib ./libmedia.dylib ./libshared_memory_support.dylib ./libleveldb_proto.dylib ./libkeyed_service_core.dylib ./libleveldatabase.dylib ./libgfx_ipc_color.dylib ./libgfx_ipc_buffer_types.dylib ./libcc.dylib ./libviz_common.dylib ./libviz_resource_format_utils.dylib ./libviz_metal_context_provider.dylib ./libui_base.dylib ./libui_base_features.dylib ./libui_data_pack.dylib ./libui_base_file_info.dylib ./libevents_base.dylib ./libcapture_base.dylib ./libmojom_modules_shared.dylib ./libmojom_core_shared.dylib ./libfido.dylib ./libbluetooth.dylib ./libscript_type_mojom.dylib ./liblatency_shared_mojom_traits.dylib ./libcc_ipc.dylib ./libcc_shared_mojom_traits.dylib ./libdom_storage_mojom.dylib ./libframe_mojom.dylib ./libblink_gpu_mojom.dylib ./libservice_worker_storage_mojom.dylib ./libtokens_traits.dylib ./libui_base_cursor_base.dylib ./libui_base_dragdrop_mojom.dylib ./libime_shared_mojom_traits.dylib ./libui_base_ime_types.dylib ./libdisplay_shared_mojom_traits.dylib ./libdisplay.dylib ./libdisplay_types.dylib ./libui_events_ipc.dylib ./libevents.dylib ./libvideo_capture_mojom_support.dylib ./libui_base_clipboard_types.dylib ./libweb_bluetooth_mojo_bindings_shared.dylib ./libax_base.dylib ./libui_accessibility_ax_mojom.dylib ./libui_accessibility_ax_mojom_shared.dylib ./libui_base_ime.dylib ./libprediction.dylib ./libcapture_lib.dylib ./libmedia_webrtc.dylib ./libwtf.dylib ./libblink_controller.dylib ./libblink_core.dylib ./libblink_mojom_broadcastchannel_bindings_shared.dylib ./libwtf_support.dylib ./libweb_feature_mojo_bindings_mojom_blink.dylib ./libmojo_base_mojom_blink.dylib ./libservice_manager_mojom_blink.dylib ./libservice_manager_mojom_constants_blink.dylib ./libchrome_zlib.dylib ./libblink_platform.dylib ./libcc_animation.dylib ./libgles2_utils.dylib ./libresource_coordinator_public_mojom_blink.dylib ./libresource_coordinator_public_mojom_shared.dylib ./libui_base_dragdrop_mojom_blink.dylib ./libkeyframe.dylib ./libblink_embedded_frame_sink_mojo_bindings_shared.dylib ./libperformance_manager_public_mojom_blink.dylib ./libperformance_manager_public_mojom_shared.dylib ./libcrdtp.dylib ./libui_accessibility_ax_mojom_blink.dylib ./libnative_theme.dylib ./libblink_modules.dylib ./libshared_with_blink.dylib ./libgamepad_mojom_blink.dylib ./libgamepad_mojom_shared.dylib ./libgamepad_shared_typemap_traits.dylib ./liburlpattern.dylib ./libdevice_vr_service_mojo_bindings_blink.dylib ./libdevice_vr_service_mojo_bindings_shared.dylib ./libdevice_vr_test_mojo_bindings_shared.dylib ./libdevice_vr_test_mojo_bindings_blink.dylib ./libdevice_vr_public_typemaps.dylib ./libc++.dylib
Undefined symbols for architecture x86_64:
  "v8::internal::compiler::CompileJSToJSWrapper(v8::internal::Isolate*, v8::internal::Signature<v8::internal::wasm::ValueType> const*, v8::internal::wasm::WasmModule const*)", referenced from:
      v8::internal::WasmJSFunction::New(v8::internal::Isolate*, v8::internal::Signature<v8::internal::wasm::ValueType> const*, v8::internal::Handle<v8::internal::JSReceiver>) in wasm-objects.o
  "v8::internal::compiler::CompileWasmToJSWrapper(v8::internal::Isolate*, v8::internal::Signature<v8::internal::wasm::ValueType> const*, v8::internal::compiler::WasmImportCallKind, int)", referenced from:
      v8::internal::WasmJSFunction::New(v8::internal::Isolate*, v8::internal::Signature<v8::internal::wasm::ValueType> const*, v8::internal::Handle<v8::internal::JSReceiver>) in wasm-objects.o
  "v8::internal::compiler::CompileWasmCapiCallWrapper(v8::internal::wasm::WasmEngine*, v8::internal::wasm::NativeModule*, v8::internal::Signature<v8::internal::wasm::ValueType> const*, unsigned long)", referenced from:
      v8::internal::wasm::InstanceBuilder::ProcessImportedFunction(v8::internal::Handle<v8::internal::WasmInstanceObject>, int, int, v8::internal::Handle<v8::internal::String>, v8::internal::Handle<v8::internal::String>, v8::internal::Handle<v8::internal::Object>) in module-instantiate.o
      v8::internal::WasmTableObject::UpdateDispatchTables(v8::internal::Isolate*, v8::internal::Handle<v8::internal::WasmTableObject>, int, v8::internal::Handle<v8::internal::WasmCapiFunction>) in wasm-objects.o
  "v8::internal::compiler::NewJSToWasmCompilationJob(v8::internal::Isolate*, v8::internal::wasm::WasmEngine*, v8::internal::Signature<v8::internal::wasm::ValueType> const*, v8::internal::wasm::WasmModule const*, bool, v8::internal::wasm::WasmFeatures const&)", referenced from:
      v8::internal::wasm::JSToWasmWrapperCompilationUnit::JSToWasmWrapperCompilationUnit(v8::internal::Isolate*, v8::internal::wasm::WasmEngine*, v8::internal::Signature<v8::internal::wasm::ValueType> const*, v8::internal::wasm::WasmModule const*, bool, v8::internal::wasm::WasmFeatures const&, v8::internal::wasm::JSToWasmWrapperCompilationUnit::AllowGeneric) in function-compiler.o
      v8::internal::wasm::JSToWasmWrapperCompilationUnit::CompileJSToWasmWrapper(v8::internal::Isolate*, v8::internal::Signature<v8::internal::wasm::ValueType> const*, v8::internal::wasm::WasmModule const*, bool) in function-compiler.o
      v8::internal::wasm::JSToWasmWrapperCompilationUnit::CompileSpecificJSToWasmWrapper(v8::internal::Isolate*, v8::internal::Signature<v8::internal::wasm::ValueType> const*, v8::internal::wasm::WasmModule const*) in function-compiler.o
  "v8::internal::compiler::ExecuteTurbofanWasmCompilation(v8::internal::wasm::WasmEngine*, v8::internal::wasm::CompilationEnv*, v8::internal::wasm::FunctionBody const&, int, v8::internal::Counters*, v8::internal::wasm::WasmFeatures*)", referenced from:
      v8::internal::wasm::WasmCompilationUnit::ExecuteFunctionCompilation(v8::internal::wasm::WasmEngine*, v8::internal::wasm::CompilationEnv*, std::__1::shared_ptr<v8::internal::wasm::WireBytesStorage> const&, v8::internal::Counters*, v8::internal::wasm::WasmFeatures*) in function-compiler.o
  "_v8_Default_embedded_blob_code_", referenced from:
      v8::internal::Isolate::InitializeDefaultEmbeddedBlob() in isolate.o
  "_v8_Default_embedded_blob_code_size_", referenced from:
      v8::internal::Isolate::InitializeDefaultEmbeddedBlob() in isolate.o
  "_v8_Default_embedded_blob_data_", referenced from:
      v8::internal::Isolate::InitializeDefaultEmbeddedBlob() in isolate.o
  "_v8_Default_embedded_blob_data_size_", referenced from:
      v8::internal::Isolate::InitializeDefaultEmbeddedBlob() in isolate.o
  "v8::internal::CheckObjectType(unsigned long, unsigned long, unsigned long)", referenced from:
      v8::internal::ExternalReference::check_object_type() in external-reference.o
  "v8::internal::Snapshot::DefaultSnapshotBlob()", referenced from:
      v8::SnapshotCreator::SnapshotCreator(v8::Isolate*, long const*, v8::StartupData*) in api.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Traceback (most recent call last):
  File "../../build/toolchain/apple/linker_driver.py", line 305, in <module>
    Main(sys.argv)
  File "../../build/toolchain/apple/linker_driver.py", line 98, in Main
    subprocess.check_call(compiler_driver_args, env=env)
  File "/Users/jianjia/opt/anaconda3/envs/py27/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['../../third_party/llvm-build/Release+Asserts/bin/clang++', '-B', '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/', '-Wl,-fatal_warnings', '-stdlib=libc++', '-arch', 'x86_64', '-Werror', '-Wl,-dead_strip', '-nostdlib++', '-isysroot', '../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk', '-mmacosx-version-min=10.11.0', '-Wl,-ObjC', '-Wl,-rpath,@loader_path/.', '-lc++abi', '-Wl,-rpath,@loader_path/../../..', '-Wl,-no_deduplicate', '-o', './v8_context_snapshot_generator', '-Wl,-filelist,./v8_context_snapshot_generator.rsp', './libgin.dylib', './libmojo_core_embedder.dylib', './libservice_manager_cpp.dylib', './libv8.dylib', './libbase.dylib', './libabsl.dylib', './libboringssl.dylib', './libperfetto.dylib', './libicui18n.dylib', './libicuuc.dylib', './libservice_manager_cpp_types.dylib', './libbindings.dylib', './libbindings_base.dylib', './libmojo_public_system_cpp.dylib', './libmojo_public_system.dylib', './libmojo_cpp_platform.dylib', './libmessage_support.dylib', './libmojo_mojom_bindings.dylib', './libmojo_mojom_bindings_shared.dylib', './libservice_manager_mojom.dylib', './libservice_manager_mojom_shared.dylib', './libservice_manager_mojom_constants_shared.dylib', './libmojo_base_mojom_shared.dylib', './libservice_manager_mojom_constants.dylib', './libmojo_base_mojom.dylib', './libmojo_base_lib.dylib', './libmojo_base_shared_typemap_traits.dylib', './libbase_i18n.dylib', './libmojo_base_typemap_traits.dylib', './libservice_manager_mojom_traits.dylib', './liburl.dylib', './libnet.dylib', './libprotobuf_lite.dylib', './libcrcrypto.dylib', './libskia.dylib', './libblink_common.dylib', './libprivacy_budget.dylib', './libmetrics_cpp.dylib', './liburl_mojom_traits.dylib', './libnetwork_cpp.dylib', './libnetwork_cpp_base.dylib', './libcookies_mojom_support.dylib', './libcrash_keys.dylib', './libcross_origin_embedder_policy.dylib', './libip_address_mojom_support.dylib', './libnetwork_param_mojom_support.dylib', './libschemeful_site_mojom_support.dylib', './libcontent_settings_features.dylib', './libipc.dylib', './libipc_mojom.dylib', './libipc_mojom_shared.dylib', './libtracing_cpp.dylib', './libstartup_tracing.dylib', './libtracing_mojom.dylib', './libtracing_mojom_shared.dylib', './libwebrtc_component.dylib', './liburl_ipc.dylib', './libskia_shared_typemap_traits.dylib', './libweb_feature_mojo_bindings_mojom.dylib', './libweb_feature_mojo_bindings_mojom_shared.dylib', './libmojom_platform_shared.dylib', './libandroid_mojo_bindings_shared.dylib', './libauthenticator_test_mojo_bindings_shared.dylib', './libcolor_scheme_mojo_bindings_shared.dylib', './libmojom_mhtml_load_result_shared.dylib', './libscript_type_mojom_shared.dylib', './libdom_storage_mojom_shared.dylib', './libframe_mojom_shared.dylib', './libblink_gpu_mojom_shared.dylib', './libservice_worker_storage_mojom_shared.dylib', './libtokens_mojom_shared.dylib', './libusb_shared.dylib', './libui_base_dragdrop_mojom_shared.dylib', './libgfx.dylib', './libcolor_space.dylib', './libcolor_utils.dylib', './libgeometry.dylib', './libgeometry_skia.dylib', './libgfx_switches.dylib', './libanimation.dylib', './libcodec.dylib', './librange.dylib', './libcc_paint.dylib', './libcc_base.dylib', './libcc_debug.dylib', './libgfx_native_types_shared_mojom_traits.dylib', './libgfx_shared_mojom_traits.dylib', './libgpu_shared_mojom_traits.dylib', './libgpu.dylib', './libmailbox.dylib', './libgfx_ipc.dylib', './libgfx_ipc_geometry.dylib', './libvulkan_ycbcr_info.dylib', './liblearning_common.dylib', './libmedia_learning_shared_typemap_traits.dylib', './libmedia_session_base_cpp.dylib', './libgl_wrapper.dylib', './libplatform.dylib', './libseatbelt_extension.dylib', './libmedia.dylib', './libshared_memory_support.dylib', './libleveldb_proto.dylib', './libkeyed_service_core.dylib', './libleveldatabase.dylib', './libgfx_ipc_color.dylib', './libgfx_ipc_buffer_types.dylib', './libcc.dylib', './libviz_common.dylib', './libviz_resource_format_utils.dylib', './libviz_metal_context_provider.dylib', './libui_base.dylib', './libui_base_features.dylib', './libui_data_pack.dylib', './libui_base_file_info.dylib', './libevents_base.dylib', './libcapture_base.dylib', './libmojom_modules_shared.dylib', './libmojom_core_shared.dylib', './libfido.dylib', './libbluetooth.dylib', './libscript_type_mojom.dylib', './liblatency_shared_mojom_traits.dylib', './libcc_ipc.dylib', './libcc_shared_mojom_traits.dylib', './libdom_storage_mojom.dylib', './libframe_mojom.dylib', './libblink_gpu_mojom.dylib', './libservice_worker_storage_mojom.dylib', './libtokens_traits.dylib', './libui_base_cursor_base.dylib', './libui_base_dragdrop_mojom.dylib', './libime_shared_mojom_traits.dylib', './libui_base_ime_types.dylib', './libdisplay_shared_mojom_traits.dylib', './libdisplay.dylib', './libdisplay_types.dylib', './libui_events_ipc.dylib', './libevents.dylib', './libvideo_capture_mojom_support.dylib', './libui_base_clipboard_types.dylib', './libweb_bluetooth_mojo_bindings_shared.dylib', './libax_base.dylib', './libui_accessibility_ax_mojom.dylib', './libui_accessibility_ax_mojom_shared.dylib', './libui_base_ime.dylib', './libprediction.dylib', './libcapture_lib.dylib', './libmedia_webrtc.dylib', './libwtf.dylib', './libblink_controller.dylib', './libblink_core.dylib', './libblink_mojom_broadcastchannel_bindings_shared.dylib', './libwtf_support.dylib', './libweb_feature_mojo_bindings_mojom_blink.dylib', './libmojo_base_mojom_blink.dylib', './libservice_manager_mojom_blink.dylib', './libservice_manager_mojom_constants_blink.dylib', './libchrome_zlib.dylib', './libblink_platform.dylib', './libcc_animation.dylib', './libgles2_utils.dylib', './libresource_coordinator_public_mojom_blink.dylib', './libresource_coordinator_public_mojom_shared.dylib', './libui_base_dragdrop_mojom_blink.dylib', './libkeyframe.dylib', './libblink_embedded_frame_sink_mojo_bindings_shared.dylib', './libperformance_manager_public_mojom_blink.dylib', './libperformance_manager_public_mojom_shared.dylib', './libcrdtp.dylib', './libui_accessibility_ax_mojom_blink.dylib', './libnative_theme.dylib', './libblink_modules.dylib', './libshared_with_blink.dylib', './libgamepad_mojom_blink.dylib', './libgamepad_mojom_shared.dylib', './libgamepad_shared_typemap_traits.dylib', './liburlpattern.dylib', './libdevice_vr_service_mojo_bindings_blink.dylib', './libdevice_vr_service_mojo_bindings_shared.dylib', './libdevice_vr_test_mojo_bindings_shared.dylib', './libdevice_vr_test_mojo_bindings_blink.dylib', './libdevice_vr_public_typemaps.dylib', './libc++.dylib']' returned non-zero exit status 1
[47889/48359] SOLINK libcontent.dylib libcontent.dylib.TOC
ninja: build stopped: subcommand failed.

**Comment by Cubelrti** [comment]
Commenting out those lines in `src/tools/v8_context_snapshot/BUILD.gn` fix this
around Line 127
```
    if (is_win && is_component_build) {
    } else {
      # deps += [
      #   "//v8:v8_initializers",
      # ]
    }
```
