### ISSUE TITLE
NW.js0.75.0 debug build fails on Windows 

### ISSUE THREAD

**Issue by a379933101** [nwjs/nw.js#8061]
1.when I set the build args "is_component_build=true" or  "is_debug=true" ,it build failed!
gn gen out_debug/nw "--args=is_component_build=true is_debug=true target_cpu=\"x86\""
error log :
FAILED: obj/buildtools/third_party/libc++/libcpp.lib
..\..\third_party\llvm-build\Release+Asserts\bin\lld-link.exe /lib /OUT:obj/buildtools/third_party/libc++/libcpp.lib /nologo /WX /ignore:4221 /llvmlibthin @obj/buildtools/third_party/libc++/libcpp.lib.rsp
warning: no input files, not writing output file
         pass /llvmlibempty to write empty .lib file,
         pass /ignore:emptyoutput to suppress warning
treating warning as error due to /WX
lld-link: error: lib failed

when I set the build args "is_component_build=false" and  "is_debug=false",it it ok!

2.the shell "python ./build/gyp_chromium -I third_party/node-nw/common.gypi -D building_nw=1 -D clang=1 third_party/node-nw/node.gyp" run error!
log:
 Traceback (most recent call last):
  File "./build/gyp_chromium", line 12, in <module>
    execfile(__file__ + '.py')
  File "./build/gyp_chromium.py", line 7, in <module>
    import gyp_environment
  File "D:\nwjs2\src\build\gyp_environment.py", line 13, in <module>
    import vs_toolchain
  File "D:\nwjs2\src\build\vs_toolchain.py", line 475
    print('Unknown parameter "%s"' % force, file=sys.stderr)

3. when I build on Mechanical hard drive ,[1/53536] LIB obj ... , it is ok!
    but on SSD(sn570) hard disk, it show  [1/54587], LIB obj ... ,when build complete, The application cannot start!

**Comment by epitaphial** [comment]
I have the same issue, "print('Unknown parameter "%s"' % force, file=sys.stderr)" give me a SyntaxError when I build node of nwjs, and I try to switch to py2, it does not work...

**Comment by liuyi520123** [comment]
When I compile with nw85 on Ubuntu 22, and execute the command 
`$NWJSDIR/src/build/gyp_chromium -I third_party/node-nw/common.gypi third_party/node-nw/node.gyp`
, using Python 3 throws an error:
`File "/root/nwjs85/src/build/vs_toolchain.py", line 486
    print('Unknown parameter "%s"' % force, file=sys.stderr)
                                                ^
SyntaxError: invalid syntax`

Using Python 2 also throws an error:
`File "/root/nwjs85/src/build/vs_toolchain.py", line 486
    print('Unknown parameter "%s"' % force, file=sys.stderr)
                                                ^
SyntaxError: invalid syntax`

I'm really not sure how to deal with this.
