### ISSUE TITLE
[Bug Report][0.79.0+0.79.1] Debug in VS Code  with "Debugger for NWjs" (plugin), but will crash after the window display.

### ISSUE THREAD

**Issue by liuyi** [nwjs/nw.js#8112]
### Issue Type
- [ y] Bug Report
- [ ] Feature Request

- [ y] Successfully reproduced against the latest version of NW.js?
- 0.79.0 , 0.79.1  mac normal

the debugger runs ok   on version less than 0.79.0,  such as 0.78.1 and 0.76.1 and so on ;
 

### Current/Missing Behavior
Debug in VS Code  with "Debugger for NWjs" (plugin), but will crash after the window display.
 error log:
`Error processing "launch": Error: Script execution is prohibited
    at Client.processMessage (/Users/liuyi/.vscode/extensions/ruakr.vsc-nwjs-1.0.18/node_modules/noice-json-rpc/lib/noice-json-rpc.js:66:36)
    at LoggingSocket.<anonymous> (/Users/liuyi/.vscode/extensions/ruakr.vsc-nwjs-1.0.18/node_modules/noice-json-rpc/lib/noice-json-rpc.js:42:48)
    at LoggingSocket.emit (node:events:525:35)
    at Receiver.receiverOnMessage (/Users/liuyi/.vscode/extensions/ruakr.vsc-nwjs-1.0.18/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (/Users/liuyi/.vscode/extensions/ruakr.vsc-nwjs-1.0.18/node_modules/ws/lib/receiver.js:422:14)
    at /Users/liuyi/.vscode/extensions/ruakr.vsc-nwjs-1.0.18/node_modules/ws/lib/receiver.js:379:23
    at /Users/liuyi/.vscode/extensions/ruakr.vsc-nwjs-1.0.18/node_modules/ws/lib/permessage-deflate.js:298:9
    at /Users/liuyi/.vscode/extensions/ruakr.vsc-nwjs-1.0.18/node_modules/ws/lib/permessage-deflate.js:376:7
    at afterWrite (node:internal/streams/writable:499:5)`

 

- Operating System: macOS 13.5.1 (22G90)  MacBook Pro 2019
- NW.js Version: 0.79.1

**Comment by ayushmanchhabra** [comment]
https://github.com/karikera/vscode-nwjs-debug
This VSCode plugin does not look like its been maintained for some time.

If your app works without debugger and crashes with it, the issue is with the VS Code extension.
